"""Generated by `mise run codegen:regen` from `crates/wyrd-spec/schemas/card.json`. Do not edit."""

from __future__ import annotations

from typing import Literal, TypeAlias, TypedDict

JsonValue: TypeAlias = "str | int | float | bool | None | list[JsonValue] | dict[str, JsonValue]"


class AgentRunConfigSpec(TypedDict, total=False):
    """Pure-serde mirror of the Skald agent run configuration."""

    max_iterations: int | None
    session_recent_limit: int | None
    timeout_ms: int | None
    tool_concurrency_cap: int | None


class _AgentSpecRequired(TypedDict):
    """Required keys of `AgentSpec`."""

    prompt: InlineableRef_for_Prompt


class AgentSpec(_AgentSpecRequired, total=False):
    """Agent authoring body inside a Wyrd Agent Card envelope."""

    run_config: AgentRunConfigSpec
    tool_names: list[str]
    verified_by: list[VerificationBinding]


# Validated value for free-form Card annotations.
AnnotationValue: TypeAlias = "str"


class _AnthropicCacheControlRequired(TypedDict):
    """Required keys of `AnthropicCacheControl`."""

    type: str


class AnthropicCacheControl(_AnthropicCacheControlRequired, total=False):
    """Generated Card schema type."""

    ttl: str | None


class AnthropicCitationToggle(TypedDict):
    """Generated Card schema type."""

    enabled: bool


# Anthropic citation block.
AnthropicCitationV1: TypeAlias = "AnthropicCitationV1CharLocation | AnthropicCitationV1PageLocation | AnthropicCitationV1ContentBlockLocation | AnthropicCitationV1WebSearchResultLocation | AnthropicCitationV1SearchResultLocation"


class _AnthropicCitationV1CharLocationRequired(TypedDict):
    """Required keys of `AnthropicCitationV1CharLocation`."""

    cited_text: str
    document_index: int
    end_char_index: int
    start_char_index: int
    type: Literal["char_location"]


class AnthropicCitationV1CharLocation(_AnthropicCitationV1CharLocationRequired, total=False):
    """Generated Card schema type."""

    document_title: str | None


class _AnthropicCitationV1ContentBlockLocationRequired(TypedDict):
    """Required keys of `AnthropicCitationV1ContentBlockLocation`."""

    cited_text: str
    document_index: int
    end_block_index: int
    start_block_index: int
    type: Literal["content_block_location"]


class AnthropicCitationV1ContentBlockLocation(
    _AnthropicCitationV1ContentBlockLocationRequired, total=False
):
    """Generated Card schema type."""

    document_title: str | None


class _AnthropicCitationV1PageLocationRequired(TypedDict):
    """Required keys of `AnthropicCitationV1PageLocation`."""

    cited_text: str
    document_index: int
    end_page_number: int
    start_page_number: int
    type: Literal["page_location"]


class AnthropicCitationV1PageLocation(_AnthropicCitationV1PageLocationRequired, total=False):
    """Generated Card schema type."""

    document_title: str | None


class _AnthropicCitationV1SearchResultLocationRequired(TypedDict):
    """Required keys of `AnthropicCitationV1SearchResultLocation`."""

    cited_text: str
    end_block_index: int
    search_result_index: int
    source: str
    start_block_index: int
    type: Literal["search_result_location"]


class AnthropicCitationV1SearchResultLocation(
    _AnthropicCitationV1SearchResultLocationRequired, total=False
):
    """Generated Card schema type."""

    title: str | None


class _AnthropicCitationV1WebSearchResultLocationRequired(TypedDict):
    """Required keys of `AnthropicCitationV1WebSearchResultLocation`."""

    cited_text: str
    type: Literal["web_search_result_location"]
    url: str


class AnthropicCitationV1WebSearchResultLocation(
    _AnthropicCitationV1WebSearchResultLocationRequired, total=False
):
    """Generated Card schema type."""

    encrypted_index: str | None
    title: str | None


AnthropicContentBlock: TypeAlias = "AnthropicContentBlockText | AnthropicContentBlockImage | AnthropicContentBlockDocument | AnthropicContentBlockThinking | AnthropicContentBlockRedactedThinking | AnthropicContentBlockToolUse | AnthropicContentBlockToolResult"


class _AnthropicContentBlockDocumentRequired(TypedDict):
    """Required keys of `AnthropicContentBlockDocument`."""

    source: AnthropicDocumentSource
    type: Literal["document"]


class AnthropicContentBlockDocument(_AnthropicContentBlockDocumentRequired, total=False):
    """Generated Card schema type."""

    cache_control: AnthropicCacheControl | None
    citations: AnthropicCitationToggle | None
    context: str | None
    title: str | None


class _AnthropicContentBlockImageRequired(TypedDict):
    """Required keys of `AnthropicContentBlockImage`."""

    source: AnthropicImageSource
    type: Literal["image"]


class AnthropicContentBlockImage(_AnthropicContentBlockImageRequired, total=False):
    """Generated Card schema type."""

    cache_control: AnthropicCacheControl | None


class AnthropicContentBlockRedactedThinking(TypedDict):
    """Generated Card schema type."""

    data: str
    type: Literal["redacted_thinking"]


class _AnthropicContentBlockTextRequired(TypedDict):
    """Required keys of `AnthropicContentBlockText`."""

    text: str
    type: Literal["text"]


class AnthropicContentBlockText(_AnthropicContentBlockTextRequired, total=False):
    """Generated Card schema type."""

    cache_control: AnthropicCacheControl | None
    citations: list[AnthropicCitationV1] | None


class AnthropicContentBlockThinking(TypedDict):
    """Generated Card schema type."""

    signature: str
    thinking: str
    type: Literal["thinking"]


class _AnthropicContentBlockToolResultRequired(TypedDict):
    """Required keys of `AnthropicContentBlockToolResult`."""

    content: AnthropicToolResultContent
    tool_use_id: str
    type: Literal["tool_result"]


class AnthropicContentBlockToolResult(_AnthropicContentBlockToolResultRequired, total=False):
    """Generated Card schema type."""

    cache_control: AnthropicCacheControl | None
    is_error: bool | None


class AnthropicContentBlockToolUse(TypedDict):
    """Generated Card schema type."""

    id: str
    input: JsonValue
    name: str
    type: Literal["tool_use"]


AnthropicDocumentSource: TypeAlias = "AnthropicDocumentSourceBase64 | AnthropicDocumentSourceUrl | AnthropicDocumentSourceFileId | AnthropicDocumentSourceText | AnthropicDocumentSourceContent"


class AnthropicDocumentSourceBase64(TypedDict):
    """Generated Card schema type."""

    data: str
    media_type: str
    type: Literal["base64"]


class AnthropicDocumentSourceContent(TypedDict):
    """Generated Card schema type."""

    content: list[AnthropicContentBlock]
    type: Literal["content"]


class AnthropicDocumentSourceFileId(TypedDict):
    """Generated Card schema type."""

    file_id: str
    type: Literal["file_id"]


class AnthropicDocumentSourceText(TypedDict):
    """Generated Card schema type."""

    data: str
    media_type: str
    type: Literal["text"]


class AnthropicDocumentSourceUrl(TypedDict):
    """Generated Card schema type."""

    type: Literal["url"]
    url: str


AnthropicImageSource: TypeAlias = (
    "AnthropicImageSourceBase64 | AnthropicImageSourceUrl | AnthropicImageSourceFileId"
)


class AnthropicImageSourceBase64(TypedDict):
    """Generated Card schema type."""

    data: str
    media_type: str
    type: Literal["base64"]


class AnthropicImageSourceFileId(TypedDict):
    """Generated Card schema type."""

    file_id: str
    type: Literal["file_id"]


class AnthropicImageSourceUrl(TypedDict):
    """Generated Card schema type."""

    type: Literal["url"]
    url: str


class AnthropicMessage(TypedDict):
    """One Anthropic message."""

    content: list[AnthropicContentBlock]
    role: str


class _AnthropicMessagesRequestRequired(TypedDict):
    """Required keys of `AnthropicMessagesRequest`."""

    max_tokens: int
    messages: list[AnthropicMessage]
    model: str


class AnthropicMessagesRequest(_AnthropicMessagesRequestRequired, total=False):
    """`POST /v1/messages`."""

    metadata: dict[str, JsonValue] | None
    output_config: AnthropicOutputConfig | None
    stop_sequences: list[str] | None
    stream: bool | None
    system: AnthropicSystem | None
    temperature: float | None
    thinking: AnthropicThinkingConfig | None
    tool_choice: JsonValue
    tools: list[AnthropicTool] | None
    top_k: int | None
    top_p: float | None


class AnthropicOutputConfig(TypedDict):
    """Anthropic `output_config` block on a `/v1/messages` request."""

    format: AnthropicOutputFormat


# Anthropic output-format variants.
AnthropicOutputFormat: TypeAlias = "AnthropicOutputFormatJsonSchema"


class AnthropicOutputFormatJsonSchema(TypedDict):
    """JSON schema enforced by Anthropic at generation time."""

    schema: JsonValue
    type: Literal["json_schema"]


AnthropicSystem: TypeAlias = "str | list[AnthropicSystemBlock]"

AnthropicSystemBlock: TypeAlias = "AnthropicSystemBlockText"


class _AnthropicSystemBlockTextRequired(TypedDict):
    """Required keys of `AnthropicSystemBlockText`."""

    text: str
    type: Literal["text"]


class AnthropicSystemBlockText(_AnthropicSystemBlockTextRequired, total=False):
    """Generated Card schema type."""

    cache_control: AnthropicCacheControl | None


class _AnthropicThinkingConfigRequired(TypedDict):
    """Required keys of `AnthropicThinkingConfig`."""

    type: str


class AnthropicThinkingConfig(_AnthropicThinkingConfigRequired, total=False):
    """Generated Card schema type."""

    budget_tokens: int | None


class _AnthropicToolRequired(TypedDict):
    """Required keys of `AnthropicTool`."""

    input_schema: JsonValue
    name: str


class AnthropicTool(_AnthropicToolRequired, total=False):
    """Generated Card schema type."""

    cache_control: AnthropicCacheControl | None
    description: str | None
    display_height_px: int | None
    display_number: int | None
    display_width_px: int | None
    type: str | None


AnthropicToolResultContent: TypeAlias = "str | list[AnthropicContentBlock]"

# Canonical Wyrd API version.
ApiVersion: TypeAlias = "str"

# Arrow serialization formats accepted by DataCard.
ArrowFormat: TypeAlias = 'Literal["Ipc", "Parquet"]'


class ArrowMeta(TypedDict):
    """Arrow interface metadata."""

    format: ArrowFormat
    framework_version: str


# Wyrd Card kind.
CardKind: TypeAlias = 'Literal["Data", "Model", "Experiment", "Prompt", "Agent", "Workflow", "Verifier", "Service", "Policy", "Mcp", "Audit", "Artifact", "Trigger", "Operator", "Source"]'

# Human-visible Card name.
CardName: TypeAlias = "str"


class _CardRefRequired(TypedDict):
    """Required keys of `CardRef`."""

    kind: CardKind
    name: CardName
    version: VersionBlock


class CardRef(_CardRefRequired, total=False):
    """Reference to a registered Card by kind, name, version, optional space, and optional UID."""

    space: SpaceName | None
    uid: CardUid | None


class _CardRelationshipRequired(TypedDict):
    """Required keys of `CardRelationship`."""

    ref: CardRef


class CardRelationship(_CardRelationshipRequired, total=False):
    """One server-derived relationship edge."""

    alias: str | None


# Resolved immutable Card UID.
CardUid: TypeAlias = "str"


class _CatboostMetaRequired(TypedDict):
    """Required keys of `CatboostMeta`."""

    framework_version: str


class CatboostMeta(_CatboostMetaRequired, total=False):
    """Config for the Catboost model interface."""

    model_subtype: str | None


# Literal value used by a column split predicate.
ColValue: TypeAlias = "int | float | str | bool | list[ColValue]"

# Image color mode accepted by DataCard image manifests.
ColorMode: TypeAlias = 'Literal["Rgb", "Rgba", "Grayscale"]'

# DataCard column name.
ColumnName: TypeAlias = "str"

CommitSha: TypeAlias = "str"

ComparisonOperator: TypeAlias = (
    "ParameterlessComparisonOperatorSchema | ParameterizedComparisonOperator"
)


class ComponentSource(TypedDict):
    """Development-time local source resolved by `lock` or `install`."""

    kind: str
    path: str


# Logical combinator between two adjacent [`EvalCondition`] nodes.
ConditionCombinator: TypeAlias = 'Literal["and", "or"]'

# Immutable tenant-scoped Operator connection name, unique per provider.
ConnectionName: TypeAlias = "str"


class CredentialRef(TypedDict):
    """Reference to a credential or secret managed outside public Card specs."""

    name: str
    provider: str


class _CustomDataMetaRequired(TypedDict):
    """Required keys of `CustomDataMeta`."""

    loader_class: str
    loader_module: str


class CustomDataMeta(_CustomDataMetaRequired, total=False):
    """Custom Python loader metadata."""

    extra: dict[str, str]


class _CustomMetaRequired(TypedDict):
    """Required keys of `CustomMeta`."""

    framework_version: str
    loader_class: str
    loader_module: str


class CustomMeta(_CustomMetaRequired, total=False):
    """Config for the Custom model interface."""

    extra: dict[str, str]
    model_subtype: str | None


# Data source interface metadata.
DataInterface: TypeAlias = "DataInterfacePandas | DataInterfacePolars | DataInterfaceArrow | DataInterfaceParquet | DataInterfaceNumpy | DataInterfaceTorch | DataInterfaceSql | DataInterfaceJsonl | DataInterfaceImage | DataInterfaceText | DataInterfaceHuggingface | DataInterfaceCustom"


class DataInterfaceArrow(TypedDict):
    """PyArrow table saved as IPC or parquet."""

    kind: Literal["Arrow"]
    meta: ArrowMeta


class DataInterfaceCustom(TypedDict):
    """Custom Python data loader."""

    kind: Literal["Custom"]
    meta: CustomDataMeta


class DataInterfaceHuggingface(TypedDict):
    """Hugging Face dataset pointer or local dataset."""

    kind: Literal["Huggingface"]
    meta: HuggingfaceMeta


class DataInterfaceImage(TypedDict):
    """Image manifest data."""

    kind: Literal["Image"]
    meta: ImageMeta


class DataInterfaceJsonl(TypedDict):
    """JSON Lines data."""

    kind: Literal["Jsonl"]
    meta: JsonlMeta


class DataInterfaceNumpy(TypedDict):
    """NumPy array saved as NPY or NPZ."""

    kind: Literal["Numpy"]
    meta: NumpyMeta


class DataInterfacePandas(TypedDict):
    """Pandas dataframe saved as parquet by default."""

    kind: Literal["Pandas"]
    meta: PandasMeta


class DataInterfaceParquet(TypedDict):
    """Existing parquet dataset or file."""

    kind: Literal["Parquet"]
    meta: ParquetMeta


class DataInterfacePolars(TypedDict):
    """Polars dataframe saved as parquet by default."""

    kind: Literal["Polars"]
    meta: PolarsMeta


class DataInterfaceSql(TypedDict):
    """SQL query bundle."""

    kind: Literal["Sql"]
    meta: SqlMeta


class DataInterfaceText(TypedDict):
    """Text manifest data."""

    kind: Literal["Text"]
    meta: TextMeta


class DataInterfaceTorch(TypedDict):
    """Torch tensor saved as safetensors or explicit pickle."""

    kind: Literal["Torch"]
    meta: TorchMeta


class DataSchema(TypedDict, total=False):
    """Ordered data schema for DataCard interfaces."""

    columns: list[FieldSpec]


class _DataSpecRequired(TypedDict):
    """Required keys of `DataSpec`."""

    interface: DataInterface
    schema: DataSchema
    stats: DataStats


class DataSpec(_DataSpecRequired, total=False):
    """Pure-data contract for a Data Card."""

    card_refs: list[Ref]
    splits: dict[str, DataSplit]
    sql: SqlLogic | None
    target_columns: list[ColumnName]


class DataSplit(TypedDict):
    """Named DataCard split declaration."""

    label: SplitName
    strategy: SplitStrategy


class _DataStatsRequired(TypedDict):
    """Required keys of `DataStats`."""

    byte_count: int
    sha256: str


class DataStats(_DataStatsRequired, total=False):
    """Storage and byte-level statistics for a DataCard source."""

    col_count: int | None
    row_count: int | None


# One dimension in a field shape.
Dim: TypeAlias = "DimFixed | DimDynamic"


class DimDynamic(TypedDict):
    """A dynamic dimension, optionally named for documentation and signatures."""

    kind: Literal["Dynamic"]
    value: str | None


class DimFixed(TypedDict):
    """A fixed, known dimension length."""

    kind: Literal["Fixed"]
    value: int


# Probability-divergence metric used by [`ComparisonOperator::DivergenceLessThan`].
DivergenceMetric: TypeAlias = 'Literal["kl", "js", "wasserstein"]'

# Lifecycle of one PSI or SPC Verifier's server-fitted baseline.
#
# Registration creates it `pending`; the fitter claims it `building` and settles it `ready` with the persisted fitted profile or `failed` with a structured error. A failed fit is retried through the same record while attempts remain, so `failed` is visible without being necessarily final.
DriftBaselineState: TypeAlias = 'Literal["pending", "building", "ready", "failed"]'


class _DriftBaselineStatusRequired(TypedDict):
    """Required keys of `DriftBaselineStatus`."""

    data: CardRef
    state: DriftBaselineState


class DriftBaselineStatus(_DriftBaselineStatusRequired, total=False):
    """Server-derived fitted-baseline status of a PSI or SPC Drift Verifier.

    Served on `card.status.verification.baseline`; it never mutates the authored spec.
    """

    error: VerificationError | None


# Fire condition for a drift observation.
DriftCondition: TypeAlias = (
    "DriftConditionStatistical | DriftConditionAbove | DriftConditionBelow | DriftConditionOutside"
)


class DriftConditionAbove(TypedDict):
    """Fires when sample > limit."""

    kind: Literal["Above"]
    limit: float


class DriftConditionBelow(TypedDict):
    """Fires when sample < limit."""

    kind: Literal["Below"]
    limit: float


class DriftConditionOutside(TypedDict):
    """Fires when sample < lower or sample > upper."""

    kind: Literal["Outside"]
    lower: float
    upper: float


class DriftConditionStatistical(TypedDict):
    """The method's profile decides, such as PSI threshold or SPC zone."""

    kind: Literal["Statistical"]


# Drift detection method.
#
# `Agent` is intentionally absent in v1. It can return only after the signal vocabulary, profile, and scoring algorithm are locked in `wyrd-design.md`.
DriftMethod: TypeAlias = 'Literal["Psi", "Spc", "Custom"]'

# Method-specific math configuration. Config only; fitted state lives in `vala-drift::baseline`, never here.
DriftProfile: TypeAlias = "DriftProfilePsi | DriftProfileSpc | DriftProfileCustom"


class DriftProfileCustom(TypedDict):
    """Custom profile configuration."""

    alert_threshold: float
    baseline_value: float
    kind: Literal["Custom"]
    metric_name: str


class _DriftProfilePsiRequired(TypedDict):
    """Required keys of `DriftProfilePsi`."""

    binning_strategy: PsiBinningStrategy
    kind: Literal["Psi"]
    threshold: PsiThreshold


class DriftProfilePsi(_DriftProfilePsiRequired, total=False):
    """PSI profile configuration."""

    categorical_features: list[FeatureName]


class DriftProfileSpc(TypedDict):
    """SPC profile configuration."""

    kind: Literal["Spc"]
    sample_size: int


# How measurements enter the drift monitor.
DriftSignal: TypeAlias = "DriftSignalDistribution | DriftSignalMetric"


class DriftSignalDistribution(TypedDict):
    """PSI or SPC over a baseline dataset."""

    baseline_ref: Ref
    features: list[FeatureName]
    kind: Literal["Distribution"]


class DriftSignalMetric(TypedDict):
    """Named scalar emitted by the subject's runtime."""

    kind: Literal["Metric"]
    name: str


class _DriftSpecRequired(TypedDict):
    """Required keys of `DriftSpec`."""

    condition: DriftCondition
    method: DriftMethod
    signal: DriftSignal


class DriftSpec(_DriftSpecRequired, total=False):
    """Drift Verifier implementation spec body.

    Reached only as `implementation.spec` on a `Verifier` Card; `drift` is an implementation discriminator, never an envelope `kind`.
    """

    description: str | None
    profile: DriftProfile | None


class _EvalConditionRequired(TypedDict):
    """Required keys of `EvalCondition`."""

    expected: JsonValue
    operator: ComparisonOperator
    path: JsonPath


class EvalCondition(_EvalConditionRequired, total=False):
    """A typed predicate evaluated against one JSON value extracted from workflow context or scenario payload.

    To chain conditions, set both [`EvalCondition::combinator`] and [`EvalCondition::subsequent`]. The whole chain is evaluated left-to-right with `AND` short-circuit on false and `OR` short-circuit on true.
    """

    combinator: ConditionCombinator | None
    subsequent: EvalCondition | None


# Declares how `vala-eval` populates [`AssertionResult::actual`] when writing result rows to `eval_task_results`.
#
# Evaluation correctness ([`AssertionResult::passed`]) is unaffected by this setting. Only the stored snapshot of the extracted value changes.
#
# Set at the [`super::spec::EvalSpec`] level via `context_capture`. Absent means `Full`.
EvalContextCapture: TypeAlias = 'Literal["full", "hash", "redact"]'

# Workflow-level pass criterion.
#
# Selects how [`AssertionResult`] rows roll up into the workflow's `pass / fail` outcome. Thresholds are in `[0.0, 1.0]`; out-of-range values are rejected by [`EvalPassGate::validate`].
EvalPassGate: TypeAlias = (
    "EvalPassGateOverallPassRate | EvalPassGatePerJudgePassRate | EvalPassGateAllPass"
)


class EvalPassGateAllPass(TypedDict):
    """Pass iff every task passes."""

    kind: Literal["all_pass"]


class EvalPassGateOverallPassRate(TypedDict):
    """Pass iff `(passed_tasks / total_tasks) >= threshold`."""

    kind: Literal["overall_pass_rate"]
    threshold: float


class EvalPassGatePerJudgePassRate(TypedDict):
    """Pass iff the minimum per-task pass rate across **all** tasks meets the threshold.

    Computed as `min(pass_rate per task across all subjects)`. A task that never appears scores 0.0. This is task-level, not judge-type-level — `LlmJudge` and other task types all contribute equally.
    """

    kind: Literal["per_judge_pass_rate"]
    threshold: float


# Sampling policy applied at the record-ingest boundary.
#
# `vala-eval` enforces the policy when records are admitted for evaluation.
EvalSampling: TypeAlias = (
    "EvalSamplingRatio | EvalSamplingDeterministicByHash | EvalSamplingEveryNth"
)


class EvalSamplingDeterministicByHash(TypedDict):
    """Deterministic 1-in-N selection by hashing a stable key path."""

    bucket: int
    key_path: JsonPath
    kind: Literal["deterministic_by_hash"]
    modulus: int


class EvalSamplingEveryNth(TypedDict):
    """Every Nth record."""

    kind: Literal["every_nth"]
    n: int


class EvalSamplingRatio(TypedDict):
    """Probabilistic selection."""

    kind: Literal["ratio"]
    ratio: float


class _EvalSpecRequired(TypedDict):
    """Required keys of `EvalSpec`."""

    tasks: dict[str, EvalTask]


class EvalSpec(_EvalSpecRequired, total=False):
    """The typed spec body of an `eval` Verifier implementation.

    This struct does not carry a discriminator; the enclosing `VerifierImplementation` union supplies the `implementation.kind: eval` and `implementation.spec: { ... }` wire shape on a `Verifier` Card.

    Authors declare: - `dataset` — source data, typically a `Data` card with eval scenarios. - `tasks` — the rubric DAG. - `workflow` — optional declared workflow shape. - `sampling` — optional production sampling policy. - `pass_gate` — optional workflow-level pass criterion. - `context_capture` — durable storage policy for `AssertionResult::actual`.

    This struct does not carry envelope identity, tenant partitioning, triggers, or alert dispatch. Alert wiring is deferred until the drift primitives and secret reference model are locked.
    """

    context_capture: EvalContextCapture | None
    dataset: Ref | None
    pass_gate: EvalPassGate | None
    sampling: EvalSampling | None
    workflow: Workflow | None


# One task in an `EvalSpec` DAG. Adjacently-tagged on the wire by `"kind"`; the inner record fields live alongside.
EvalTask: TypeAlias = (
    "EvalTaskAssertion | EvalTaskLlmJudge | EvalTaskTraceAssertion | EvalTaskAgentAssertion"
)


class _EvalTaskAgentAssertionRequired(TypedDict):
    """Required keys of `EvalTaskAgentAssertion`."""

    expected: JsonValue
    id: TaskId
    kind: Literal["agent_assertion"]
    operator: ComparisonOperator
    workflow_field_path: JsonPath


class EvalTaskAgentAssertion(_EvalTaskAgentAssertionRequired, total=False):
    """Assertion over the assembled GenAI workflow envelope."""

    condition: EvalCondition | None
    depends_on: list[TaskId]


class _EvalTaskAssertionRequired(TypedDict):
    """Required keys of `EvalTaskAssertion`."""

    expected: JsonValue
    id: TaskId
    kind: Literal["assertion"]
    operator: ComparisonOperator


class EvalTaskAssertion(_EvalTaskAssertionRequired, total=False):
    """Programmatic assertion against the workflow context."""

    condition: EvalCondition | None
    context_path: JsonPath | None
    depends_on: list[TaskId]
    item_context_path: JsonPath | None


class _EvalTaskLlmJudgeRequired(TypedDict):
    """Required keys of `EvalTaskLlmJudge`."""

    expected: JsonValue
    id: TaskId
    judge_ref: InlineableRef_for_AgentSpec
    kind: Literal["llm_judge"]
    operator: ComparisonOperator


class EvalTaskLlmJudge(_EvalTaskLlmJudgeRequired, total=False):
    """LLM-as-judge evaluation via a `Prompt` card."""

    condition: EvalCondition | None
    context_path: JsonPath | None
    depends_on: list[TaskId]
    max_retries: int


class _EvalTaskTraceAssertionRequired(TypedDict):
    """Required keys of `EvalTaskTraceAssertion`."""

    expected: JsonValue
    id: TaskId
    kind: Literal["trace_assertion"]
    operator: ComparisonOperator
    span_selector: JsonPath


class EvalTaskTraceAssertion(_EvalTaskTraceAssertionRequired, total=False):
    """Assertion over the assembled OTel trace document."""

    condition: EvalCondition | None
    depends_on: list[TaskId]


# Feature column name referenced by a drift Verifier signal.
FeatureName: TypeAlias = "str"


class _FieldSpecRequired(TypedDict):
    """Required keys of `FieldSpec`."""

    dtype: str
    name: ColumnName


class FieldSpec(_FieldSpecRequired, total=False):
    """Ordered field declaration used by Wyrd data schemas and model signatures."""

    extra: dict[str, str]
    nullable: bool
    shape: list[Dim]


class GoogleBatchEmbedRequest(TypedDict):
    """Generated Card schema type."""

    requests: list[GoogleEmbedRequest]


class GoogleCodeExecutionResult(TypedDict):
    """Generated Card schema type."""

    outcome: str
    output: str


class GoogleContent(TypedDict):
    """One Google content turn."""

    parts: list[GooglePart]
    role: str


class GoogleEmbedContent(TypedDict):
    """Generated Card schema type."""

    parts: list[GoogleEmbedPart]


class GoogleEmbedPart(TypedDict):
    """Generated Card schema type."""

    text: str


class _GoogleEmbedRequestRequired(TypedDict):
    """Required keys of `GoogleEmbedRequest`."""

    content: GoogleEmbedContent
    model: str


class GoogleEmbedRequest(_GoogleEmbedRequestRequired, total=False):
    """Generated Card schema type."""

    output_dimensionality: int | None
    task_type: str | None
    title: str | None


class GoogleExecutableCode(TypedDict):
    """Generated Card schema type."""

    code: str
    language: str


class GoogleFileData(TypedDict):
    """Generated Card schema type."""

    file_uri: str
    mime_type: str


class GoogleFunctionCall(TypedDict):
    """Function call the model requested.

    Decoding is deliberately permissive (no `deny_unknown_fields`): Gemini and Vertex add members such as call identifiers and thought signatures, which are ignored rather than failing the whole answer.
    """

    args: JsonValue
    name: str


class _GoogleFunctionCallingConfigRequired(TypedDict):
    """Required keys of `GoogleFunctionCallingConfig`."""

    mode: str


class GoogleFunctionCallingConfig(_GoogleFunctionCallingConfigRequired, total=False):
    """Generated Card schema type."""

    allowed_function_names: list[str] | None


class _GoogleFunctionDeclarationRequired(TypedDict):
    """Required keys of `GoogleFunctionDeclaration`."""

    name: str
    parameters: JsonValue


class GoogleFunctionDeclaration(_GoogleFunctionDeclarationRequired, total=False):
    """Generated Card schema type."""

    description: str | None


class GoogleFunctionResponse(TypedDict):
    """Generated Card schema type."""

    name: str
    response: JsonValue


class _GoogleGenerateContentRequestRequired(TypedDict):
    """Required keys of `GoogleGenerateContentRequest`."""

    contents: list[GoogleContent]


class GoogleGenerateContentRequest(_GoogleGenerateContentRequestRequired, total=False):
    """`POST /v1beta/models/{model}:generateContent`."""

    cached_content: str | None
    generation_config: GoogleGenerationConfig | None
    labels: dict[str, JsonValue] | None
    safety_settings: list[GoogleSafetySetting] | None
    system_instruction: GoogleContent | None
    tool_config: GoogleToolConfig | None
    tools: list[GoogleTool] | None


class GoogleGenerationConfig(TypedDict, total=False):
    """Generated Card schema type."""

    candidate_count: int | None
    frequency_penalty: float | None
    max_output_tokens: int | None
    presence_penalty: float | None
    response_mime_type: str | None
    response_modalities: list[str] | None
    response_schema: JsonValue
    seed: int | None
    speech_config: JsonValue
    stop_sequences: list[str] | None
    temperature: float | None
    thinking_config: GoogleThinkingConfig | None
    top_k: int | None
    top_p: float | None


class GoogleInlineData(TypedDict):
    """Generated Card schema type."""

    data: str
    mime_type: str


# One content part.
#
# Decoding is untagged and tries variants in declaration order, so `Thought` precedes `Text`: a part carrying both `thought` and `text` is reasoning, not visible text. Structured variants accept the snake_case names Skald emits and the camelCase names Gemini and Vertex return.
GooglePart: TypeAlias = "GooglePartVariant1 | GooglePartText | GooglePartInlineData | GooglePartFileData | GooglePartFunctionCall | GooglePartFunctionResponse | GooglePartExecutableCode | GooglePartCodeExecutionResult"


class GooglePartCodeExecutionResult(TypedDict):
    """Result of executing generated code."""

    code_execution_result: GoogleCodeExecutionResult


class GooglePartExecutableCode(TypedDict):
    """Code the model generated for execution."""

    executable_code: GoogleExecutableCode


class GooglePartFileData(TypedDict):
    """Media referenced by URI."""

    file_data: GoogleFileData


class GooglePartFunctionCall(TypedDict):
    """Function call the model requested."""

    function_call: GoogleFunctionCall


class GooglePartFunctionResponse(TypedDict):
    """Function result returned to the model."""

    function_response: GoogleFunctionResponse


class GooglePartInlineData(TypedDict):
    """Inline base64 media."""

    inline_data: GoogleInlineData


class GooglePartText(TypedDict):
    """Visible text."""

    text: str


class GooglePartVariant1(TypedDict):
    """Model reasoning text."""

    text: str
    thought: bool


class GoogleSafetySetting(TypedDict):
    """Generated Card schema type."""

    category: str
    threshold: str


class GoogleThinkingConfig(TypedDict, total=False):
    """Generated Card schema type."""

    include_thoughts: bool | None
    thinking_budget: int | None


class GoogleTool(TypedDict, total=False):
    """Generated Card schema type."""

    code_execution: JsonValue
    function_declarations: list[GoogleFunctionDeclaration] | None
    google_search: JsonValue
    google_search_retrieval: JsonValue
    url_context: JsonValue


class GoogleToolConfig(TypedDict):
    """Generated Card schema type."""

    function_calling_config: GoogleFunctionCallingConfig


# Credential authority of an HTTP action, bound to a tenant `http` connection.
#
# The scheme and custom header name must equal the named connection's stored authority at registration and before every attempt.
HttpAuth: TypeAlias = "HttpAuthBearer | HttpAuthBasic | HttpAuthHeader"


class HttpAuthBasic(TypedDict):
    """`Authorization: Basic` from the connection's username and password."""

    connection: ConnectionName
    scheme: Literal["basic"]


class HttpAuthBearer(TypedDict):
    """`Authorization: Bearer` from the connection's token."""

    connection: ConnectionName
    scheme: Literal["bearer"]


class HttpAuthHeader(TypedDict):
    """A custom header carrying the connection's value."""

    connection: ConnectionName
    name: str
    scheme: Literal["header"]


# HTTP methods supported by an HTTP Operator action.
HttpMethod: TypeAlias = 'Literal["get", "post", "put", "patch", "delete"]'

# Hugging Face task identifier.
HuggingFaceTask: TypeAlias = 'Literal["TextClassification", "TokenClassification", "QuestionAnswering", "Summarization", "Translation", "TextGeneration", "FillMask", "ZeroShotClassification", "ImageClassification", "ObjectDetection", "ImageSegmentation", "ImageToText", "ImageToImage", "TextToImage", "DepthEstimation", "AudioClassification", "AutomaticSpeechRecognition", "AudioToAudio", "TextToSpeech", "TabularClassification", "TabularRegression", "FeatureExtraction", "SentenceSimilarity", "Conversational", "DocumentQuestionAnswering", "VisualQuestionAnswering", "TableQuestionAnswering", "Embedding", "MultipleChoice", "Other"]'


class _HuggingfaceMetaRequired(TypedDict):
    """Required keys of `HuggingfaceMeta`."""

    dataset_id: str


class HuggingfaceMeta(_HuggingfaceMetaRequired, total=False):
    """Hugging Face dataset interface metadata."""

    config: str | None
    revision: str | None
    split: str | None


class _HuggingfaceMeta2Required(TypedDict):
    """Required keys of `HuggingfaceMeta2`."""

    framework_version: str
    hf_task: HuggingFaceTask


class HuggingfaceMeta2(_HuggingfaceMeta2Required, total=False):
    """Config for the Huggingface model interface."""

    model_subtype: str | None
    repo_id: str | None
    revision: str | None


# Image format family accepted by DataCard image manifests.
ImageFormat: TypeAlias = 'Literal["Png", "Jpeg", "Webp", "Mixed"]'


class _ImageMetaRequired(TypedDict):
    """Required keys of `ImageMeta`."""

    color_mode: ColorMode
    format: ImageFormat


class ImageMeta(_ImageMetaRequired, total=False):
    """Image manifest interface metadata."""

    manifest_ref: Ref | None


# Predicate operator for a column split.
Inequality: TypeAlias = 'Literal["Eq", "Ne", "Gt", "Ge", "Lt", "Le", "In"]'

# A reference position that may carry an embedded child spec.
#
# Loaders rewrite `Path` values to `Sibling` values before submitting a request; the server rejects unresolved paths at the wire boundary. `Inline` bodies are authored, not synthesized by the loader.
InlineableRef_for_AgentSpec: TypeAlias = (
    "CardRef | InlineableRef_for_AgentSpecSibling | AgentSpec | str"
)


class InlineableRef_for_AgentSpecSibling(TypedDict):
    """A loader-projected reference to another submission in the same request."""

    sibling: CardRef


# A reference position that may carry an embedded child spec.
#
# Loaders rewrite `Path` values to `Sibling` values before submitting a request; the server rejects unresolved paths at the wire boundary. `Inline` bodies are authored, not synthesized by the loader.
InlineableRef_for_OperatorSpec: TypeAlias = (
    "CardRef | InlineableRef_for_OperatorSpecSibling | OperatorSpec | str"
)


class InlineableRef_for_OperatorSpecSibling(TypedDict):
    """A loader-projected reference to another submission in the same request."""

    sibling: CardRef


# A reference position that may carry an embedded child spec.
#
# Loaders rewrite `Path` values to `Sibling` values before submitting a request; the server rejects unresolved paths at the wire boundary. `Inline` bodies are authored, not synthesized by the loader.
InlineableRef_for_Prompt: TypeAlias = "CardRef | InlineableRef_for_PromptSibling | Prompt | str"


class InlineableRef_for_PromptSibling(TypedDict):
    """A loader-projected reference to another submission in the same request."""

    sibling: CardRef


# A reference position that may carry an embedded child spec.
#
# Loaders rewrite `Path` values to `Sibling` values before submitting a request; the server rejects unresolved paths at the wire boundary. `Inline` bodies are authored, not synthesized by the loader.
InlineableRef_for_TriggerSpec: TypeAlias = (
    "CardRef | InlineableRef_for_TriggerSpecSibling | TriggerSpec | str"
)


class InlineableRef_for_TriggerSpecSibling(TypedDict):
    """A loader-projected reference to another submission in the same request."""

    sibling: CardRef


JsonPath: TypeAlias = "str"

# JSON value-type set used by [`ComparisonOperator::IsType`].
JsonValueType: TypeAlias = 'Literal["null", "bool", "number", "string", "array", "object"]'

# JSONL compression choices accepted by DataCard.
JsonlCompression: TypeAlias = 'Literal["None", "Gzip", "Zstd"]'


class _JsonlMetaRequired(TypedDict):
    """Required keys of `JsonlMeta`."""

    compression: JsonlCompression


class JsonlMeta(_JsonlMetaRequired, total=False):
    """JSON Lines interface metadata."""

    lines_per_file: int | None


# Validated value for queryable Card and Run labels.
LabelValue: TypeAlias = "str"


class _LightgbmMetaRequired(TypedDict):
    """Required keys of `LightgbmMeta`."""

    framework_version: str


class LightgbmMeta(_LightgbmMetaRequired, total=False):
    """Config for the Lightgbm model interface."""

    model_subtype: str | None


class _LightningMetaRequired(TypedDict):
    """Required keys of `LightningMeta`."""

    framework_version: str


class LightningMeta(_LightningMetaRequired, total=False):
    """Config for the Lightning model interface."""

    model_subtype: str | None


class _MetadataRequired(TypedDict):
    """Required keys of `Metadata`."""

    name: CardName


class Metadata(_MetadataRequired, total=False):
    """Card metadata common to every kind.

    `version` and `bump` capture the author's declarative intent on the register path. The server resolves both to a concrete pin before the envelope is returned to the caller:

    - Pre-register: `version` may be `None` (server bumps absolute latest or seeds `0.1.0`), `Some(VersionSpec::Scope("1.0"))` (server bumps within the prefix line), or `Some(VersionSpec::Pin("1.4.2"))` (exact pin). `bump` selects the bump level applied on the auto-bump paths (defaults to `Patch` if unset). - Post-register: `version` is always `Some(VersionSpec::Pin(resolved))`; readers may use [`Metadata::resolved_pin`] to extract the [`VersionBlock`].
    """

    annotations: dict[str, AnnotationValue]
    artifact_hash: str | None
    bump: VersionBump | None
    labels: dict[str, LabelValue]
    origin: Origin | None
    space: SpaceName | None
    spec_hash: str | None
    uid: CardUid | None
    version: VersionSpec | None


# Framework interface tag for a Model spec.
ModelInterface: TypeAlias = "ModelInterfaceSklearn | ModelInterfaceXgboost | ModelInterfaceLightgbm | ModelInterfaceCatboost | ModelInterfaceTorch | ModelInterfaceLightning | ModelInterfaceTensorflow | ModelInterfaceHuggingface | ModelInterfaceCustom"


class ModelInterfaceCatboost(TypedDict):
    """CatBoost model persisted through the catboost loader."""

    kind: Literal["Catboost"]
    meta: CatboostMeta


class ModelInterfaceCustom(TypedDict):
    """User-supplied loader metadata."""

    kind: Literal["Custom"]
    meta: CustomMeta


class ModelInterfaceHuggingface(TypedDict):
    """Hugging Face model persisted through a local snapshot or pinned repo."""

    kind: Literal["Huggingface"]
    meta: HuggingfaceMeta2


class ModelInterfaceLightgbm(TypedDict):
    """LightGBM model persisted through the lightgbm loader."""

    kind: Literal["Lightgbm"]
    meta: LightgbmMeta


class ModelInterfaceLightning(TypedDict):
    """PyTorch Lightning module persisted as a trainer checkpoint."""

    kind: Literal["Lightning"]
    meta: LightningMeta


class ModelInterfaceSklearn(TypedDict):
    """scikit-learn estimator persisted through the sklearn loader."""

    kind: Literal["Sklearn"]
    meta: SklearnMeta


class ModelInterfaceTensorflow(TypedDict):
    """TensorFlow or Keras model persisted through the tensorflow loader."""

    kind: Literal["Tensorflow"]
    meta: TensorflowMeta


class ModelInterfaceTorch(TypedDict):
    """PyTorch module persisted through the torch loader."""

    kind: Literal["Torch"]
    meta: TorchMeta2


class ModelInterfaceXgboost(TypedDict):
    """XGBoost model persisted through the xgboost loader."""

    kind: Literal["Xgboost"]
    meta: XgboostMeta


class ModelSignature(TypedDict):
    """Typed input and output schema for a Model spec."""

    inputs: list[FieldSpec]
    outputs: list[FieldSpec]


class _ModelSpecRequired(TypedDict):
    """Required keys of `ModelSpec`."""

    interface: ModelInterface
    signature: ModelSignature
    task_type: TaskType


class ModelSpec(_ModelSpecRequired, total=False):
    """Body of a Model card.

    This pure contract describes which framework loads the model, which task it performs, which fields it consumes and produces, and which Artifact cards hold model-related bytes.
    """

    card_refs: list[Ref]
    sample_input: SampleInput | None


# Non-secret JSON-like configuration value.
NonSecretValue: TypeAlias = "NonSecretValueStr | NonSecretValueNumber | NonSecretValueBool | NonSecretValueList | NonSecretValueObject"


class NonSecretValueBool(TypedDict):
    """Boolean value."""

    type: Literal["bool"]
    value: bool


class NonSecretValueList(TypedDict):
    """List of non-secret values."""

    type: Literal["list"]
    value: list[NonSecretValue]


class NonSecretValueNumber(TypedDict):
    """Numeric value."""

    type: Literal["number"]
    value: float


class NonSecretValueObject(TypedDict):
    """Object of non-secret values."""

    type: Literal["object"]
    value: dict[str, NonSecretValue]


class NonSecretValueStr(TypedDict):
    """String value."""

    type: Literal["str"]
    value: str


# Typed notification destinations.
NotifyChannel: TypeAlias = "NotifyChannelPagerDuty | NotifyChannelSlack"


class _NotifyChannelPagerDutyRequired(TypedDict):
    """Required keys of `NotifyChannelPagerDuty`."""

    connection: ConnectionName
    kind: Literal["pager_duty"]
    route: str
    severity: PagerDutySeverity
    summary: str


class NotifyChannelPagerDuty(_NotifyChannelPagerDutyRequired, total=False):
    """PagerDuty Events API v2 trigger through a tenant Global Integration key."""

    dedup_key: str | None


class NotifyChannelSlack(TypedDict):
    """Slack `chat.postMessage` through a tenant workspace bot token."""

    channel_id: str
    connection: ConnectionName
    kind: Literal["slack"]
    text: str


# NumPy serialization formats accepted by DataCard.
NumpyFormat: TypeAlias = 'Literal["Npy", "Npz"]'


class _NumpyMetaRequired(TypedDict):
    """Required keys of `NumpyMeta`."""

    dtype: str
    format: NumpyFormat


class NumpyMeta(_NumpyMetaRequired, total=False):
    """NumPy interface metadata."""

    shape: list[int]


class OpenAiAllowedTools(TypedDict):
    """Generated Card schema type."""

    mode: OpenAiAllowedToolsMode
    tools: list[dict[str, JsonValue]]


class OpenAiAllowedToolsChoice(TypedDict):
    """Generated Card schema type."""

    allowed_tools: OpenAiAllowedTools
    type: OpenAiAllowedToolsKind


OpenAiAllowedToolsKind: TypeAlias = 'Literal["allowed_tools"]'

OpenAiAllowedToolsMode: TypeAlias = 'Literal["auto", "required"]'

OpenAiAudioFormat: TypeAlias = 'Literal["wav", "aac", "mp3", "flac", "opus", "pcm16"]'

OpenAiBuiltInVoice: TypeAlias = 'Literal["alloy", "ash", "ballad", "coral", "echo", "fable", "nova", "onyx", "sage", "shimmer", "marin", "cedar"]'


class OpenAiChatAudio(TypedDict):
    """Generated Card schema type."""

    format: OpenAiAudioFormat
    voice: OpenAiVoice


class _OpenAiChatMessageRequired(TypedDict):
    """Required keys of `OpenAiChatMessage`."""

    role: str


class OpenAiChatMessage(_OpenAiChatMessageRequired, total=False):
    """One chat message on the wire."""

    annotations: list[OpenAiMessageAnnotation]
    audio: OpenAiMessageAudio | None
    content: OpenAiMessageContent | None
    name: str | None
    refusal: str | None
    tool_call_id: str | None
    tool_calls: list[OpenAiToolCall] | None


class _OpenAiChatRequestRequired(TypedDict):
    """Required keys of `OpenAiChatRequest`."""

    messages: list[OpenAiChatMessage]
    model: str


class OpenAiChatRequest(_OpenAiChatRequestRequired, total=False):
    """`POST /v1/chat/completions`."""

    audio: OpenAiChatAudio | None
    frequency_penalty: float | None
    logit_bias: dict[str, JsonValue] | None
    logprobs: bool | None
    max_completion_tokens: int | None
    max_tokens: int | None
    metadata: dict[str, JsonValue] | None
    modalities: list[OpenAiResponseModality] | None
    n: int | None
    parallel_tool_calls: bool | None
    prediction: OpenAiPredictionContent | None
    presence_penalty: float | None
    prompt_cache_key: str | None
    reasoning_effort: OpenAiReasoningEffort | None
    response_format: OpenAiResponseFormat | None
    safety_identifier: str | None
    seed: int | None
    service_tier: str | None
    stop: OpenAiStop | None
    store: bool | None
    stream: bool | None
    stream_options: OpenAiStreamOptions | None
    temperature: float | None
    tool_choice: OpenAiChatToolChoice | None
    tools: list[OpenAiTool] | None
    top_logprobs: int | None
    top_p: float | None
    user: str | None


OpenAiChatToolChoice: TypeAlias = "OpenAiToolChoiceMode | OpenAiAllowedToolsChoice | OpenAiNamedFunctionToolChoice | OpenAiNamedCustomToolChoice"

OpenAiContentPart: TypeAlias = "OpenAiContentPartText | OpenAiContentPartImageUrl | OpenAiContentPartInputAudio | OpenAiContentPartFile"


class OpenAiContentPartFile(TypedDict):
    """Generated Card schema type."""

    file: OpenAiFilePart
    type: Literal["file"]


class OpenAiContentPartImageUrl(TypedDict):
    """Generated Card schema type."""

    image_url: OpenAiImageUrl
    type: Literal["image_url"]


class OpenAiContentPartInputAudio(TypedDict):
    """Generated Card schema type."""

    input_audio: OpenAiInputAudio
    type: Literal["input_audio"]


class OpenAiContentPartText(TypedDict):
    """Generated Card schema type."""

    text: str
    type: Literal["text"]


class OpenAiCustomChoice(TypedDict):
    """Generated Card schema type."""

    name: str


class _OpenAiCustomToolRequired(TypedDict):
    """Required keys of `OpenAiCustomTool`."""

    name: str


class OpenAiCustomTool(_OpenAiCustomToolRequired, total=False):
    """Generated Card schema type."""

    description: str | None
    format: OpenAiCustomToolFormat | None


OpenAiCustomToolFormat: TypeAlias = "OpenAiCustomToolFormatText | OpenAiCustomToolFormatGrammar"


class OpenAiCustomToolFormatGrammar(TypedDict):
    """Generated Card schema type."""

    grammar: OpenAiGrammar
    type: Literal["grammar"]


class OpenAiCustomToolFormatText(TypedDict):
    """Generated Card schema type."""

    type: Literal["text"]


class OpenAiCustomVoice(TypedDict):
    """Generated Card schema type."""

    id: str


OpenAiEmbeddingsInput: TypeAlias = "str | list[str] | list[int] | list[list[int]]"


class _OpenAiEmbeddingsRequestRequired(TypedDict):
    """Required keys of `OpenAiEmbeddingsRequest`."""

    input: OpenAiEmbeddingsInput
    model: str


class OpenAiEmbeddingsRequest(_OpenAiEmbeddingsRequestRequired, total=False):
    """Generated Card schema type."""

    dimensions: int | None
    encoding_format: str | None
    user: str | None


class OpenAiFilePart(TypedDict, total=False):
    """Generated Card schema type."""

    file_data: str | None
    file_id: str | None
    filename: str | None


class _OpenAiFunctionRequired(TypedDict):
    """Required keys of `OpenAiFunction`."""

    name: str


class OpenAiFunction(_OpenAiFunctionRequired, total=False):
    """Generated Card schema type."""

    description: str | None
    parameters: dict[str, JsonValue] | None
    strict: bool | None


class OpenAiFunctionChoice(TypedDict):
    """Generated Card schema type."""

    name: str


class OpenAiGrammar(TypedDict):
    """Generated Card schema type."""

    definition: str
    syntax: OpenAiGrammarSyntax


OpenAiGrammarSyntax: TypeAlias = 'Literal["lark", "regex"]'


class _OpenAiImageUrlRequired(TypedDict):
    """Required keys of `OpenAiImageUrl`."""

    url: str


class OpenAiImageUrl(_OpenAiImageUrlRequired, total=False):
    """Generated Card schema type."""

    detail: str | None


class OpenAiInputAudio(TypedDict):
    """Generated Card schema type."""

    data: str
    format: str


class _OpenAiJsonSchemaRequired(TypedDict):
    """Required keys of `OpenAiJsonSchema`."""

    name: str


class OpenAiJsonSchema(_OpenAiJsonSchemaRequired, total=False):
    """Generated Card schema type."""

    description: str | None
    schema: dict[str, JsonValue] | None
    strict: bool | None


class OpenAiMessageAnnotation(TypedDict):
    """A URL citation annotation returned by web search."""

    type: str
    url_citation: OpenAiUrlCitation


class OpenAiMessageAudio(TypedDict):
    """Audio output returned by the model."""

    data: str
    expires_at: int
    id: str
    transcript: str


OpenAiMessageContent: TypeAlias = "str | list[OpenAiContentPart]"


class OpenAiNamedCustomToolChoice(TypedDict):
    """Generated Card schema type."""

    custom: OpenAiCustomChoice
    type: OpenAiNamedCustomToolChoiceKind


OpenAiNamedCustomToolChoiceKind: TypeAlias = 'Literal["custom"]'


class OpenAiNamedFunctionToolChoice(TypedDict):
    """Generated Card schema type."""

    function: OpenAiFunctionChoice
    type: OpenAiNamedFunctionToolChoiceKind


OpenAiNamedFunctionToolChoiceKind: TypeAlias = 'Literal["function"]'


class OpenAiPredictionContent(TypedDict):
    """Generated Card schema type."""

    content: OpenAiPredictionPayload
    type: OpenAiPredictionKind


OpenAiPredictionContentPart: TypeAlias = "OpenAiPredictionContentPartText"


class OpenAiPredictionContentPartText(TypedDict):
    """Generated Card schema type."""

    text: str
    type: Literal["text"]


OpenAiPredictionKind: TypeAlias = 'Literal["content"]'

OpenAiPredictionPayload: TypeAlias = "str | list[OpenAiPredictionContentPart]"


class OpenAiReasoning(TypedDict, total=False):
    """Generated Card schema type."""

    effort: OpenAiReasoningEffort2 | None
    generate_summary: OpenAiReasoningSummary | None
    summary: OpenAiReasoningSummary | None


OpenAiReasoningEffort: TypeAlias = 'Literal["none", "minimal", "low", "medium", "high", "xhigh"]'

OpenAiReasoningEffort2: TypeAlias = 'Literal["none", "minimal", "low", "medium", "high", "xhigh"]'

OpenAiReasoningSummary: TypeAlias = 'Literal["auto", "concise", "detailed"]'

# One part of a Responses reasoning item summary.
OpenAiReasoningSummaryPart: TypeAlias = "OpenAiReasoningSummaryPartSummaryText"


class OpenAiReasoningSummaryPartSummaryText(TypedDict):
    """Summary text."""

    text: str
    type: Literal["summary_text"]


OpenAiResponseContentPart: TypeAlias = "OpenAiResponseContentPartInputText | OpenAiResponseContentPartOutputText | OpenAiResponseContentPartInputImage | OpenAiResponseContentPartInputFile"


class OpenAiResponseContentPartInputFile(TypedDict):
    """Generated Card schema type."""

    file_id: str
    type: Literal["input_file"]


class _OpenAiResponseContentPartInputImageRequired(TypedDict):
    """Required keys of `OpenAiResponseContentPartInputImage`."""

    image_url: str
    type: Literal["input_image"]


class OpenAiResponseContentPartInputImage(
    _OpenAiResponseContentPartInputImageRequired, total=False
):
    """Generated Card schema type."""

    detail: str | None


class OpenAiResponseContentPartInputText(TypedDict):
    """Generated Card schema type."""

    text: str
    type: Literal["input_text"]


class OpenAiResponseContentPartOutputText(TypedDict):
    """Generated Card schema type."""

    text: str
    type: Literal["output_text"]


OpenAiResponseFormat: TypeAlias = (
    "OpenAiResponseFormatText | OpenAiResponseFormatJsonObject | OpenAiResponseFormatJsonSchema"
)


class OpenAiResponseFormatJsonObject(TypedDict):
    """Generated Card schema type."""

    type: Literal["json_object"]


class OpenAiResponseFormatJsonSchema(TypedDict):
    """Generated Card schema type."""

    json_schema: OpenAiJsonSchema
    type: Literal["json_schema"]


class OpenAiResponseFormatText(TypedDict):
    """Generated Card schema type."""

    type: Literal["text"]


OpenAiResponseItem: TypeAlias = "OpenAiResponseItemMessage | OpenAiResponseItemFunctionCall | OpenAiResponseItemFunctionCallOutput | OpenAiResponseItemReasoning | OpenAiResponseItemInputFile | OpenAiResponseItemInputImage"


class OpenAiResponseItemFunctionCall(TypedDict):
    """Generated Card schema type."""

    arguments: str
    call_id: str
    name: str
    type: Literal["function_call"]


class OpenAiResponseItemFunctionCallOutput(TypedDict):
    """Generated Card schema type."""

    call_id: str
    output: str
    type: Literal["function_call_output"]


class OpenAiResponseItemInputFile(TypedDict):
    """Generated Card schema type."""

    file_id: str
    type: Literal["input_file"]


class _OpenAiResponseItemInputImageRequired(TypedDict):
    """Required keys of `OpenAiResponseItemInputImage`."""

    image_url: str
    type: Literal["input_image"]


class OpenAiResponseItemInputImage(_OpenAiResponseItemInputImageRequired, total=False):
    """Generated Card schema type."""

    detail: str | None


class OpenAiResponseItemMessage(TypedDict):
    """Generated Card schema type."""

    content: list[OpenAiResponseContentPart]
    role: str
    type: Literal["message"]


class _OpenAiResponseItemReasoningRequired(TypedDict):
    """Required keys of `OpenAiResponseItemReasoning`."""

    type: Literal["reasoning"]


class OpenAiResponseItemReasoning(_OpenAiResponseItemReasoningRequired, total=False):
    """Generated Card schema type."""

    encrypted_content: str | None
    id: str | None
    summary: list[OpenAiReasoningSummaryPart]


OpenAiResponseModality: TypeAlias = 'Literal["text", "audio"]'


class OpenAiResponsesAllowedToolsChoice(TypedDict):
    """Generated Card schema type."""

    mode: OpenAiResponsesAllowedToolsMode
    tools: list[dict[str, JsonValue]]
    type: OpenAiResponsesAllowedToolsKind


OpenAiResponsesAllowedToolsKind: TypeAlias = 'Literal["allowed_tools"]'

OpenAiResponsesAllowedToolsMode: TypeAlias = 'Literal["auto", "required"]'


class OpenAiResponsesApplyPatchToolChoice(TypedDict):
    """Generated Card schema type."""

    type: OpenAiResponsesApplyPatchToolKind


OpenAiResponsesApplyPatchToolKind: TypeAlias = 'Literal["apply_patch"]'


class OpenAiResponsesCustomToolChoice(TypedDict):
    """Generated Card schema type."""

    name: str
    type: OpenAiResponsesCustomToolKind


OpenAiResponsesCustomToolFormat: TypeAlias = (
    "OpenAiResponsesCustomToolFormatText | OpenAiResponsesCustomToolFormatGrammar"
)


class OpenAiResponsesCustomToolFormatGrammar(TypedDict):
    """Generated Card schema type."""

    grammar: OpenAiResponsesGrammar
    type: Literal["grammar"]


class OpenAiResponsesCustomToolFormatText(TypedDict):
    """Generated Card schema type."""

    type: Literal["text"]


OpenAiResponsesCustomToolKind: TypeAlias = 'Literal["custom"]'


class OpenAiResponsesFunctionToolChoice(TypedDict):
    """Generated Card schema type."""

    name: str
    type: OpenAiResponsesFunctionToolKind


OpenAiResponsesFunctionToolKind: TypeAlias = 'Literal["function"]'


class OpenAiResponsesGrammar(TypedDict):
    """Generated Card schema type."""

    definition: str
    syntax: OpenAiResponsesGrammarSyntax


OpenAiResponsesGrammarSyntax: TypeAlias = 'Literal["lark", "regex"]'


class OpenAiResponsesHostedToolChoice(TypedDict):
    """Generated Card schema type."""

    type: OpenAiResponsesHostedToolKind


OpenAiResponsesHostedToolKind: TypeAlias = 'Literal["file_search", "web_search_preview", "computer", "computer_use_preview", "computer_use", "web_search_preview_2025_03_11", "image_generation", "code_interpreter"]'

# OpenAI Responses `input`: the text shorthand for one user message, or an ordered list of input items.
#
# Both forms decode and re-encode unchanged, so a relayed request keeps the form its caller sent. Editing the conversation first expands the text shorthand into the single user message it stands for.
OpenAiResponsesInput: TypeAlias = "str | list[OpenAiResponseItem]"


class _OpenAiResponsesMcpToolChoiceRequired(TypedDict):
    """Required keys of `OpenAiResponsesMcpToolChoice`."""

    server_label: str
    type: OpenAiResponsesMcpToolKind


class OpenAiResponsesMcpToolChoice(_OpenAiResponsesMcpToolChoiceRequired, total=False):
    """Generated Card schema type."""

    name: str | None


OpenAiResponsesMcpToolKind: TypeAlias = 'Literal["mcp"]'


class _OpenAiResponsesRequestRequired(TypedDict):
    """Required keys of `OpenAiResponsesRequest`."""

    input: OpenAiResponsesInput
    model: str


class OpenAiResponsesRequest(_OpenAiResponsesRequestRequired, total=False):
    """`OpenAI` Responses API request body carried by a prompt or gateway call.

    `input` keeps the form the author or caller sent, either text shorthand or an item list, so the request serializes back without reshaping.
    """

    include: list[str] | None
    instructions: str | None
    max_output_tokens: int | None
    metadata: dict[str, JsonValue] | None
    parallel_tool_calls: bool | None
    previous_response_id: str | None
    reasoning: OpenAiReasoning | None
    store: bool | None
    stream: bool | None
    temperature: float | None
    text: OpenAiResponsesText | None
    tool_choice: OpenAiResponsesToolChoice | None
    tools: list[OpenAiResponsesTool] | None
    top_p: float | None


class OpenAiResponsesShellToolChoice(TypedDict):
    """Generated Card schema type."""

    type: OpenAiResponsesShellToolKind


OpenAiResponsesShellToolKind: TypeAlias = 'Literal["shell"]'


class OpenAiResponsesText(TypedDict, total=False):
    """Generated Card schema type."""

    format: OpenAiTextResponseFormat | None


OpenAiResponsesTool: TypeAlias = "OpenAiResponsesToolFunction | OpenAiResponsesToolWebSearchPreview | OpenAiResponsesToolFileSearch | OpenAiResponsesToolCodeInterpreter | OpenAiResponsesToolImageGeneration | OpenAiResponsesToolMcp | OpenAiResponsesToolCustom"

OpenAiResponsesToolChoice: TypeAlias = "OpenAiResponsesToolChoiceMode | OpenAiResponsesAllowedToolsChoice | OpenAiResponsesHostedToolChoice | OpenAiResponsesFunctionToolChoice | OpenAiResponsesMcpToolChoice | OpenAiResponsesCustomToolChoice | OpenAiResponsesApplyPatchToolChoice | OpenAiResponsesShellToolChoice"

OpenAiResponsesToolChoiceMode: TypeAlias = 'Literal["none", "auto", "required"]'


class OpenAiResponsesToolCodeInterpreter(TypedDict):
    """Generated Card schema type."""

    type: Literal["code_interpreter"]


class _OpenAiResponsesToolCustomRequired(TypedDict):
    """Required keys of `OpenAiResponsesToolCustom`."""

    name: str
    type: Literal["custom"]


class OpenAiResponsesToolCustom(_OpenAiResponsesToolCustomRequired, total=False):
    """Generated Card schema type."""

    description: str | None
    format: OpenAiResponsesCustomToolFormat | None


class OpenAiResponsesToolFileSearch(TypedDict):
    """Generated Card schema type."""

    type: Literal["file_search"]
    vector_store_ids: list[str]


class _OpenAiResponsesToolFunctionRequired(TypedDict):
    """Required keys of `OpenAiResponsesToolFunction`."""

    name: str
    type: Literal["function"]


class OpenAiResponsesToolFunction(_OpenAiResponsesToolFunctionRequired, total=False):
    """Generated Card schema type."""

    description: str | None
    parameters: dict[str, JsonValue] | None
    strict: bool | None


class OpenAiResponsesToolImageGeneration(TypedDict):
    """Generated Card schema type."""

    type: Literal["image_generation"]


class _OpenAiResponsesToolMcpRequired(TypedDict):
    """Required keys of `OpenAiResponsesToolMcp`."""

    server_label: str
    server_url: str
    type: Literal["mcp"]


class OpenAiResponsesToolMcp(_OpenAiResponsesToolMcpRequired, total=False):
    """Generated Card schema type."""

    allowed_tools: list[str] | None


class OpenAiResponsesToolWebSearchPreview(TypedDict):
    """Generated Card schema type."""

    type: Literal["web_search_preview"]


OpenAiStop: TypeAlias = "str | list[str]"


class OpenAiStreamOptions(TypedDict, total=False):
    """Generated Card schema type."""

    include_obfuscation: bool | None
    include_usage: bool | None


OpenAiTextResponseFormat: TypeAlias = "OpenAiTextResponseFormatText | OpenAiTextResponseFormatJsonObject | OpenAiTextResponseFormatJsonSchema"


class OpenAiTextResponseFormatJsonObject(TypedDict):
    """Generated Card schema type."""

    type: Literal["json_object"]


class _OpenAiTextResponseFormatJsonSchemaRequired(TypedDict):
    """Required keys of `OpenAiTextResponseFormatJsonSchema`."""

    name: str
    type: Literal["json_schema"]


class OpenAiTextResponseFormatJsonSchema(_OpenAiTextResponseFormatJsonSchemaRequired, total=False):
    """Generated Card schema type."""

    description: str | None
    schema: dict[str, JsonValue] | None
    strict: bool | None


class OpenAiTextResponseFormatText(TypedDict):
    """Generated Card schema type."""

    type: Literal["text"]


OpenAiTool: TypeAlias = "OpenAiToolFunction | OpenAiToolCustom"


class OpenAiToolCall(TypedDict):
    """Generated Card schema type."""

    function: OpenAiToolFunctionCall
    id: str
    type: str


OpenAiToolChoiceMode: TypeAlias = 'Literal["none", "auto", "required"]'


class OpenAiToolCustom(TypedDict):
    """Generated Card schema type."""

    custom: OpenAiCustomTool
    type: Literal["custom"]


class OpenAiToolFunction(TypedDict):
    """Generated Card schema type."""

    function: OpenAiFunction
    type: Literal["function"]


class OpenAiToolFunctionCall(TypedDict):
    """Generated Card schema type."""

    arguments: str
    name: str


class OpenAiUrlCitation(TypedDict):
    """Citation metadata for a web search result."""

    end_index: int
    start_index: int
    title: str
    url: str


OpenAiVoice: TypeAlias = "OpenAiBuiltInVoice | OpenAiCustomVoice"


class OperatorBudget(TypedDict, total=False):
    """Operator execution limits."""

    max_tool_calls: int | None
    max_wall_seconds: int | None


# A server-owned side-effect template.
OperatorSpec: TypeAlias = "OperatorSpecWorkflow | OperatorSpecNotify | OperatorSpecHttp"


class _OperatorSpecHttpRequired(TypedDict):
    """Required keys of `OperatorSpecHttp`."""

    kind: Literal["http"]
    method: HttpMethod
    url: str


class OperatorSpecHttp(_OperatorSpecHttpRequired, total=False):
    """Perform an HTTP request."""

    auth: HttpAuth | None
    body: JsonValue
    budget: OperatorBudget | None
    description: str | None
    expect_status: int | None
    headers: dict[str, str]
    timeout_seconds: int | None


class _OperatorSpecNotifyRequired(TypedDict):
    """Required keys of `OperatorSpecNotify`."""

    channel: NotifyChannel
    kind: Literal["notify"]


class OperatorSpecNotify(_OperatorSpecNotifyRequired, total=False):
    """Send a typed notification."""

    budget: OperatorBudget | None
    description: str | None


class _OperatorSpecWorkflowRequired(TypedDict):
    """Required keys of `OperatorSpecWorkflow`."""

    kind: Literal["workflow"]
    workflow_ref: Ref


class OperatorSpecWorkflow(_OperatorSpecWorkflowRequired, total=False):
    """Dispatch a registered Workflow."""

    budget: OperatorBudget | None
    description: str | None


class _OriginRequired(TypedDict):
    """Required keys of `Origin`."""

    commit: CommitSha
    repo: str


class Origin(_OriginRequired, total=False):
    """Code-origin provenance for a card: the repository commit it was declared from, plus the in-repo path for monorepo disambiguation."""

    dirty: bool
    path: str | None


# PagerDuty Events API v2 severities.
PagerDutySeverity: TypeAlias = 'Literal["critical", "error", "warning", "info"]'


class _PandasMetaRequired(TypedDict):
    """Required keys of `PandasMeta`."""

    framework_version: str


class PandasMeta(_PandasMetaRequired, total=False):
    """Pandas interface metadata."""

    compression: ParquetCompression


ParameterizedComparisonOperator: TypeAlias = "ParameterizedComparisonOperatorInRange | ParameterizedComparisonOperatorNotInRange | ParameterizedComparisonOperatorApproximatelyEquals | ParameterizedComparisonOperatorMatchesRegex | ParameterizedComparisonOperatorNotMatchesRegex | ParameterizedComparisonOperatorHasMinLength | ParameterizedComparisonOperatorHasMaxLength | ParameterizedComparisonOperatorLength | ParameterizedComparisonOperatorLengthGreaterThan | ParameterizedComparisonOperatorLengthLessThan | ParameterizedComparisonOperatorIsType | ParameterizedComparisonOperatorWithinAbsTolerance | ParameterizedComparisonOperatorWithinPctTolerance | ParameterizedComparisonOperatorWithinStdDev | ParameterizedComparisonOperatorBetweenPercentiles | ParameterizedComparisonOperatorDivergenceLessThan | ParameterizedComparisonOperatorCosineSimilarityAtLeast"


class ParameterizedComparisonOperatorApproximatelyEquals(TypedDict):
    """Generated Card schema type."""

    kind: Literal["approximately_equals"]
    tolerance: float


class ParameterizedComparisonOperatorBetweenPercentiles(TypedDict):
    """Generated Card schema type."""

    kind: Literal["between_percentiles"]
    lower_pct: float
    upper_pct: float


class ParameterizedComparisonOperatorCosineSimilarityAtLeast(TypedDict):
    """Generated Card schema type."""

    kind: Literal["cosine_similarity_at_least"]
    threshold: float


class ParameterizedComparisonOperatorDivergenceLessThan(TypedDict):
    """Generated Card schema type."""

    kind: Literal["divergence_less_than"]
    metric: DivergenceMetric
    threshold: float


class ParameterizedComparisonOperatorHasMaxLength(TypedDict):
    """Generated Card schema type."""

    kind: Literal["has_max_length"]
    max: int


class ParameterizedComparisonOperatorHasMinLength(TypedDict):
    """Generated Card schema type."""

    kind: Literal["has_min_length"]
    min: int


class ParameterizedComparisonOperatorInRange(TypedDict):
    """Generated Card schema type."""

    inclusive: bool
    kind: Literal["in_range"]
    max: float
    min: float


class ParameterizedComparisonOperatorIsType(TypedDict):
    """Generated Card schema type."""

    expected: JsonValueType
    kind: Literal["is_type"]


class ParameterizedComparisonOperatorLength(TypedDict):
    """Generated Card schema type."""

    expected: int
    kind: Literal["length"]


class ParameterizedComparisonOperatorLengthGreaterThan(TypedDict):
    """Generated Card schema type."""

    kind: Literal["length_greater_than"]
    min: int


class ParameterizedComparisonOperatorLengthLessThan(TypedDict):
    """Generated Card schema type."""

    kind: Literal["length_less_than"]
    max: int


class ParameterizedComparisonOperatorMatchesRegex(TypedDict):
    """Generated Card schema type."""

    kind: Literal["matches_regex"]
    pattern: str


class ParameterizedComparisonOperatorNotInRange(TypedDict):
    """Generated Card schema type."""

    inclusive: bool
    kind: Literal["not_in_range"]
    max: float
    min: float


class ParameterizedComparisonOperatorNotMatchesRegex(TypedDict):
    """Generated Card schema type."""

    kind: Literal["not_matches_regex"]
    pattern: str


class ParameterizedComparisonOperatorWithinAbsTolerance(TypedDict):
    """Generated Card schema type."""

    kind: Literal["within_abs_tolerance"]
    tolerance: float


class ParameterizedComparisonOperatorWithinPctTolerance(TypedDict):
    """Generated Card schema type."""

    kind: Literal["within_pct_tolerance"]
    pct: float


class ParameterizedComparisonOperatorWithinStdDev(TypedDict):
    """Generated Card schema type."""

    kind: Literal["within_std_dev"]
    mean: float
    sigma: float
    std_dev: float


ParameterlessComparisonOperatorSchema: TypeAlias = 'Literal["equals", "not_equals", "greater_than", "greater_than_or_equals", "less_than", "less_than_or_equals", "is_positive", "is_negative", "is_zero", "contains", "not_contains", "contains_ignore_case", "starts_with", "ends_with", "is_email", "is_url", "is_uuid", "is_ipv4", "is_ipv6", "is_json", "in", "not_in", "is_subset", "is_superset", "is_disjoint", "all_of", "any_of", "none_of", "is_empty", "is_non_empty", "unique_values", "is_truthy", "is_falsy", "is_null", "is_not_null", "is_string", "is_number", "is_boolean", "is_object"]'

# Parquet compression choices accepted by the DataCard contract.
ParquetCompression: TypeAlias = 'Literal["None", "Snappy", "Gzip", "Zstd", "Lz4"]'


class ParquetMeta(TypedDict, total=False):
    """Parquet interface metadata."""

    compression: ParquetCompression
    row_group_size: int | None


class _PolarsMetaRequired(TypedDict):
    """Required keys of `PolarsMeta`."""

    framework_version: str


class PolarsMeta(_PolarsMetaRequired, total=False):
    """Polars interface metadata."""

    compression: ParquetCompression


class _PromptRequired(TypedDict):
    """Required keys of `Prompt`."""

    model: str
    request: ProviderRequest


class Prompt(_PromptRequired, total=False):
    """Authored native prompt request plus render metadata."""

    media_variables: list[str]
    provider: ProviderName | None
    response_type: ResponseType
    variables: list[str]
    version: str | None


class _PromptSpecRequired(TypedDict):
    """Required keys of `PromptSpec`."""

    model: str
    request: ProviderRequest


class PromptSpec(_PromptSpecRequired, total=False):
    """PromptCard spec body wrapping the native Skald prompt.

    Serializes with the `prompt` fields flattened directly into the spec body (no `prompt:` nesting key on the wire). Accepts two input forms:

    - **Declarative** (`provider` present, `request` absent): a `PromptDraft` that is compiled into the native provider request. - **Native** (`request` present): the stored native `Prompt` shape, as produced by `save()`.
    """

    media_variables: list[str]
    provider: ProviderName | None
    response_type: ResponseType
    variables: list[str]
    version: str | None


# Which provider a request targets.
ProviderName: TypeAlias = 'Literal["open_ai", "anthropic", "google", "vertex"] | ProviderNameCustom'


class ProviderNameCustom(TypedDict):
    """Provider not modeled by skald-spec."""

    custom: str


# One native LLM request, tagged with the provider dialect its body speaks.
#
# Serialized as `{"provider": "<variant>", "body": <native provider JSON>}`. The tag selects the variant, so a body that does not match its named dialect fails to deserialize. The tag names a wire schema, not a destination: one schema served by several providers is one variant.
ProviderRequest: TypeAlias = "ProviderRequestOpenAiChatCompletion | ProviderRequestOpenAiResponses | ProviderRequestOpenAiEmbeddings | ProviderRequestAnthropicMessage | ProviderRequestGeminiGenerateContent | ProviderRequestGoogleBatchEmbed | ProviderRequestVertexPredict | ProviderRequestRawV1"


class ProviderRequestAnthropicMessage(TypedDict):
    """Anthropic Messages request."""

    body: AnthropicMessagesRequest
    provider: Literal["anthropic_message"]


class ProviderRequestGeminiGenerateContent(TypedDict):
    """Google GenerateContent request, sent to Gemini or, when [`Prompt::provider`](crate::Prompt::provider) is Vertex, to Vertex."""

    body: GoogleGenerateContentRequest
    provider: Literal["gemini_generate_content"]


class ProviderRequestGoogleBatchEmbed(TypedDict):
    """Google Gemini BatchEmbedContents request."""

    body: GoogleBatchEmbedRequest
    provider: Literal["google_batch_embed"]


class ProviderRequestOpenAiChatCompletion(TypedDict):
    """OpenAI Chat Completions request, whether it is sent to OpenAI, a gateway, or a custom OpenAI-compatible endpoint named by [`Prompt::provider`](crate::Prompt::provider)."""

    body: OpenAiChatRequest
    provider: Literal["open_ai_chat_completion"]


class ProviderRequestOpenAiEmbeddings(TypedDict):
    """OpenAI Embeddings request."""

    body: OpenAiEmbeddingsRequest
    provider: Literal["open_ai_embeddings"]


class ProviderRequestOpenAiResponses(TypedDict):
    """OpenAI Responses API request."""

    body: OpenAiResponsesRequest
    provider: Literal["open_ai_responses"]


class ProviderRequestRawV1(TypedDict):
    """Raw provider request body that no typed variant models."""

    body: ProviderRequestRawV1Body
    provider: Literal["raw_v1"]


class ProviderRequestRawV1Body(TypedDict):
    """Generated Card schema type."""

    body: JsonValue
    provider: ProviderName


class ProviderRequestVertexPredict(TypedDict):
    """Vertex Predict request."""

    body: VertexPredictRequest
    provider: Literal["vertex_predict"]


# PSI numeric binning strategy.
PsiBinningStrategy: TypeAlias = "PsiBinningStrategyEqualWidth | PsiBinningStrategyQuantile"


class PsiBinningStrategyEqualWidth(TypedDict):
    """Equal-width bins across the baseline column range."""

    kind: Literal["EqualWidth"]
    n_bins: int


class PsiBinningStrategyQuantile(TypedDict):
    """Quantile bins from sorted baseline values."""

    kind: Literal["Quantile"]
    n_bins: int


# PSI alert threshold strategy.
PsiThreshold: TypeAlias = "PsiThresholdChiSquare | PsiThresholdNormal | PsiThresholdFixed"


class PsiThresholdChiSquare(TypedDict):
    """Chi-square approximation threshold."""

    alpha: float
    kind: Literal["ChiSquare"]


class PsiThresholdFixed(TypedDict):
    """Static threshold value."""

    kind: Literal["Fixed"]
    value: float


class PsiThresholdNormal(TypedDict):
    """Normal approximation threshold."""

    alpha: float
    kind: Literal["Normal"]


# DataCard SQL query key.
QueryName: TypeAlias = "str"

# A reference position that requires durable identity.
#
# Loaders rewrite `Path` values to `Sibling` values before submitting a request; the server rejects unresolved paths at the wire boundary. Authored `Ref` values remain external references even when they identify a submitted card.
Ref: TypeAlias = "CardRef | RefSibling | str"


class RefSibling(TypedDict):
    """A loader-projected reference to another submission in the same request."""

    sibling: CardRef


class _RegisteredAgentCardRequired(TypedDict):
    """Required keys of `RegisteredAgentCard`."""

    apiVersion: ApiVersion
    kind: Literal["Agent"]
    metadata: Metadata
    spec: AgentSpec


class RegisteredAgentCard(_RegisteredAgentCardRequired, total=False):
    """Registered `Agent` Card envelope."""

    relationships: Relationships
    status: Status | None


# One registered Card envelope as `cards.get` returns it, discriminated by `kind`.
RegisteredCard: TypeAlias = "RegisteredDataCard | RegisteredModelCard | RegisteredPromptCard | RegisteredAgentCard | RegisteredVerifierCard | RegisteredServiceCard | RegisteredTriggerCard | RegisteredOperatorCard | RegisteredUntypedCard"


class _RegisteredDataCardRequired(TypedDict):
    """Required keys of `RegisteredDataCard`."""

    apiVersion: ApiVersion
    kind: Literal["Data"]
    metadata: Metadata
    spec: DataSpec


class RegisteredDataCard(_RegisteredDataCardRequired, total=False):
    """Registered `Data` Card envelope."""

    relationships: Relationships
    status: Status | None


class _RegisteredModelCardRequired(TypedDict):
    """Required keys of `RegisteredModelCard`."""

    apiVersion: ApiVersion
    kind: Literal["Model"]
    metadata: Metadata
    spec: ModelSpec


class RegisteredModelCard(_RegisteredModelCardRequired, total=False):
    """Registered `Model` Card envelope."""

    relationships: Relationships
    status: Status | None


class _RegisteredOperatorCardRequired(TypedDict):
    """Required keys of `RegisteredOperatorCard`."""

    apiVersion: ApiVersion
    kind: Literal["Operator"]
    metadata: Metadata
    spec: OperatorSpec


class RegisteredOperatorCard(_RegisteredOperatorCardRequired, total=False):
    """Registered `Operator` Card envelope."""

    relationships: Relationships
    status: Status | None


class _RegisteredPromptCardRequired(TypedDict):
    """Required keys of `RegisteredPromptCard`."""

    apiVersion: ApiVersion
    kind: Literal["Prompt"]
    metadata: Metadata
    spec: PromptSpec


class RegisteredPromptCard(_RegisteredPromptCardRequired, total=False):
    """Registered `Prompt` Card envelope."""

    relationships: Relationships
    status: Status | None


class _RegisteredServiceCardRequired(TypedDict):
    """Required keys of `RegisteredServiceCard`."""

    apiVersion: ApiVersion
    kind: Literal["Service"]
    metadata: Metadata
    spec: ServiceSpec


class RegisteredServiceCard(_RegisteredServiceCardRequired, total=False):
    """Registered `Service` Card envelope."""

    relationships: Relationships
    status: Status | None


class _RegisteredTriggerCardRequired(TypedDict):
    """Required keys of `RegisteredTriggerCard`."""

    apiVersion: ApiVersion
    kind: Literal["Trigger"]
    metadata: Metadata
    spec: TriggerSpec


class RegisteredTriggerCard(_RegisteredTriggerCardRequired, total=False):
    """Registered `Trigger` Card envelope."""

    relationships: Relationships
    status: Status | None


class _RegisteredUntypedCardRequired(TypedDict):
    """Required keys of `RegisteredUntypedCard`."""

    apiVersion: ApiVersion
    kind: Literal["Experiment", "Workflow", "Policy", "Mcp", "Audit", "Artifact", "Source"]
    metadata: Metadata
    spec: dict[str, JsonValue]


class RegisteredUntypedCard(_RegisteredUntypedCardRequired, total=False):
    """Registered Card envelope of a kind whose spec is not typed yet."""

    relationships: Relationships
    status: Status | None


class _RegisteredVerifierCardRequired(TypedDict):
    """Required keys of `RegisteredVerifierCard`."""

    apiVersion: ApiVersion
    kind: Literal["Verifier"]
    metadata: Metadata
    spec: VerifierSpec


class RegisteredVerifierCard(_RegisteredVerifierCardRequired, total=False):
    """Registered `Verifier` Card envelope."""

    relationships: Relationships
    status: Status | None


class Relationships(TypedDict, total=False):
    """Server-derived relationship summary for graph, UI, policy, imports, and diff."""

    inbound: list[str]
    inbound_refs: list[CardRelationship]
    outbound: list[str]
    outbound_refs: list[CardRelationship]


# Expected response shape for a rendered prompt.
ResponseType: TypeAlias = 'Literal["text"] | ResponseTypeJsonSchema'


class ResponseTypeJsonSchema(TypedDict):
    """JSON response validated against a named schema by the runtime."""

    json_schema: ResponseTypeJsonSchemaJsonSchema


class ResponseTypeJsonSchemaJsonSchema(TypedDict):
    """Generated Card schema type."""

    name: str
    schema: JsonValue


class SampleInput(TypedDict):
    """Sample input description for loader-side rehydration."""

    kind: SampleInputKind


# Closed set of sample input shapes supported by Wyrd at the contract layer.
SampleInputKind: TypeAlias = 'Literal["Pandas", "Polars", "Arrow", "Numpy", "Torch", "Tf", "Dict", "List", "Tuple", "Str", "None"]'


class _ServiceComponentRequired(TypedDict):
    """Required keys of `ServiceComponent`."""

    alias: str
    ref: Ref


class ServiceComponent(_ServiceComponentRequired, total=False):
    """Alias-bound service component."""

    config: dict[str, NonSecretValue]
    credential_refs: list[CredentialRef]
    source: ComponentSource | None
    verified_by: list[VerificationBinding]


class _ServiceRuntimeRequired(TypedDict):
    """Required keys of `ServiceRuntime`."""

    kind: ServiceRuntimeKind


class ServiceRuntime(_ServiceRuntimeRequired, total=False):
    """Server-side runtime declaration; tenancy is inherited from `Card.metadata.space`."""

    config: dict[str, NonSecretValue]
    framework: str | None
    mode: ServiceRuntimeMode | None
    policy: ServiceRuntimePolicy | None
    strict: bool | None


# Service runtime kind.
ServiceRuntimeKind: TypeAlias = 'Literal["api", "mcp", "agent", "workflow"]'

# Service runtime placement mode.
ServiceRuntimeMode: TypeAlias = 'Literal["in_process"]'


class ServiceRuntimePolicy(TypedDict, total=False):
    """Service runtime policy settings."""

    runtime_hooks: bool


class ServiceSpec(TypedDict, total=False):
    """Composition of cards used by an application or deployment."""

    components: list[ServiceComponent]
    content_hash: str | None
    credential_refs: list[CredentialRef]
    deployment: dict[str, NonSecretValue]
    description: str | None
    entry_point: str | None
    lock_hash: str | None
    metadata: dict[str, NonSecretValue]
    runtime: ServiceRuntime | None
    service_config: dict[str, NonSecretValue]
    service_type: str | None
    verified_by: list[VerificationBinding]


class _SklearnMetaRequired(TypedDict):
    """Required keys of `SklearnMeta`."""

    framework_version: str


class SklearnMeta(_SklearnMetaRequired, total=False):
    """Config for the Sklearn model interface."""

    model_subtype: str | None


# Human-visible namespace for Cards and Runs.
SpaceName: TypeAlias = "str"

# DataCard split label.
SplitName: TypeAlias = "str"

# Data split strategy.
SplitStrategy: TypeAlias = "SplitStrategyMaterialized | SplitStrategyColumn | SplitStrategyIndexRange | SplitStrategyIndices"


class SplitStrategyColumn(TypedDict):
    """Predicate over a schema column."""

    kind: Literal["Column"]
    value: SplitStrategyColumnValue


class SplitStrategyColumnValue(TypedDict):
    """Generated Card schema type."""

    name: ColumnName
    op: Inequality
    value: ColValue


class SplitStrategyIndexRange(TypedDict):
    """Positional range using inclusive start and exclusive stop."""

    kind: Literal["IndexRange"]
    value: SplitStrategyIndexRangeValue


class SplitStrategyIndexRangeValue(TypedDict):
    """Generated Card schema type."""

    start: int
    stop: int


class SplitStrategyIndices(TypedDict):
    """Explicit positional indices."""

    kind: Literal["Indices"]
    value: list[int]


class SplitStrategyMaterialized(TypedDict):
    """Reference to an already materialized split artifact."""

    kind: Literal["Materialized"]
    value: Ref


class _SqlLogicRequired(TypedDict):
    """Required keys of `SqlLogic`."""

    queries: dict[str, str]


class SqlLogic(_SqlLogicRequired, total=False):
    """SQL query bundle associated with SQL-backed DataCards."""

    default_query: QueryName | None


class _SqlMetaRequired(TypedDict):
    """Required keys of `SqlMeta`."""

    dialect: str


class SqlMeta(_SqlMetaRequired, total=False):
    """SQL interface metadata."""

    connection_hint: str | None


class _StatusRequired(TypedDict):
    """Required keys of `Status`."""

    phase: str


class Status(_StatusRequired, total=False):
    """Server-derived Card status."""

    message: str | None
    updated_at: str | None
    verification: VerificationStatus | None


TaskId: TypeAlias = "str"

# Closed Wyrd ML task taxonomy.
TaskType: TypeAlias = 'Literal["BinaryClassification", "MultiClassClassification", "Regression", "Clustering", "AnomalyDetection", "Forecasting", "Generation", "Other"]'


class _TensorflowMetaRequired(TypedDict):
    """Required keys of `TensorflowMeta`."""

    framework_version: str
    save_format: TfSaveFormat


class TensorflowMeta(_TensorflowMetaRequired, total=False):
    """Config for the Tensorflow model interface."""

    model_subtype: str | None


class TextMeta(TypedDict, total=False):
    """Text manifest interface metadata."""

    encoding: str
    manifest_ref: Ref | None


# Save format for the Tensorflow model interface.
TfSaveFormat: TypeAlias = 'Literal["Keras", "SavedModel"]'


class TorchMeta(TypedDict):
    """Torch interface metadata."""

    framework_version: str
    save_format: TorchSaveFormat


class _TorchMeta2Required(TypedDict):
    """Required keys of `TorchMeta2`."""

    framework_version: str
    save_format: TorchSaveFormat2


class TorchMeta2(_TorchMeta2Required, total=False):
    """Config for the Torch model interface."""

    model_subtype: str | None


# Torch serialization formats accepted by DataCard.
TorchSaveFormat: TypeAlias = 'Literal["Safetensors", "Pickle"]'

# Save format for the Torch model interface.
TorchSaveFormat2: TypeAlias = 'Literal["Safetensors", "Pickle"]'

# Declarative activation for a bound Verifier.
TriggerSpec: TypeAlias = "TriggerSpecSchedule | TriggerSpecObservationsReady"


class _TriggerSpecObservationsReadyRequired(TypedDict):
    """Required keys of `TriggerSpecObservationsReady`."""

    kind: Literal["observations_ready"]


class TriggerSpecObservationsReady(_TriggerSpecObservationsReadyRequired, total=False):
    """Activate on each successfully committed observation for the subject.

    Declared as a fieldless struct variant so the enum-level `deny_unknown_fields` applies: a unit variant's internally tagged visitor would silently drain every sibling key, admitting typos and pasted secrets. The authored wire shape stays `{kind: observations_ready}`.
    """

    description: str | None


class _TriggerSpecScheduleRequired(TypedDict):
    """Required keys of `TriggerSpecSchedule`."""

    cron: str
    kind: Literal["schedule"]


class TriggerSpecSchedule(_TriggerSpecScheduleRequired, total=False):
    """Activate on each due occurrence of a cron schedule."""

    description: str | None
    tz: str | None


# Card kinds whose `spec` and `status` `cards.get` types.
TypedCardKind: TypeAlias = (
    'Literal["Data", "Model", "Prompt", "Agent", "Verifier", "Service", "Trigger", "Operator"]'
)


class _VerificationBindingRequired(TypedDict):
    """Required keys of `VerificationBinding`."""

    runs_on: InlineableRef_for_TriggerSpec
    verifier: Ref


class VerificationBinding(_VerificationBindingRequired, total=False):
    """One inline declaration attaching a Verifier to its containing subject.

    Authored on a Service, a Service component occurrence, or a standalone Agent. Registration resolves and UID-pins the Verifier, the effective Trigger, and every effective Operator before the owning Card persists.
    """

    on_failure: list[InlineableRef_for_OperatorSpec]


class VerificationError(TypedDict):
    """Structured, secret-free execution or delivery error."""

    code: str
    message: str


class VerificationStatus(TypedDict, total=False):
    """Server-derived verification state projected onto `card.status`.

    A Service or standalone Agent owning `verified_by` bindings exposes the stable identity of each projected binding here, so a caller can address a binding without a separate listing resource. The field is read-only: it is derived from the tenant's binding projection on every Card read and is never persisted as Card status.
    """

    baseline: DriftBaselineStatus | None
    binding_ids: list[str]


# The closed set of Verifier implementations.
#
# Adjacently tagged so that `implementation.kind` selects the variant and the variant's own typed body lives under `implementation.spec`. An unknown `kind` fails deserialization before validation or persistence, so a future implementation cannot be authored until its variant ships.
VerifierImplementation: TypeAlias = "VerifierImplementationDrift | VerifierImplementationEval"


class VerifierImplementationDrift(TypedDict):
    """Continuous distribution or metric drift over observed records."""

    kind: Literal["drift"]
    spec: DriftSpec


class VerifierImplementationEval(TypedDict):
    """Task-based evaluation over committed observations."""

    kind: Literal["eval"]
    spec: EvalSpec


class _VerifierSpecRequired(TypedDict):
    """Required keys of `VerifierSpec`."""

    implementation: VerifierImplementation


class VerifierSpec(_VerifierSpecRequired, total=False):
    """Verifier Card spec body.

    One Verifier declares one implementation. Independent judgments are composed by attaching multiple Verifier Cards, never by nesting implementations or introducing a Verifier DAG.
    """

    description: str | None


# Semver-compatible version string.
VersionBlock: TypeAlias = "str"

# Semantic version bump level.
#
# `Major`, `Minor`, and `Patch` perform a conventional semver bump and clear any pre-release / build metadata. `Pre`, `Build`, and `PreBuild` are additive: they apply the requested pre-release or build metadata to the existing triple without resetting it.
VersionBump: TypeAlias = (
    'Literal["major", "minor", "patch"] | VersionBumpPre | VersionBumpBuild | VersionBumpPreBuild'
)


class VersionBumpBuild(TypedDict):
    """Set the build metadata on the current triple (e.g. "001", "sha-abc123")."""

    build: VersionBumpBuildBuild


class VersionBumpBuildBuild(TypedDict):
    """Generated Card schema type."""

    metadata: str


class VersionBumpPre(TypedDict):
    """Set the pre-release identifier on the current triple (e.g. "rc.1")."""

    pre: VersionBumpPrePre


class VersionBumpPreBuild(TypedDict):
    """Set both pre-release and build metadata on the current triple."""

    pre_build: VersionBumpPreBuildPreBuild


class VersionBumpPreBuildPreBuild(TypedDict):
    """Generated Card schema type."""

    build: str
    pre: str


class VersionBumpPrePre(TypedDict):
    """Generated Card schema type."""

    identifier: str


# Authored version on the card-registration path. Either a full semver triple pin (e.g. "1.4.2", "1.4.2-rc.1+meta") or a bare partial scope (e.g. "1", "1.0"). Range comparators (^, ~, *, >=, ...) are rejected on this path.
VersionSpec: TypeAlias = "str"


class _VertexEmbedInstanceRequired(TypedDict):
    """Required keys of `VertexEmbedInstance`."""

    content: str


class VertexEmbedInstance(_VertexEmbedInstanceRequired, total=False):
    """Generated Card schema type."""

    task_type: str | None
    title: str | None


class VertexEmbedParameters(TypedDict, total=False):
    """Generated Card schema type."""

    auto_truncate: bool | None
    output_dimensionality: int | None


class _VertexPredictRequestRequired(TypedDict):
    """Required keys of `VertexPredictRequest`."""

    instances: list[VertexEmbedInstance]


class VertexPredictRequest(_VertexPredictRequestRequired, total=False):
    """Generated Card schema type."""

    parameters: VertexEmbedParameters | None


class Workflow(TypedDict):
    """Author-declared workflow field map for eval task inputs and outputs."""

    fields: dict[str, WorkflowFieldType]


# Declared JSON shape for one workflow field.
WorkflowFieldType: TypeAlias = (
    'Literal["string", "integer", "float", "boolean", "object", "array", "any"]'
)


class _XgboostMetaRequired(TypedDict):
    """Required keys of `XgboostMeta`."""

    framework_version: str


class XgboostMeta(_XgboostMetaRequired, total=False):
    """Config for the Xgboost model interface."""

    model_subtype: str | None
