// Build script for vala-bifrost.
//
// Generates `OUT_DIR/domain_schemas.rs` containing `SchemaRef` constructors
// and `[u8; 32]` fingerprint constants for each pre-declared domain table.
// DomainTable implementations in `src/tables/` access these via the
// `tables::generated` module which includes this file.
//
// Fingerprint is over user-fields-only Arrow IPC bytes (system + correlation
// columns excluded). Any user-field change flips the fingerprint.
//
// A checked-in mirror at `src/tables/generated_schemas.snapshot` is diffed
// against a fresh run by `mise run codegen:check`.

use std::env;
use std::fmt::Write as FmtWrite;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

#[path = "build/arrow_projection.rs"]
mod arrow_projection;

use arrow_projection::{ArrowProjection, BuildPolicy, compute_fingerprint, full_schema};

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let out_path = out_dir.join("domain_schemas.rs");

    let mut code = String::new();
    code.push_str(
        "// AUTO-GENERATED by vala-bifrost/build.rs — do not edit by hand.\n\
         // Regenerate with `mise run codegen:check`.\n\n\
         use ::std::sync::Arc;\n\
         use ::arrow::datatypes::{DataType, Field, Schema, SchemaRef, TimeUnit};\n\n",
    );

    emit_table::<arrow_projection::SpansTable>(
        &mut code,
        "TRACES_SPANS_FINGERPRINT",
        "traces_spans_schema",
        BuildPolicy::Observation,
    );
    emit_table::<arrow_projection::EventsTable>(
        &mut code,
        "TRACES_EVENTS_FINGERPRINT",
        "traces_events_schema",
        BuildPolicy::Observation,
    );
    emit_table::<arrow_projection::LinksTable>(
        &mut code,
        "TRACES_LINKS_FINGERPRINT",
        "traces_links_schema",
        BuildPolicy::Observation,
    );
    emit_table::<arrow_projection::MessagesTable>(
        &mut code,
        "GENAI_MESSAGES_FINGERPRINT",
        "genai_messages_schema",
        BuildPolicy::Observation,
    );
    emit_table::<arrow_projection::EmbeddingsTable>(
        &mut code,
        "GENAI_EMBEDDINGS_FINGERPRINT",
        "genai_embeddings_schema",
        BuildPolicy::Observation,
    );
    emit_table::<arrow_projection::ToolCallsTable>(
        &mut code,
        "GENAI_TOOL_CALLS_FINGERPRINT",
        "genai_tool_calls_schema",
        BuildPolicy::Observation,
    );
    emit_table::<arrow_projection::PointsTable>(
        &mut code,
        "METRICS_POINTS_FINGERPRINT",
        "metrics_points_schema",
        BuildPolicy::Observation,
    );
    emit_table::<arrow_projection::LogsRecordsTable>(
        &mut code,
        "LOGS_RECORDS_FINGERPRINT",
        "logs_records_schema",
        BuildPolicy::Observation,
    );
    emit_table::<arrow_projection::EvalRunsTable>(
        &mut code,
        "EVAL_RUNS_FINGERPRINT",
        "eval_runs_schema",
        BuildPolicy::Observation,
    );
    emit_table::<arrow_projection::EvalAssertionsTable>(
        &mut code,
        "EVAL_ASSERTIONS_FINGERPRINT",
        "eval_assertions_schema",
        BuildPolicy::Observation,
    );
    emit_table::<arrow_projection::DriftObservationsTable>(
        &mut code,
        "DRIFT_OBSERVATIONS_FINGERPRINT",
        "drift_observations_schema",
        BuildPolicy::Observation,
    );
    emit_table::<arrow_projection::AgentTracesTable>(
        &mut code,
        "DEV_AGENT_TRACES_FINGERPRINT",
        "dev_agent_traces_schema",
        BuildPolicy::CodeAxis,
    );
    // system — CorrelationPolicy::None: no universal correlation columns
    emit_table::<arrow_projection::AuditLogTable>(
        &mut code,
        "SYSTEM_AUDIT_LOG_FINGERPRINT",
        "system_audit_log_schema",
        BuildPolicy::None,
    );

    fs::File::create(&out_path)
        .expect("create domain_schemas.rs")
        .write_all(code.as_bytes())
        .expect("write domain_schemas.rs");

    // Update checked-in snapshot for codegen:check.
    let snapshot_path = PathBuf::from("src/tables/generated_schemas.snapshot");
    if let Ok(mut f) = fs::File::create(&snapshot_path) {
        let _ = f.write_all(code.as_bytes());
    }

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=build/arrow_projection.rs");
}

fn emit_table<T: ArrowProjection>(
    code: &mut String,
    fp_const: &str,
    schema_fn: &str,
    policy: BuildPolicy,
) {
    let user_fields = T::arrow_fields();
    let fp = compute_fingerprint(&user_fields);
    let full = full_schema(user_fields, policy);

    // fingerprint constant
    writeln!(code, "pub const {fp_const}: [u8; 32] = {fp:?};")
        .expect("write to OUT_DIR schema file");

    // schema constructor
    writeln!(code, "pub fn {schema_fn}() -> SchemaRef {{").expect("write to OUT_DIR schema file");
    writeln!(code, "    Arc::new(Schema::new(vec![").expect("write to OUT_DIR schema file");
    for f in full.fields() {
        let dt = format_dtype(f.data_type());
        writeln!(
            code,
            "        Field::new({:?}, {dt}, {}),",
            f.name(),
            f.is_nullable()
        )
        .expect("write to OUT_DIR schema file");
    }
    writeln!(code, "    ]))").expect("write to OUT_DIR schema file");
    writeln!(code, "}}").expect("write to OUT_DIR schema file");
    writeln!(code).expect("write to OUT_DIR schema file");
}

fn format_dtype(dt: &arrow::datatypes::DataType) -> String {
    use arrow::datatypes::{DataType, TimeUnit};
    match dt {
        DataType::Utf8 => "DataType::Utf8".into(),
        DataType::Utf8View => "DataType::Utf8View".into(),
        DataType::Boolean => "DataType::Boolean".into(),
        DataType::Int32 => "DataType::Int32".into(),
        DataType::Int64 => "DataType::Int64".into(),
        DataType::UInt32 => "DataType::UInt32".into(),
        DataType::UInt64 => "DataType::UInt64".into(),
        DataType::Float64 => "DataType::Float64".into(),
        DataType::FixedSizeBinary(n) => format!("DataType::FixedSizeBinary({n})"),
        DataType::Timestamp(unit, tz) => {
            let u = match unit {
                TimeUnit::Microsecond => "TimeUnit::Microsecond",
                TimeUnit::Nanosecond => "TimeUnit::Nanosecond",
                TimeUnit::Millisecond => "TimeUnit::Millisecond",
                TimeUnit::Second => "TimeUnit::Second",
            };
            match tz {
                Some(tz_str) => format!("DataType::Timestamp({u}, Some(\"{tz_str}\".into()))"),
                None => format!("DataType::Timestamp({u}, None)"),
            }
        }
        other => format!("/* unsupported: {other:?} */ DataType::Utf8"),
    }
}
