// Build script for vala-bifrost.
//
// Generates `OUT_DIR/domain_schemas.rs` containing `SchemaRef` constructors
// and `SCHEMA_FINGERPRINT: [u8; 32]` constants for each pre-declared domain
// table. The DomainTable implementations in `src/tables/<domain>/` include
// this file via:
//   include!(concat!(env!("OUT_DIR"), "/domain_schemas.rs"))
//
// The fingerprint is over the canonical Arrow IPC bytes of each table's
// user fields only, excluding system columns and policy-appended correlation
// columns. Any change to a user field flips the fingerprint.
//
// A checked-in mirror at `src/tables/generated_schemas.snapshot` is diffed
// against a fresh run by `mise run codegen:check`.

use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

#[path = "build/arrow_projection.rs"]
mod arrow_projection;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let out_path = out_dir.join("domain_schemas.rs");

    let mut out = fs::File::create(&out_path).expect("create domain_schemas.rs");

    // Header comment.
    writeln!(
        out,
        "// AUTO-GENERATED by vala-bifrost/build.rs — do not edit by hand."
    )
    .unwrap();
    writeln!(out, "// Regenerate with `mise run codegen:check`.").unwrap();
    writeln!(out).unwrap();

    // Placeholder — table schemas are generated here as each DomainTable lands.
    // Each block looks like:
    //
    //   pub mod spans_schema {
    //       pub const SCHEMA_FINGERPRINT: [u8; 32] = [...];
    //       pub fn schema() -> arrow::datatypes::SchemaRef { ... }
    //   }
    //
    // Task 04-11 will add their blocks here.

    writeln!(out, "// No domain table schemas generated yet — tasks 04-11 will add them.").unwrap();

    // Rerun if the build script or projection module changes.
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=build/arrow_projection.rs");
}

/// Compute a SHA-256 fingerprint over the Arrow IPC bytes of a schema's user
/// fields. This is the fingerprint stored in `vala.bifrost_tables` and compared
/// at startup by `register::<T>`.
#[allow(dead_code)]
fn compute_fingerprint(user_fields: &[arrow::datatypes::Field]) -> [u8; 32] {
    use sha2::{Digest, Sha256};
    let schema = arrow::datatypes::Schema::new(user_fields.to_vec());
    let mut buf = vec![];
    {
        let mut writer =
            arrow::ipc::writer::FileWriter::try_new(&mut buf, &schema).expect("ipc writer");
        writer.finish().expect("finish ipc");
    }
    let mut hasher = Sha256::new();
    hasher.update(&buf);
    hasher.finalize().into()
}
