/* auto-generated by NAPI-RS */
/* eslint-disable */
/** In-process server handle used only by TypeScript integration tests. */
export declare class NativeWyrdTestServer {
  /** Returns the bound HTTP base URL. */
  get baseUrl(): string
  /** Returns the bound gRPC ingest URL. */
  get grpcUrl(): string
  /** Returns the integration-only admin bearer. */
  get token(): string
  /** Returns the registered table used by the TypeScript Oracle journey. */
  get tableFqn(): string
  /**
   * Returns the writer principal's API key, which `Bifrost` authenticates with.
   *
   * The query journeys exchange this for a bearer through
   * [`Self::token`]; the write journey needs the key itself because the
   * write handle resolves its own credential.
   */
  get apiKey(): string
  /**
   * Returns the Card the writer principal is scoped to.
   *
   * Every row written with [`Self::api_key`] must correlate to this Card, so
   * the harness publishes it rather than making each test restate it.
   */
  get cardRef(): string
  /**
   * Seed rows through the real gRPC ingest and Scribe flush paths.
   *
   * # Errors
   *
   * Returns a napi error when the harness is closed or registration,
   * encoding, ingest, or flushing fails.
   */
  seedBifrostRows(table: string, rows: Array<number>): Array<number>
  /**
   * Wait for the test-tier Scribe publication barrier after a public write.
   *
   * This does not expose a production flush API; it only lets a journey
   * await the existing server-owned publication lifecycle before Oracle
   * reads the acknowledged batch.
   *
   * # Errors
   *
   * Returns a napi error when the server lock is poisoned, the server is
   * shut down, or the publication barrier fails.
   */
  waitForBifrostPublication(): void
  /**
   * Flush Scribe so rows written through the public SDK become queryable.
   *
   * A client `flush` only proves the server accepted the batch; the rows
   * reach a readable source after Scribe drains, which a test must wait for
   * rather than sleep on.
   *
   * # Errors
   *
   * Returns a napi error when the harness is closed or the flush fails.
   */
  flushBifrost(): void
  /**
   * Bring binding `binding_id`'s schedule cursor to database time, so the
   * verification runtime schedules its next occurrence now.
   *
   * # Errors
   *
   * Returns a napi error when the harness is closed, `binding_id` is not a
   * binding ID, or the update fails.
   */
  makeBindingDue(bindingId: string): void
  /**
   * Every verification run ID of the fixture tenant, oldest first.
   *
   * # Errors
   *
   * Returns a napi error when the harness is closed or the runs cannot be
   * read.
   */
  verificationRuns(): Array<string>
  /**
   * Strip the fitted-profile format from Verifier `verifier_uid`'s ready
   * baseline, as a baseline fitted under earlier semantics is stored.
   *
   * # Errors
   *
   * Returns a napi error when the harness is closed, `verifier_uid` is not
   * a Card UID, or no ready baseline exists.
   */
  retireFittedFormat(verifierUid: string): void
  /**
   * Provision one canonical built-in table for the fixture tenant.
   *
   * A canonical signal ledger is server-owned, so a journey cannot register
   * it through the public write path. This is the harness door that makes
   * `vala.traces.spans`, `vala.logs.records` and `vala.metrics.points`
   * exist before a public Arrow write reaches them.
   *
   * # Errors
   *
   * Returns a napi error when the harness is closed or provisioning fails.
   */
  ensureBuiltinTable(namespace: string, name: string): void
  /**
   * Mint an API key for a principal holding exactly `permissions`.
   *
   * `permissions` are `resource:action` strings. This is the door a journey
   * uses to prove an access gate from the caller's side: it seeds one role
   * carrying only those grants and bootstraps a service onto it.
   *
   * # Errors
   *
   * Returns a napi error for an unparsable permission, or when the harness
   * is closed or role seeding or bootstrapping fails.
   */
  scopedApiKey(role: string, permissions: Array<string>): string
  /**
   * Issue an API key for the principal a registered Service Card projects.
   *
   * `card_ref` is the canonical `space/Kind/name@version` identity a
   * registration receipt returns. The Card must already be registered: this
   * credentials the service account registration projected for it rather
   * than minting a new one, so the key carries the registered Service's real
   * card-ref scope and a run may observe the component Cards its spec
   * references.
   *
   * # Errors
   *
   * Returns a napi error for a malformed identity string, or when the
   * harness is closed or the Card has no projected principal.
   */
  credentialRegisteredService(cardRef: string, roles: Array<string>): string
  /**
   * Mint an authenticated token without `bifrost_query:read`.
   *
   * # Errors
   *
   * Returns a napi error when the harness is closed or token issuance fails.
   */
  queryDeniedToken(): string
  /**
   * Return the durable read-decision audit count for the fixture tenant.
   *
   * # Errors
   *
   * Returns a napi error when the harness is closed or the audit query fails.
   */
  bifrostReadDecisionCount(): number
  /**
   * Return the staged allowed describe decisions for one table FQN.
   *
   * Every server describe stages exactly one decision, so a journey started
   * with audit publication disabled reads how many schema describes a table
   * has received.
   *
   * # Errors
   *
   * Returns a napi error when the harness is closed or the audit query fails.
   */
  tableDescribeCount(fqn: string): number
  /**
   * Make every describe of one table FQN fail until restored.
   *
   * The server answers the failed describe with
   * `WYRD_VALA_500_AUDIT_UNAVAILABLE`.
   *
   * # Errors
   *
   * Returns a napi error when the harness is closed, the FQN is not a
   * dotted identifier, or installing the fault fails.
   */
  failTableDescribe(fqn: string): void
  /**
   * Remove the describe fault installed by `fail_table_describe`.
   *
   * # Errors
   *
   * Returns a napi error when the harness is closed or removing the fault
   * fails.
   */
  restoreTableDescribe(): void
  /**
   * Truncate the next query after its schema frame.
   *
   * # Errors
   *
   * Returns a napi error when the server lock is poisoned or the server is
   * shut down.
   */
  failNextQueryAfterSchema(): void
  /**
   * Truncate the next query after its first batch frame.
   *
   * # Errors
   *
   * Returns a napi error when the server lock is poisoned or the server is
   * shut down.
   */
  failNextQueryAfterBatch(): void
  /**
   * Gracefully shuts down the in-process server once.
   *
   * # Errors
   *
   * Returns a napi error when the Rust harness cannot complete shutdown.
   */
  shutdown(): void
}

/**
 * Starts a real bound Wyrd test server and mints an admin access token.
 *
 * `auditPublication: false` keeps staged audit rows for assertions.
 * `verificationRuntime: true` runs Drift baseline fitting and Verifier runs.
 * `providerBaseUrl` roots built-in gateway adapters at a local mock upstream.
 *
 * # Errors
 *
 * Returns a napi error for an invalid provider URL or server setup failure.
 */
export declare function startTestServer(providerBaseUrl?: string | undefined | null, auditPublication?: boolean | undefined | null, verificationRuntime?: boolean | undefined | null): NativeWyrdTestServer
