/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * In-process server handle used only by TypeScript integration tests.
 *
 * Journeys steer the server through exactly three test controls, each backed
 * by the production code path: `flushBifrost`, `waitForBaseline`, and
 * `makeBindingDue`. The remaining members start, address, or credential the
 * server.
 */
export declare class NativeWyrdTestServer {
  /** Returns the bound HTTP base URL. */
  get baseUrl(): string
  /** Returns the bound gRPC ingest URL. */
  get grpcUrl(): string
  /** Returns the integration-only admin bearer. */
  get token(): string
  /** Returns the registered table used by the TypeScript Oracle journey. */
  get tableFqn(): string
  /**
   * Returns the writer principal's API key, which `Bifrost` authenticates with.
   *
   * The query journeys exchange this for a bearer through
   * [`Self::token`]; the write journey needs the key itself because the
   * write handle resolves its own credential.
   */
  get apiKey(): string
  /**
   * Returns the Card the writer principal is scoped to.
   *
   * Every row written with [`Self::api_key`] must correlate to this Card, so
   * the harness publishes it rather than making each test restate it.
   */
  get cardRef(): string
  /**
   * Flush Scribe so rows written through the public SDK become queryable.
   *
   * A client `flush` only proves the server accepted the batch; the rows
   * reach a readable source after Scribe drains, which a test must wait for
   * rather than sleep on.
   *
   * # Errors
   *
   * Throws a `WyrdError`-shaped error (`code`, `status`, `title`, `detail`,
   * `remediation`, `details`) when the harness is closed or the flush
   * fails.
   */
  flushBifrost(): void
  /**
   * Bring binding `binding_id`'s schedule cursor to database time, so the
   * verification runtime schedules its next occurrence now.
   *
   * # Errors
   *
   * Throws a `WyrdError`-shaped error when the harness is closed,
   * `binding_id` is not a binding ID, or the update fails.
   */
  makeBindingDue(bindingId: string): void
  /**
   * Wait until Drift Verifier `verifier`'s fitted baseline is ready.
   *
   * `verifier` is the Verifier Card UID. The harness polls the baseline
   * status a Card read serves for at most `timeoutMs` milliseconds.
   *
   * # Errors
   *
   * Throws a `WyrdError`-shaped error when the harness is closed or
   * `verifier` is not a Card UID, and one with code
   * `WYRD_VERIFICATION_409_BASELINE_NOT_READY` whose `details.baseline` is
   * the last observed baseline status when `timeoutMs` elapses first.
   */
  waitForBaseline(verifier: string, timeoutMs: number): void
  /**
   * Mint an API key for a principal holding exactly `permissions`.
   *
   * `permissions` are `resource:action` strings. This is the door a journey
   * uses to prove an access gate from the caller's side: it seeds one role
   * carrying only those grants and bootstraps a service onto it.
   *
   * # Errors
   *
   * Returns a napi error for an unparsable permission, or when the harness
   * is closed or role seeding or bootstrapping fails.
   */
  scopedApiKey(role: string, permissions: Array<string>): string
  /**
   * Provision a second active tenant so a journey can prove cross-tenant
   * isolation, returning its tenant ID.
   *
   * The tenant is seeded through the same operator path the Rust harness
   * uses, so the journey observes the production tenancy boundary.
   *
   * # Errors
   *
   * Returns a napi error when the harness is closed or seeding fails.
   */
  seedTenant(slug: string): string
  /**
   * Bootstrap a service principal holding exactly the built-in or seeded
   * `roles` in the fixture tenant and return its API key.
   *
   * The door a journey uses for a machine caller with a known role set,
   * such as one holding only `workload` to prove a gate from the caller's
   * side.
   *
   * # Arguments
   *
   * * `roles` - The role names the principal holds.
   * * `name` - The principal's fixture Service name, unique per harness.
   *
   * # Errors
   *
   * Returns a napi error when the harness is closed or bootstrapping fails.
   */
  bootstrapService(roles: Array<string>, name: string): string
  /**
   * Bootstrap a service principal holding `roles` in tenant `tenant_id` and
   * return its API key.
   *
   * Pairs with [`Self::seed_tenant`]: the key is the foreign caller a
   * cross-tenant journey uses to prove the fixture tenant is unreachable.
   *
   * # Errors
   *
   * Returns a napi error when `tenant_id` is not a tenant ID, the harness
   * is closed, or bootstrapping fails.
   */
  bootstrapServiceInTenant(tenantId: string, roles: Array<string>, name: string): string
  /**
   * Activate the identity lane's Keycloak sign-in for one tenant and
   * return its id: the fixture tenant when `tenantSlug` is absent, else a
   * newly seeded tenant of that slug with its own administrator.
   *
   * Needs `startTestServer({ humanSso: true })` and the identity lane's
   * Keycloak.
   *
   * # Errors
   *
   * Returns a napi error when the harness is closed, seeding fails, or any
   * served activation step panics.
   */
  activateHumanSso(tenantSlug?: string | undefined | null): string
  /**
   * Log `username` in to `tenant` through the RFC 8628 device login and
   * save the credential under the Wyrd configuration directory `configHome`,
   * exactly as `wyrd auth login` does.
   *
   * # Errors
   *
   * Returns a napi error when the login or the save panics.
   */
  saveHumanLogin(configHome: string, tenant: string, username: string, password: string): void
  /**
   * Make the saved login for `tenant` under `configHome` stale, so the
   * next client renews it.
   *
   * # Errors
   *
   * Returns a napi error when the login is missing or cannot be saved.
   */
  expireSavedLogin(configHome: string, tenant: string): void
  /**
   * Whether the saved login for `tenant` under `configHome` holds an
   * expired access token, so a journey can prove a renewal was saved.
   *
   * # Errors
   *
   * Returns a napi error when the login is missing.
   */
  savedLoginIsStale(configHome: string, tenant: string): boolean
  /**
   * Revoke the server-side refresh chain of the saved login for `tenant`
   * under `configHome` without touching the record, as another device's
   * logout would.
   *
   * # Errors
   *
   * Returns a napi error when the login is not ready or the server refuses
   * the revocation.
   */
  revokeSavedLogin(configHome: string, tenant: string): void
  /**
   * Gracefully shuts down the in-process server once.
   *
   * # Errors
   *
   * Returns a napi error when the Rust harness cannot complete shutdown.
   */
  shutdown(): void
}

/**
 * Registers a local Card tree and returns its receipt (`wyrd apply`).
 *
 * # Errors
 *
 * Returns a napi error only when the receipt cannot be serialized; local,
 * client, and server failures are returned in the outcome.
 */
export declare function cliApply(path: string, connection?: NativeCliConnection | undefined | null): Promise<NativeCliOutcome>

/**
 * Deletes one unreferenced provider credential; an absent name succeeds
 * (`wyrd gateway credential delete`).
 *
 * # Errors
 *
 * Returns a napi error only when the result cannot be serialized; an invalid
 * name, client, or server failure is returned in the outcome.
 */
export declare function cliDeleteProviderCredential(name: string, connection?: NativeCliConnection | undefined | null): Promise<NativeCliOutcome>

/**
 * Hydrates a Card's reachable graph into `output_dir` (`wyrd get`).
 *
 * # Errors
 *
 * Returns a napi error only when the summary cannot be serialized; selector,
 * client, and server failures are returned in the outcome.
 */
export declare function cliGet(selector: NativeCardSelector, outputDir: string, metadataOnly?: boolean | undefined | null, connection?: NativeCliConnection | undefined | null): Promise<NativeCliOutcome>

/**
 * Issues an API key bound to one exact Card (`wyrd auth issue-key`).
 *
 * The outcome holds the plaintext key exactly once.
 *
 * # Errors
 *
 * Returns a napi error only when the response cannot be serialized;
 * coordinate, client, and server failures are returned in the outcome.
 */
export declare function cliIssueKey(options: NativeIssueKey, connection?: NativeCliConnection | undefined | null): Promise<NativeCliOutcome>

/**
 * Loads one Card and materializes its artifacts (`wyrd load`).
 *
 * # Errors
 *
 * Returns a napi error only when the output cannot be serialized; selector,
 * client, and server failures are returned in the outcome.
 */
export declare function cliLoad(selector: NativeCardSelector, path?: string | undefined | null, connection?: NativeCliConnection | undefined | null): Promise<NativeCliOutcome>

/**
 * Validates a local Card tree without contacting a server (`wyrd plan`).
 *
 * # Errors
 *
 * Returns a napi error only when the plan cannot be serialized; a load
 * failure is returned in the outcome.
 */
export declare function cliPlan(path: string): NativeCliOutcome

/**
 * Creates or rotates one provider credential (`wyrd gateway credential put`).
 *
 * A decode failure quotes no part of the body, which may carry a provider
 * key; the returned view is redacted.
 *
 * # Errors
 *
 * Returns a napi error only when the view cannot be serialized; a malformed
 * body, client, or server failure is returned in the outcome.
 */
export declare function cliPutProviderCredential(write: any, connection?: NativeCliConnection | undefined | null): Promise<NativeCliOutcome>

/**
 * Terminally revokes one provider credential
 * (`wyrd gateway credential revoke`).
 *
 * # Errors
 *
 * Returns a napi error only when the view cannot be serialized; an invalid
 * name, client, or server failure is returned in the outcome.
 */
export declare function cliRevokeProviderCredential(name: string, connection?: NativeCliConnection | undefined | null): Promise<NativeCliOutcome>

/**
 * Card selector for `get` and `load`: a `uid` with `kind`, or `kind`,
 * `space`, and `name`; `version` narrows either.
 */
export interface NativeCardSelector {
  /** Card kind, such as `Model` or `Prompt`. */
  kind?: string
  /** Card space. */
  space?: string
  /** Card name. */
  name?: string
  /** Exact Card version. */
  version?: string
  /** Exact Card UID. */
  uid?: string
}

/**
 * Explicit client a command runs as: a public `WyrdClient`'s endpoints and
 * its current access token.
 *
 * Native objects cannot cross from `@wyrd/sdk` into this addon, so the
 * wrapper reads the client's public `serverUrl`, `grpcUrl`, and
 * `accessToken()` and the command presents that token verbatim.
 */
export interface NativeCliConnection {
  /** HTTP base URL of the Wyrd server. */
  serverUrl: string
  /** gRPC endpoint of the Wyrd server. */
  grpcUrl: string
  /** Current bearer of the caller's client. */
  accessToken: string
}

/** Closed result of one command: its JSON value or its problem document. */
export interface NativeCliOutcome {
  /** JSON the command prints with `--format json`, when it succeeded. */
  valueJson?: string
  /**
   * Catalog problem document (`code`, `status`, `title`, `detail`,
   * `remediation`, `details`), when it failed.
   */
  problemJson?: string
}

/** Options for `issueKey`: the bound Card and the key's label and lifetime. */
export interface NativeIssueKey {
  /** Card kind, such as `Service` or `Agent`. */
  kind: string
  /** Card name. */
  name: string
  /** Exact Card version. */
  version: string
  /** Card space. */
  space: string
  /** Optional label stored with the key row. */
  label?: string
  /** Optional lifetime override in seconds. */
  expiresInSeconds?: number
}

/**
 * Test-only capabilities a story's server starts with; every field is
 * optional and defaults to off, except `auditPublication`.
 */
export interface NativeTestServerOptions {
  /**
   * Roots built-in gateway adapters at a local mock upstream; its `/v1`
   * segment also serves the verification runtime's `OpenAI` Eval judge,
   * which calls `<providerBaseUrl>/v1/chat/completions`.
   */
  providerBaseUrl?: string
  /** `false` keeps staged audit rows for assertions; defaults to `true`. */
  auditPublication?: boolean
  /** `true` runs Drift baseline fitting and Verifier runs. */
  verificationRuntime?: boolean
  /**
   * `true` serves the public origin the identity lane's Keycloak clients
   * register, for saved user login journeys.
   */
  humanSso?: boolean
}

/**
 * Starts a real bound Wyrd test server and mints an admin access token.
 *
 * `options` selects the test-only capabilities; omitted, the server keeps
 * its default upstreams, publishes audit, and runs no verification runtime.
 *
 * # Errors
 *
 * Returns a napi error for an invalid provider URL or server setup failure.
 */
export declare function startTestServer(options?: NativeTestServerOptions | undefined | null): NativeWyrdTestServer
