[package]
name = "wyrd-dev-fixtures"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }

[features]
default = []
pg = [
    "dep:secrecy",
    "dep:serde_json",
    "dep:sqlx",
    "dep:thiserror",
    "dep:tokio",
    "dep:url",
    "dep:uuid",
    "dep:vala-sql",
    "dep:wyrd-sql",
    "dep:wyrd-spec",
]

[dependencies]
secrecy = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
sqlx = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
tokio = { workspace = true, optional = true, features = ["macros", "rt-multi-thread"] }
url = { workspace = true, optional = true }
uuid = { workspace = true, optional = true, features = ["v7"] }
vala-sql = { path = "../../vala/vala-sql", version = "0.0.1", optional = true }
wyrd-sql = { path = "../../wyrd/wyrd-sql", version = "0.0.1", optional = true }
wyrd-spec = { workspace = true, optional = true }

[dev-dependencies]
workspace-hack.workspace = true
