[package]
name = "wyrd-auth-issue"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }

[dependencies]
jsonwebtoken = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true, features = ["clock"] }
argon2 = { workspace = true }
password-hash = { workspace = true }
secrecy = { workspace = true }
zeroize = { workspace = true }
wyrd-spec = { path = "../../wyrd-spec", version = "0.0.1" }
wyrd-auth-verify = { path = "../wyrd-auth-verify", version = "0.0.1" }
