use std::sync::Arc;

use arrow::datatypes::SchemaRef;

use crate::catalog::WyrdCatalog;
use crate::error::BifrostError;
use crate::types::PartitionTransform;
use wyrd_spec::vala::system_columns::{
    DATA_TENANT_ID, WYRD_BATCH_ID, WYRD_EVENT_TIME, WYRD_INGESTED_AT, is_reserved_system_column,
};

pub mod system_columns;

pub(crate) mod generated {
    include!(concat!(env!("OUT_DIR"), "/domain_schemas.rs"));
}

pub mod dev;
pub mod drift;
pub mod eval;
pub mod genai;
pub mod logs;
pub mod metrics;
pub mod system;
pub mod traces;

/// Which universal correlation columns a pre-declared domain table carries (C-01).
///
/// A single universal policy is wrong — the pre-declared set spans three shapes.
/// Each table declares its policy; `ensure_system_cols` appends columns from the
/// policy, not unconditionally.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CorrelationPolicy {
    /// Observation facts (traces, metrics, logs, genai, eval, drift).
    /// Appends `run_id`, `card_uid`, `principal_id` (all nullable).
    Observation,
    /// `agent_traces`: the code axis owns `run_id`, so the universal `run_id` is
    /// NOT appended (it would collide with the code-axis column).
    /// `card_uid` + `principal_id` ARE appended.
    CodeAxis,
    /// `audit_log`: 16 bespoke content columns + Bifrost system columns, NO
    /// universal correlation columns appended. `audit_card_ref` is the
    /// writer-identity content column, distinct from correlation `card_uid`.
    None,
}

impl CorrelationPolicy {
    /// Returns the names of the universal correlation columns this policy appends.
    pub fn appended_correlation_columns(self) -> &'static [&'static str] {
        match self {
            Self::Observation => &[
                wyrd_spec::vala::RUN_ID,
                wyrd_spec::vala::CARD_UID,
                wyrd_spec::vala::PRINCIPAL_ID,
            ],
            Self::CodeAxis => &[wyrd_spec::vala::CARD_UID, wyrd_spec::vala::PRINCIPAL_ID],
            Self::None => &[],
        }
    }
}

/// Write-path payload classification (M-03).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PayloadClass {
    /// No sensitive-default payload columns — commit untouched.
    Standard,
    /// Carries sensitive-default payload named by `DomainTable::SENSITIVE_PAYLOAD_COLUMNS`.
    /// The built-in redaction pass scrubs those columns on write before commit.
    Sensitive,
}

/// Sort key specification for a domain table.
#[derive(Debug, Clone)]
pub struct SortKey {
    pub column: String,
    pub ascending: bool,
    pub nulls_first: bool,
}

/// Index declared by a domain table for `vala.olap_indexes`.
#[derive(Debug, Clone)]
pub struct DeclaredIndex {
    pub name: String,
    pub columns: Vec<String>,
    pub kind: IndexKind,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IndexKind {
    BloomFilter,
    ZOrder,
}

/// Mapping for `entity_time_bounds` best-effort acceleration (M-06).
#[derive(Debug, Clone)]
pub struct EntityBoundsMapping {
    pub entity_kind: String,
    pub entity_id_column: String,
}

/// Pre-declared domain table contract.
///
/// Implementors declare schema, correlation policy, payload class, partition
/// columns, sort keys, declared indexes, and (optionally) entity bounds mapping.
/// The `register_all` boot path pins each table to its `SCHEMA_FINGERPRINT`.
pub trait DomainTable: Send + Sync + 'static {
    const NAMESPACE: &'static str;
    const NAME: &'static str;
    /// SHA-256 over the canonical Arrow IPC bytes of the table's user fields,
    /// excluding system columns and the policy-appended correlation columns.
    const SCHEMA_FINGERPRINT: [u8; 32];
    /// Per-table correlation policy (C-01).
    const CORRELATION_POLICY: CorrelationPolicy;
    /// Write-path payload classification (M-03). Defaults to `Standard`.
    const PAYLOAD_CLASS: PayloadClass = PayloadClass::Standard;
    /// Sensitive payload columns scanned by the redaction pass. Non-empty exactly
    /// when `PAYLOAD_CLASS == Sensitive`. Single source of truth for both the
    /// write-path pass (M-03) and the task-16 read gate.
    const SENSITIVE_PAYLOAD_COLUMNS: &'static [&'static str] = &[];

    /// Full physical schema including user fields, correlation columns per policy,
    /// and Bifrost system columns. Generated by `build.rs`.
    fn schema() -> SchemaRef;

    /// Partition columns as `(column_name, transform)` pairs. Defaults to
    /// `day(wyrd_event_time)` which matches the `PartitionSpec` builder.
    fn partition_columns() -> Vec<(String, PartitionTransform)> {
        vec![(WYRD_EVENT_TIME.to_string(), PartitionTransform::Day)]
    }

    fn sort_keys() -> Vec<SortKey>;
    fn declared_indexes() -> Vec<DeclaredIndex>;

    /// Best-effort `entity_time_bounds` producer mapping (M-06). `Some` names the
    /// `entity_kind` + which physical column supplies `entity_id`. `None` = no bounds.
    fn entity_bounds_mapping() -> Option<EntityBoundsMapping> {
        None
    }
}

/// Policy-aware reserved-field validation (C-03).
///
/// For a pre-declared table: rejects a declared user field only when its name
/// would actually duplicate a column the table gets from system columns or the
/// policy-appended correlation set.
///
/// - System names are always rejected regardless of policy (C-02 guard).
/// - A universal-correlation name is rejected only if the table's policy appends it.
pub fn reject_reserved_domain_fields(
    user_field_names: &[&str],
    policy: CorrelationPolicy,
) -> Result<(), BifrostError> {
    let appended = policy.appended_correlation_columns();
    let always_reserved = [
        WYRD_EVENT_TIME,
        WYRD_INGESTED_AT,
        WYRD_BATCH_ID,
        DATA_TENANT_ID,
    ];
    for name in user_field_names {
        if always_reserved.contains(name) || is_reserved_system_column(name) {
            return Err(BifrostError::ReservedColumn((*name).to_string()));
        }
        if appended.contains(name) {
            return Err(BifrostError::ReservedColumn((*name).to_string()));
        }
    }
    Ok(())
}

/// Register all pre-declared domain tables at boot. Called from `WyrdCatalog::new`.
///
/// Append-only — do not reorder or remove entries.
pub async fn register_all(catalog: &Arc<WyrdCatalog>) -> Result<(), BifrostError> {
    // traces
    register::<traces::SpansTable>(catalog).await?;
    register::<traces::EventsTable>(catalog).await?;
    register::<traces::LinksTable>(catalog).await?;
    // genai
    register::<genai::MessagesTable>(catalog).await?;
    register::<genai::EmbeddingsTable>(catalog).await?;
    register::<genai::ToolCallsTable>(catalog).await?;
    // metrics
    register::<metrics::PointsTable>(catalog).await?;
    // logs
    register::<logs::RecordsTable>(catalog).await?;
    // eval
    register::<eval::RunsTable>(catalog).await?;
    register::<eval::AssertionsTable>(catalog).await?;
    // drift
    register::<drift::ObservationsTable>(catalog).await?;
    // dev
    register::<dev::AgentTracesTable>(catalog).await?;
    // system
    register::<system::AuditLogTable>(catalog).await?;
    Ok(())
}

/// Register a single pre-declared domain table with exhaustive cross-store
/// state checking and concurrent-boot fencing (M-01/M-02).
pub async fn register<T: DomainTable>(catalog: &Arc<WyrdCatalog>) -> Result<(), BifrostError> {
    let _guard = catalog.advisory_lock_for(T::NAMESPACE, T::NAME).await?;

    let control = catalog
        .domain_table_fingerprint(T::NAMESPACE, T::NAME)
        .await?;
    let iceberg = catalog.iceberg_table_exists(T::NAMESPACE, T::NAME).await?;

    match (control, iceberg) {
        // STEADY STATE — only healthy path (M-01).
        (Some(fp), true) if fp == T::SCHEMA_FINGERPRINT => {
            let physical = catalog
                .iceberg_physical_schema(T::NAMESPACE, T::NAME)
                .await?;
            if catalog.physical_matches_declared::<T>(&physical) {
                Ok(())
            } else {
                Err(BifrostError::PhysicalDrift {
                    namespace: T::NAMESPACE,
                    name: T::NAME,
                    expected: T::SCHEMA_FINGERPRINT,
                    actual: catalog.fingerprint_of_user_fields(&physical),
                })
            }
        }
        // Control present, Iceberg MISSING — terminal (M-01).
        (Some(_), false) => Err(BifrostError::IcebergMissing {
            namespace: T::NAMESPACE,
            name: T::NAME,
        }),
        // Fingerprint drifted.
        (Some(actual), true) => Err(BifrostError::SchemaDrift {
            namespace: T::NAMESPACE,
            name: T::NAME,
            expected: T::SCHEMA_FINGERPRINT,
            actual,
        }),
        // Clean first boot.
        (None, false) => match catalog.create_domain_table::<T>().await {
            Ok(()) => {
                catalog
                    .register_domain_control_row::<T>(T::SCHEMA_FINGERPRINT)
                    .await?;
                for idx in T::declared_indexes() {
                    catalog.declare_domain_index(T::NAMESPACE, T::NAME, &idx)?;
                }
                Ok(())
            }
            Err(BifrostError::IcebergAlreadyExists { .. }) => {
                repair_control_from_physical::<T>(catalog).await
            }
            Err(e) => Err(e),
        },
        // SPLIT BRAIN: Iceberg present, control row missing (M-02).
        (None, true) => repair_control_from_physical::<T>(catalog).await,
    }
}

async fn repair_control_from_physical<T: DomainTable>(
    catalog: &Arc<WyrdCatalog>,
) -> Result<(), BifrostError> {
    let physical = catalog
        .iceberg_physical_schema(T::NAMESPACE, T::NAME)
        .await?;
    if catalog.physical_matches_declared::<T>(&physical) {
        catalog
            .register_domain_control_row::<T>(T::SCHEMA_FINGERPRINT)
            .await?;
        catalog.ensure_domain_indexes::<T>()?;
        Ok(())
    } else {
        Err(BifrostError::PhysicalDrift {
            namespace: T::NAMESPACE,
            name: T::NAME,
            expected: T::SCHEMA_FINGERPRINT,
            actual: catalog.fingerprint_of_user_fields(&physical),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use wyrd_spec::vala::{CARD_UID, PRINCIPAL_ID, RUN_ID};

    #[test]
    fn observation_policy_appends_all_three() {
        let cols = CorrelationPolicy::Observation.appended_correlation_columns();
        assert!(cols.contains(&RUN_ID));
        assert!(cols.contains(&CARD_UID));
        assert!(cols.contains(&PRINCIPAL_ID));
    }

    #[test]
    fn code_axis_policy_omits_run_id() {
        let cols = CorrelationPolicy::CodeAxis.appended_correlation_columns();
        assert!(
            !cols.contains(&RUN_ID),
            "CodeAxis must not append universal run_id"
        );
        assert!(cols.contains(&CARD_UID));
        assert!(cols.contains(&PRINCIPAL_ID));
    }

    #[test]
    fn none_policy_appends_nothing() {
        let cols = CorrelationPolicy::None.appended_correlation_columns();
        assert!(cols.is_empty());
    }

    #[test]
    fn observation_table_rejects_reserved_correlation_names() {
        let policy = CorrelationPolicy::Observation;
        for reserved in [RUN_ID, CARD_UID, PRINCIPAL_ID] {
            assert!(
                reject_reserved_domain_fields(&[reserved], policy).is_err(),
                "'{reserved}' must be rejected on Observation table"
            );
        }
    }

    #[test]
    fn none_table_permits_principal_id_and_run_id_as_content() {
        // audit_log has CorrelationPolicy::None and declares principal_id as a content column.
        let result =
            reject_reserved_domain_fields(&["principal_id", "run_id"], CorrelationPolicy::None);
        assert!(
            result.is_ok(),
            "None policy must permit content columns named principal_id/run_id"
        );
    }

    #[test]
    fn code_axis_table_permits_run_id_content_column() {
        // agent_traces has CorrelationPolicy::CodeAxis and declares run_id as its own code-axis column.
        let result = reject_reserved_domain_fields(&["run_id"], CorrelationPolicy::CodeAxis);
        assert!(
            result.is_ok(),
            "CodeAxis policy must permit run_id as a content column"
        );
    }

    #[test]
    fn system_column_always_rejected_regardless_of_policy() {
        for policy in [
            CorrelationPolicy::Observation,
            CorrelationPolicy::CodeAxis,
            CorrelationPolicy::None,
        ] {
            for sys in [
                "data_tenant_id",
                "wyrd_event_time",
                "wyrd_ingested_at",
                "wyrd_batch_id",
            ] {
                assert!(
                    reject_reserved_domain_fields(&[sys], policy).is_err(),
                    "system column '{sys}' must be rejected by all policies"
                );
            }
        }
    }
}
