[package]
name = "wyrd-version"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }

[lib]
doctest = false

[dependencies]
semver = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
schemars = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
