//! OIDC login contracts and URL newtypes.

use std::fmt;
use std::str::FromStr;

use schemars::JsonSchema;
use schemars::r#gen::SchemaGenerator;
use schemars::schema::Schema;
use serde::{Deserialize, Deserializer, Serialize};

use crate::auth::SecretBearer;

/// Absolute URL used by auth contracts.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize)]
#[serde(transparent)]
pub struct Url(String);

impl Url {
    /// Build a validated absolute URL.
    ///
    /// # Errors
    /// Returns [`UrlParseError`] when the value is not an absolute URL with an authority.
    pub fn new(value: impl Into<String>) -> Result<Self, UrlParseError> {
        let value = value.into();
        validate_absolute_url(&value)?;
        Ok(Self(value))
    }

    /// Borrow the URL string.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for Url {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

impl FromStr for Url {
    type Err = UrlParseError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        Self::new(value)
    }
}

impl<'de> Deserialize<'de> for Url {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let value = String::deserialize(deserializer)?;
        Self::new(value).map_err(serde::de::Error::custom)
    }
}

impl JsonSchema for Url {
    fn schema_name() -> String {
        "Url".to_owned()
    }

    fn json_schema(_generator: &mut SchemaGenerator) -> Schema {
        url_schema("Absolute URL with a scheme and authority.")
    }
}

#[cfg(feature = "server")]
impl utoipa::PartialSchema for Url {
    fn schema() -> utoipa::openapi::RefOr<utoipa::openapi::schema::Schema> {
        openapi_url_schema("Absolute URL with a scheme and authority.")
    }
}

#[cfg(feature = "server")]
impl utoipa::ToSchema for Url {}

/// Trusted OIDC issuer URL.
///
/// The constructor validates the URL and removes trailing slashes so issuer
/// comparisons use one canonical string form.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize)]
#[serde(transparent)]
pub struct IssuerUrl(String);

impl IssuerUrl {
    /// Build a normalized issuer URL.
    ///
    /// # Errors
    /// Returns [`UrlParseError`] when the value is not an absolute URL with an authority.
    pub fn new(value: impl Into<String>) -> Result<Self, UrlParseError> {
        let value = value.into();
        validate_absolute_url(&value)?;
        Ok(Self(normalize_issuer(&value)))
    }

    /// Borrow the normalized issuer string.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for IssuerUrl {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

impl FromStr for IssuerUrl {
    type Err = UrlParseError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        Self::new(value)
    }
}

impl<'de> Deserialize<'de> for IssuerUrl {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let value = String::deserialize(deserializer)?;
        Self::new(value).map_err(serde::de::Error::custom)
    }
}

impl JsonSchema for IssuerUrl {
    fn schema_name() -> String {
        "IssuerUrl".to_owned()
    }

    fn json_schema(_generator: &mut SchemaGenerator) -> Schema {
        url_schema("Absolute OIDC issuer URL. Trailing slashes are normalized away.")
    }
}

#[cfg(feature = "server")]
impl utoipa::PartialSchema for IssuerUrl {
    fn schema() -> utoipa::openapi::RefOr<utoipa::openapi::schema::Schema> {
        openapi_url_schema("Absolute OIDC issuer URL. Trailing slashes are normalized away.")
    }
}

#[cfg(feature = "server")]
impl utoipa::ToSchema for IssuerUrl {}

/// `GET /auth/login` response.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
#[serde(deny_unknown_fields)]
pub struct LoginInitResponse {
    /// Authorization URL used as the redirect target.
    pub authorization_url: Url,
    /// Opaque login state echoed for SDK correlation.
    pub state: String,
}

/// `GET /auth/callback` query.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
#[serde(deny_unknown_fields)]
pub struct CallbackQuery {
    /// Authorization code from the identity provider callback.
    pub code: SecretBearer,
    /// Opaque login state generated by Wyrd.
    pub state: String,
}

/// URL validation failure.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error("URL must be absolute and include an authority")]
pub struct UrlParseError;

fn validate_absolute_url(value: &str) -> Result<(), UrlParseError> {
    let parsed = url::Url::parse(value).map_err(|_| UrlParseError)?;
    if parsed.has_host() {
        Ok(())
    } else {
        Err(UrlParseError)
    }
}

fn normalize_issuer(value: &str) -> String {
    value.trim_end_matches('/').to_owned()
}

fn url_schema(description: &'static str) -> Schema {
    serde_json::from_value(serde_json::json!({
        "type": "string",
        "format": "uri",
        "description": description
    }))
    .expect("URL schema is valid JSON Schema")
}

#[cfg(feature = "server")]
fn openapi_url_schema(
    description: &'static str,
) -> utoipa::openapi::RefOr<utoipa::openapi::schema::Schema> {
    use utoipa::openapi::schema::{ObjectBuilder, Schema, SchemaFormat, Type};

    utoipa::openapi::RefOr::T(Schema::Object(
        ObjectBuilder::new()
            .schema_type(Type::String)
            .format(Some(SchemaFormat::Custom("uri".to_owned())))
            .description(Some(description))
            .build(),
    ))
}

#[cfg(test)]
mod tests {
    use super::{IssuerUrl, Url};

    #[test]
    fn issuer_url_normalizes_trailing_slash() {
        let issuer =
            IssuerUrl::new("https://idp.example.com/realms/acme/").expect("issuer URL is valid");

        assert_eq!(issuer.as_str(), "https://idp.example.com/realms/acme");
    }

    #[test]
    fn issuer_url_rejects_non_url_input() {
        assert!(IssuerUrl::new("not a url").is_err());
        assert!(IssuerUrl::new("/relative/path").is_err());
    }

    #[test]
    fn url_rejects_non_url_input() {
        assert!(Url::new("not a url").is_err());
        assert!(Url::new("urn:example:login").is_err());
    }
}
