//! Auth token request and response contracts.

use chrono::{DateTime, Utc};
use schemars::r#gen::SchemaGenerator;
use schemars::schema::{InstanceType, Schema, SchemaObject, StringValidation};
use serde::{Deserialize, Serialize};

use crate::auth::SecretBearer;
use crate::ids::TenantSlug;

/// Body of `POST /auth/token`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
#[serde(tag = "grant_type", rename_all = "snake_case", deny_unknown_fields)]
pub enum TokenRequest {
    /// Wyrd-native API key exchange.
    WyrdApiKey {
        /// API key from the deployment secret store.
        api_key: SecretBearer,
    },
    /// RFC 8693 token exchange: the actor acts on behalf of the subject.
    ///
    /// The issued token names the subject as its top-level principal, the actor
    /// as the outermost `act` layer, and `audience` as its `aud`. Its authority
    /// is the intersection of both parties' permissions.
    #[serde(rename = "urn:ietf:params:oauth:grant-type:token-exchange")]
    TokenExchange {
        /// Wyrd access token of the party being acted for (the subject).
        subject_token: SecretBearer,
        /// Type of `subject_token`.
        subject_token_type: ExchangeTokenType,
        /// Wyrd access token of the party doing the work (the actor).
        actor_token: SecretBearer,
        /// Type of `actor_token`.
        actor_token_type: ExchangeTokenType,
        /// Wyrd resource the delegated token is issued for.
        audience: TokenAudience,
    },
    /// Human OIDC login completion.
    ///
    /// The public completion carries only callback material. The server loads
    /// `code_verifier`, `nonce`, `redirect_uri`, issuer, and tenant from the
    /// login state keyed by `state`.
    AuthorizationCode {
        /// Authorization code from the identity provider callback.
        code: SecretBearer,
        /// Single-use login state key generated by Wyrd.
        #[schemars(schema_with = "state_key_schema")]
        state: String,
    },
    /// Workload identity: platform-attested OIDC assertion.
    #[serde(rename = "urn:ietf:params:oauth:grant-type:jwt-bearer")]
    JwtBearer {
        /// Kubernetes service-account token, SPIFFE JWT-SVID, or cloud token.
        assertion: SecretBearer,
        /// Tenant selector fallback when the request host does not carry tenant.
        tenant: Option<TenantSlug>,
    },
    /// Wyrd refresh-token rotation.
    RefreshToken {
        /// Signed Wyrd refresh token.
        refresh_token: SecretBearer,
    },
}

/// Supported RFC 8693 token type for a subject or actor token.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
pub enum ExchangeTokenType {
    /// OAuth access token.
    #[serde(rename = "urn:ietf:params:oauth:token-type:access_token")]
    AccessToken,
}

/// Audience (`aud`) of a Wyrd tenant access token.
///
/// Every directly issued token is [`Self::Wyrd`] and is accepted on every
/// tenant surface. A [`Self::Bifrost`] token is accepted only on the Bifrost
/// surfaces, so a token delegated for Bifrost cannot be replayed elsewhere.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
#[serde(rename_all = "snake_case")]
pub enum TokenAudience {
    /// Every Wyrd tenant surface.
    Wyrd,
    /// Only the Bifrost ingest and query surfaces.
    Bifrost,
}

impl TokenAudience {
    /// The canonical `aud` claim value.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Wyrd => "wyrd",
            Self::Bifrost => "bifrost",
        }
    }
}

/// Response from `POST /auth/token`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
#[serde(deny_unknown_fields)]
pub struct TokenResponse {
    /// Signed Wyrd access token.
    pub access_token: SecretBearer,
    /// Refresh token. Present only for grants that issue one: human OIDC login
    /// (`authorization_code`), API-key exchange (`wyrd_api_key`), and refresh
    /// rotation (`refresh_token`). Absent for the workload `jwt-bearer` and
    /// `token-exchange` (delegation) grants, whose clients re-present their
    /// durable credential to obtain a fresh access token instead of holding a
    /// long-lived refresh secret.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refresh_token: Option<SecretBearer>,
    /// Token type.
    pub token_type: TokenType,
    /// Access-token expiry timestamp.
    pub expires_at: DateTime<Utc>,
}

/// Bearer token marker.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
#[serde(rename_all = "PascalCase")]
pub enum TokenType {
    /// Bearer token.
    Bearer,
}

fn state_key_schema(_gen: &mut SchemaGenerator) -> Schema {
    Schema::Object(SchemaObject {
        instance_type: Some(InstanceType::String.into()),
        string: Some(Box::new(StringValidation {
            min_length: Some(1),
            max_length: Some(512),
            pattern: None,
        })),
        ..Default::default()
    })
}

#[cfg(test)]
mod tests {
    use super::{ExchangeTokenType, TokenAudience, TokenRequest, TokenResponse, TokenType};
    use crate::auth::SecretBearer;
    use chrono::Utc;

    #[test]
    fn token_response_has_no_card_ref_wire_field() {
        let response = TokenResponse {
            access_token: SecretBearer::new("access".to_owned()),
            refresh_token: Some(SecretBearer::new("refresh".to_owned())),
            token_type: TokenType::Bearer,
            expires_at: Utc::now(),
        };

        let json = serde_json::to_value(response).expect("serializes");

        assert!(json.get("card_ref").is_none());
    }

    #[test]
    fn token_exchange_uses_rfc_8693_grant_type() {
        let request = exchange_request();

        let json = serde_json::to_value(request).expect("serializes");

        assert_eq!(
            json["grant_type"],
            "urn:ietf:params:oauth:grant-type:token-exchange"
        );
    }

    #[test]
    fn serde_grant_type_discriminator() {
        let api_key_request = TokenRequest::WyrdApiKey {
            api_key: SecretBearer::new("key".to_owned()),
        };
        let exchange_request = exchange_request();
        let authorization_code_request = TokenRequest::AuthorizationCode {
            code: SecretBearer::new("code".to_owned()),
            state: "state-123".to_owned(),
        };
        let jwt_bearer_request = TokenRequest::JwtBearer {
            assertion: SecretBearer::new("assertion".to_owned()),
            tenant: Some(crate::ids::TenantSlug::new("acme").expect("static slug is valid")),
        };
        let refresh_request = TokenRequest::RefreshToken {
            refresh_token: SecretBearer::new("refresh".to_owned()),
        };

        let api_key_json = serde_json::to_value(&api_key_request).expect("serializes");
        let exchange_json = serde_json::to_value(&exchange_request).expect("serializes");
        let authorization_code_json =
            serde_json::to_value(&authorization_code_request).expect("serializes");
        let jwt_bearer_json = serde_json::to_value(&jwt_bearer_request).expect("serializes");
        let refresh_json = serde_json::to_value(&refresh_request).expect("serializes");

        assert_eq!(api_key_json["grant_type"], "wyrd_api_key");
        assert_eq!(
            exchange_json["grant_type"],
            "urn:ietf:params:oauth:grant-type:token-exchange"
        );
        assert_eq!(authorization_code_json["grant_type"], "authorization_code");
        assert_eq!(
            jwt_bearer_json["grant_type"],
            "urn:ietf:params:oauth:grant-type:jwt-bearer"
        );
        assert_eq!(refresh_json["grant_type"], "refresh_token");
        assert_eq!(
            serde_json::from_value::<TokenRequest>(api_key_json).expect("deserializes"),
            api_key_request
        );
        assert_eq!(
            serde_json::from_value::<TokenRequest>(exchange_json).expect("deserializes"),
            exchange_request
        );
        assert_eq!(
            serde_json::from_value::<TokenRequest>(authorization_code_json).expect("deserializes"),
            authorization_code_request
        );
        assert_eq!(
            serde_json::from_value::<TokenRequest>(jwt_bearer_json).expect("deserializes"),
            jwt_bearer_request
        );
        assert_eq!(
            serde_json::from_value::<TokenRequest>(refresh_json).expect("deserializes"),
            refresh_request
        );
    }

    #[test]
    fn authorization_code_public_shape_is_code_and_state_only() {
        let request = serde_json::json!({
            "grant_type": "authorization_code",
            "code": "code",
            "state": "state-123"
        });

        let parsed = serde_json::from_value::<TokenRequest>(request).expect("deserializes");

        assert_eq!(
            parsed,
            TokenRequest::AuthorizationCode {
                code: SecretBearer::new("code".to_owned()),
                state: "state-123".to_owned(),
            }
        );

        let with_code_verifier = serde_json::json!({
            "grant_type": "authorization_code",
            "code": "code",
            "state": "state-123",
            "code_verifier": "server-owned"
        });
        let with_redirect_uri = serde_json::json!({
            "grant_type": "authorization_code",
            "code": "code",
            "state": "state-123",
            "redirect_uri": "https://app.example.com/callback"
        });

        assert!(serde_json::from_value::<TokenRequest>(with_code_verifier).is_err());
        assert!(serde_json::from_value::<TokenRequest>(with_redirect_uri).is_err());
    }

    #[test]
    fn authorization_code_schema_shape_is_code_and_state_only() {
        let schema = schemars::schema_for!(TokenRequest);
        let value = serde_json::to_value(schema.schema).expect("schema serializes");
        let variants = value["oneOf"]
            .as_array()
            .expect("token request has variants");
        let authorization_code = variants
            .iter()
            .find(|variant| {
                variant["properties"]["grant_type"]["enum"]
                    .as_array()
                    .and_then(|values| values.first())
                    .and_then(serde_json::Value::as_str)
                    == Some("authorization_code")
            })
            .expect("authorization_code variant exists");
        let properties = authorization_code["properties"]
            .as_object()
            .expect("variant has properties");
        let mut property_names = properties.keys().map(String::as_str).collect::<Vec<_>>();
        property_names.sort_unstable();

        assert_eq!(property_names, ["code", "grant_type", "state"]);
        assert_eq!(
            authorization_code["required"],
            serde_json::json!(["code", "grant_type", "state"])
        );
        assert_eq!(authorization_code["additionalProperties"], false);
    }

    #[test]
    fn new_grant_variants_reject_unknown_fields() {
        let authorization_code = serde_json::json!({
            "grant_type": "authorization_code",
            "code": "code",
            "state": "state-123",
            "extra": true
        });
        let jwt_bearer = serde_json::json!({
            "grant_type": "urn:ietf:params:oauth:grant-type:jwt-bearer",
            "assertion": "assertion",
            "tenant": "acme",
            "extra": true
        });
        let refresh_token = serde_json::json!({
            "grant_type": "refresh_token",
            "refresh_token": "refresh",
            "extra": true
        });

        assert!(serde_json::from_value::<TokenRequest>(authorization_code).is_err());
        assert!(serde_json::from_value::<TokenRequest>(jwt_bearer).is_err());
        assert!(serde_json::from_value::<TokenRequest>(refresh_token).is_err());
    }

    #[test]
    fn new_secret_grants_redact_debug() {
        let request = TokenRequest::JwtBearer {
            assertion: SecretBearer::new("top-secret-assertion".to_owned()),
            tenant: None,
        };

        let debug = format!("{request:?}");

        assert!(debug.contains("REDACTED"));
        assert!(!debug.contains("top-secret-assertion"));
    }

    #[test]
    fn jwt_bearer_without_tenant_roundtrips() {
        let request = TokenRequest::JwtBearer {
            assertion: SecretBearer::new("assertion".to_owned()),
            tenant: None,
        };
        let value = serde_json::to_value(&request).unwrap();
        assert_eq!(value["tenant"], serde_json::Value::Null);
        assert_eq!(
            serde_json::from_value::<TokenRequest>(value).unwrap(),
            request
        );
    }

    #[test]
    fn token_response_roundtrips() {
        let response = TokenResponse {
            access_token: SecretBearer::new("access".to_owned()),
            refresh_token: Some(SecretBearer::new("refresh".to_owned())),
            token_type: TokenType::Bearer,
            expires_at: Utc::now(),
        };
        let value = serde_json::to_value(&response).unwrap();
        assert_eq!(value["token_type"], "Bearer");
        assert!(value["expires_at"].as_str().is_some());
        assert_eq!(
            serde_json::from_value::<TokenResponse>(value).unwrap(),
            response
        );
    }

    #[test]
    fn token_response_without_refresh_omits_field_and_roundtrips() {
        let response = TokenResponse {
            access_token: SecretBearer::new("access".to_owned()),
            refresh_token: None,
            token_type: TokenType::Bearer,
            expires_at: Utc::now(),
        };
        let value = serde_json::to_value(&response).unwrap();
        assert!(
            value.get("refresh_token").is_none(),
            "a grant that issues no refresh token must omit the wire field"
        );
        assert_eq!(
            serde_json::from_value::<TokenResponse>(value).unwrap(),
            response
        );
    }

    /// Build one Bifrost-audience exchange with placeholder bearers.
    fn exchange_request() -> TokenRequest {
        TokenRequest::TokenExchange {
            subject_token: SecretBearer::new("subject".to_owned()),
            subject_token_type: ExchangeTokenType::AccessToken,
            actor_token: SecretBearer::new("actor".to_owned()),
            actor_token_type: ExchangeTokenType::AccessToken,
            audience: TokenAudience::Bifrost,
        }
    }

    /// The exchange wire carries RFC 8693 subject/actor fields and a closed
    /// audience set; an unsupported audience or a stale `requested_subject`
    /// field is rejected at deserialization.
    #[test]
    fn token_exchange_wire_is_rfc_8693_subject_actor_audience() {
        let json = serde_json::to_value(exchange_request()).expect("serializes");
        let token_type = "urn:ietf:params:oauth:token-type:access_token";
        assert_eq!(json["subject_token_type"], token_type);
        assert_eq!(json["actor_token_type"], token_type);
        assert_eq!(json["audience"], "bifrost");

        let mut unsupported = json.clone();
        unsupported["audience"] = serde_json::json!("storage");
        assert!(serde_json::from_value::<TokenRequest>(unsupported).is_err());

        let mut stale = json.clone();
        stale["requested_subject"] = serde_json::json!({"kind": "principal_id"});
        assert!(serde_json::from_value::<TokenRequest>(stale).is_err());

        let mut missing_actor = json;
        missing_actor
            .as_object_mut()
            .expect("request is an object")
            .remove("actor_token");
        assert!(serde_json::from_value::<TokenRequest>(missing_actor).is_err());
    }
}
