from collections.abc import Mapping
from typing import Any, ClassVar, Protocol, runtime_checkable

class Role:
    System: ClassVar[Role]
    User: ClassVar[Role]
    Assistant: ClassVar[Role]
    Tool: ClassVar[Role]
    def __str__(self) -> str: ...

class SessionTurn:
    def __init__(self, *, role: Role | str, content: str, call_id: str | None = ...) -> None: ...
    @property
    def role(self) -> str: ...
    @property
    def content(self) -> str: ...
    @property
    def call_id(self) -> str | None: ...
    def model_dump(self) -> dict[str, Any]: ...
    def model_dump_json(self) -> str: ...
    @staticmethod
    def model_validate(value: SessionTurn | Mapping[str, Any]) -> SessionTurn: ...
    @staticmethod
    def model_validate_json(data: str) -> SessionTurn: ...

@runtime_checkable
class SessionMemory(Protocol):
    def recent(self, session_id: str, limit: int) -> list[SessionTurn | dict[str, Any]]: ...
    def append(self, session_id: str, turn: SessionTurn) -> None: ...

class NoSession:
    def recent(self, session_id: str, limit: int) -> list[SessionTurn]: ...
    def append(self, session_id: str, turn: SessionTurn) -> None: ...

__all__ = [
    "NoSession",
    "Role",
    "SessionMemory",
    "SessionTurn",
]
