/* auto-generated by NAPI-RS */
/* eslint-disable */
/** In-process server handle used only by TypeScript integration tests. */
export declare class NativeWyrdTestServer {
  /** Returns the bound HTTP base URL. */
  get baseUrl(): string
  /** Returns the integration-only admin bearer. */
  get token(): string
  /** Returns the registered table used by the TypeScript Oracle journey. */
  get tableFqn(): string
  /**
   * Seed rows through the real gRPC ingest and Scribe flush paths.
   *
   * # Errors
   *
   * Returns a napi error when the harness is closed or registration,
   * encoding, ingest, or flushing fails.
   */
  seedBifrostRows(table: string, rows: Array<number>): Array<number>
  /**
   * Mint an authenticated token without `bifrost_query:read`.
   *
   * # Errors
   *
   * Returns a napi error when the harness is closed or token issuance fails.
   */
  queryDeniedToken(): string
  /**
   * Return the durable read-decision audit count for the fixture tenant.
   *
   * # Errors
   *
   * Returns a napi error when the harness is closed or the audit query fails.
   */
  bifrostReadDecisionCount(): number
  /** Truncate the next query after its schema frame. */
  failNextQueryAfterSchema(): void
  /** Truncate the next query after its first batch frame. */
  failNextQueryAfterBatch(): void
  /**
   * Gracefully shuts down the in-process server once.
   *
   * # Errors
   *
   * Returns a napi error when the Rust harness cannot complete shutdown.
   */
  shutdown(): void
}

/**
 * Starts a real bound Wyrd test server and mints an admin access token.
 *
 * # Errors
 *
 * Returns a napi error when server startup, service bootstrap, API-key
 * exchange, or URL discovery fails.
 */
export declare function startTestServer(): NativeWyrdTestServer
