/* auto-generated by NAPI-RS */
/* eslint-disable */
/** In-process server handle used only by TypeScript integration tests. */
export declare class NativeWyrdTestServer {
  /** Returns the bound HTTP base URL. */
  get baseUrl(): string
  /** Returns the integration-only admin bearer. */
  get token(): string
  /** Returns the registered table used by the TypeScript Oracle journey. */
  get tableFqn(): string
  /**
   * Gracefully shuts down the in-process server once.
   *
   * # Errors
   *
   * Returns a napi error when the Rust harness cannot complete shutdown.
   */
  shutdown(): void
}

/**
 * Starts a real bound Wyrd test server and mints an admin access token.
 *
 * # Errors
 *
 * Returns a napi error when server startup, service bootstrap, API-key
 * exchange, or URL discovery fails.
 */
export declare function startTestServer(): NativeWyrdTestServer
