[package]
name = "wyrd-dev-fixtures"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
[features]
default = []
dev = ["dep:postgresql_embedded"]

[dependencies]
postgresql_embedded = { workspace = true, optional = true }
thiserror.workspace = true
