[package]
name = "wyrd-sql"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }

[features]
embedded-postgres = ["dep:pg-embed", "dep:rand", "dep:urlencoding"]
test-e2e = []

[dependencies]
chrono = { workspace = true }
secrecy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
ulid = { workspace = true }
uuid = { workspace = true, features = ["v7"] }
wyrd-runtime = { workspace = true }
wyrd-semver = { workspace = true }
wyrd-spec = { workspace = true }

[dependencies.pg-embed]
workspace = true
optional = true

[dependencies.rand]
workspace = true
optional = true

[dependencies.urlencoding]
workspace = true
optional = true

[dev-dependencies]
paste = { workspace = true }
sqlx = { workspace = true, features = ["postgres", "uuid", "json"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
