[package]
name = "wyrd-sql"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }

[features]
embedded-postgres = ["dep:pg-embed", "dep:rand", "dep:urlencoding"]

[dependencies]
chrono = { workspace = true }
secrecy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
wyrd-runtime = { workspace = true }
wyrd-semver = { workspace = true }
wyrd-spec = { workspace = true }

[dependencies.pg-embed]
workspace = true
optional = true

[dependencies.rand]
workspace = true
optional = true

[dependencies.urlencoding]
workspace = true
optional = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
wyrd-semver = { workspace = true }
