/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * The one Bifrost client: query any authorized table, write to the active one.
 *
 * Mirrors the Python binding: both are thin conversions over the one
 * [`Bifrost`], so batching, backpressure, registration, and the
 * query contract have exactly one owner.
 */
export declare class NativeBifrost {
  /**
   * Creates the active table, answering `created` or `already_exists`.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * no-active-table, fingerprint-conflict, and transport failures are
   * returned in [`NativeLifecycleResult`].
   */
  register(): Promise<NativeLifecycleResult>
  /**
   * Binds `table` as the write target, returning the previous binding.
   *
   * The previous table's producer stays pooled, so its buffered rows still
   * flush; a swap loses nothing.
   *
   * # Errors
   *
   * Returns a napi error when the config is not one serialized `TableConfig`
   * or the previous binding cannot be projected.
   */
  useTable(table: NativeTableConfig): NativeTableConfig | null
  /**
   * Binds an already-registered table by name, describing it first.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * not-found, authorization, and transport failures are returned in
   * [`NativeLifecycleResult`].
   */
  useTableByName(table: string): Promise<NativeLifecycleResult>
  /**
   * The active write binding, if any.
   *
   * # Errors
   *
   * Returns a napi error when the binding cannot be projected.
   */
  get table(): NativeTableConfig | null
  /**
   * Enqueues one JSON row into the active table.
   *
   * Stays synchronous because the producer push is a bounded, non-blocking
   * queue operation; only the drains need a worker thread. A saturated queue
   * refuses here rather than dropping silently.
   *
   * # Errors
   *
   * Returns a napi error for an invalid card reference; no-active-table and
   * queue-full refusals are returned in [`NativeLifecycleResult`].
   */
  insert(row: string, cardRef?: string | undefined | null, runId?: string | undefined | null): NativeLifecycleResult
  /**
   * Writes one already-built Arrow batch to `table` and awaits durability.
   *
   * The batch crosses as a single-batch Arrow IPC stream, the same framing
   * [`NativeTableConfig::schema_ipc`] uses in the other direction, so the
   * field metadata a canonical table declares survives the boundary. Unlike
   * [`NativeBifrost::insert`] nothing is buffered, so no flush follows.
   *
   * # Errors
   *
   * Returns a napi error when the bytes are not one single-batch Arrow IPC
   * stream; server and envelope refusals are returned in
   * [`NativeLifecycleResult`].
   */
  writeBatch(table: string, batchIpc: Buffer): Promise<NativeLifecycleResult>
  /**
   * Flushes every pooled producer and awaits each durable acknowledgement.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * producer and sink failures are returned in [`NativeLifecycleResult`].
   */
  flush(): Promise<NativeLifecycleResult>
  /**
   * Drains every producer and stops its background task.
   *
   * # Errors
   *
   * As [`NativeBifrost::flush`].
   */
  shutdown(): Promise<NativeLifecycleResult>
  /** Number of distinct table producers currently pooled. */
  get producerCount(): number
  /**
   * Starts one terminal-safe query through the Rust SDK owner.
   *
   * Expected request, Gate, authentication, and transport failures are
   * returned in [`NativeQueryStart`] so JavaScript never has to parse an
   * exception message to recover the public Wyrd error contract.
   *
   * # Errors
   *
   * Returns a napi error only when napi cannot project the structured
   * startup result itself.
   */
  query(request: NativeQueryRequest): Promise<NativeQueryStart>
  /**
   * Lists active queries for the authenticated tenant.
   *
   * Cancelling the JavaScript promise abandons the pending HTTP request and
   * does not create client-owned lifecycle state.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * Wyrd control failures are returned in [`NativeLifecycleResult`].
   */
  running(): Promise<NativeLifecycleResult>
  /**
   * Gets one active query by canonical request ID.
   *
   * Cancelling the JavaScript promise abandons the pending HTTP request and
   * does not alter the active query.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * validation and Wyrd control failures are returned in [`NativeLifecycleResult`].
   */
  status(requestId: string): Promise<NativeLifecycleResult>
  /**
   * Requests server-side cancellation without closing a local stream.
   *
   * Once the server accepts cancellation, abandoning the JavaScript promise
   * does not reverse the server-side lifecycle transition.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * validation and Wyrd control failures are returned in [`NativeLifecycleResult`].
   */
  cancel(requestId: string): Promise<NativeLifecycleResult>
  /**
   * Describes one registered table's stored physical schema.
   *
   * The description is the server's own projection: the user fields a caller
   * declares, the correlation inputs the write path resolves, the managed
   * candidates it may supply, and a canonical table's physical fingerprint.
   * JavaScript builds its insertable schema from this rather than from a
   * local copy of the table contract.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * Wyrd control failures are returned in [`NativeLifecycleResult`].
   */
  describeTable(namespace: string, name: string): Promise<NativeLifecycleResult>
}

/** Native query stream that retains Rust terminal validation and emits raw IPC. */
export declare class NativeBifrostQueryStream {
  /** Returns the canonical server lifecycle request identity. */
  get requestId(): string
  /**
   * Returns one Arrow IPC batch or the final validated terminal.
   *
   * # Errors
   *
   * Returns a napi error carrying the stable Wyrd code for failed,
   * incomplete, malformed, or transport-terminated streams.
   */
  next(): Promise<NativeQueryStep>
  /** Drops the response stream so Rust transport cancellation propagates. */
  close(): Promise<void>
  /**
   * Returns the result's authoritative schema as a schema-only IPC stream.
   *
   * Retained when the stream completes, so a query that produced no batch
   * still carries the server's schema and JavaScript never has to infer one
   * from the batches it happened to receive.
   *
   * # Errors
   *
   * Returns a napi error when the retaining lock is poisoned.
   */
  get schemaIpc(): Buffer | null
  /**
   * Returns serialized terminal metadata after validated completion.
   *
   * # Errors
   *
   * Returns a napi error when the terminal lock is poisoned.
   */
  get terminalJson(): string | null
}

/** Tenant-scoped Card registry handle over the shared `wyrd_client` Cards. */
export declare class NativeCards {
  /**
   * Loads one Card tree from disk and registers it as a composite.
   *
   * # Errors
   *
   * Returns a napi error only when the receipt cannot be serialized; load,
   * validation, and registry failures are returned in the result.
   */
  registerFromPath(path: string): Promise<NativeLifecycleResult>
  /**
   * Fetches one Card envelope by exact reference.
   *
   * # Errors
   *
   * Returns a napi error only when the envelope cannot be serialized; an
   * invalid reference or registry failure is returned in the result.
   */
  get(cardRef: string): Promise<NativeLifecycleResult>
  /**
   * Lists metadata-only Card summaries for one serialized list request.
   *
   * # Errors
   *
   * Returns a napi error only when the page cannot be serialized; a
   * malformed request or registry failure is returned in the result.
   */
  list(requestJson: string): Promise<NativeLifecycleResult>
  /**
   * Hydrates one Card graph into a published local bundle.
   *
   * `metadata_only` skips artifact payload downloads. A failed hydration
   * never publishes a partial bundle.
   *
   * # Errors
   *
   * Returns a napi error only when the summary cannot be serialized; graph,
   * destination, and transfer failures are returned in the result.
   */
  hydrate(cardRef: string, destination: string, metadataOnly: boolean): Promise<NativeLifecycleResult>
  /**
   * Soft-deletes one Card by exact reference.
   *
   * # Errors
   *
   * Returns a napi error only when the result cannot be projected; an
   * invalid reference or registry failure is returned in the result.
   */
  delete(cardRef: string): Promise<NativeLifecycleResult>
}

/** Structured result of starting a native terminal-safe query. */
export declare class NativeQueryStart {
  /** Moves the Rust-owned stream out after a successful startup. */
  takeStream(): NativeBifrostQueryStream | null
  /** Returns the stable SDK error code when startup failed. */
  get errorCode(): string | null
  /** Returns the HTTP-equivalent status when startup failed. */
  get errorStatus(): number | null
  /** Returns the stable title when startup failed. */
  get errorTitle(): string | null
  /** Returns the scrubbed SDK error detail when startup failed. */
  get errorDetail(): string | null
  /** Returns operator-facing remediation when startup failed. */
  get errorRemediation(): string | null
  /** Returns serialized JSON-safe structured details when startup failed. */
  get errorDetailsJson(): string | null
}

/** Node-facing handle to one authenticated [`WyrdClient`]. */
export declare class NativeWyrdClient {
  /**
   * Returns a client that acts for the holder of `subject_token`.
   *
   * This client's credential is the actor. The first exchange runs here so a
   * refusal is returned at the call site; the returned client re-exchanges
   * in Rust before expiry. An `audience` other than `wyrd` or `bifrost` is a
   * `WYRD_SPEC_400_VALIDATION` result.
   */
  onBehalfOf(subjectToken: string, audience: string): Promise<NativeWyrdClientResult>
}

/**
 * Offline hydrated-bundle view over the shared `wyrd_client` `WyrdState`.
 *
 * The open result is retained so an invalid bundle surfaces its catalog error
 * on the first read instead of as an untyped constructor failure.
 */
export declare class NativeWyrdState {
  /**
   * Returns the exact root Card reference.
   *
   * # Errors
   *
   * Returns a napi error only when the reference cannot be serialized.
   */
  rootRef(): NativeLifecycleResult
  /**
   * Returns every persisted alias in stable sorted order.
   *
   * # Errors
   *
   * Returns a napi error only when the aliases cannot be serialized.
   */
  aliases(): NativeLifecycleResult
  /**
   * Resolves an alias to its stored Card envelope.
   *
   * # Errors
   *
   * Returns a napi error only when the envelope cannot be serialized.
   */
  card(alias: string): NativeLifecycleResult
  /**
   * Resolves an alias to its exact Card reference.
   *
   * # Errors
   *
   * Returns a napi error only when the reference cannot be serialized.
   */
  cardRef(alias: string): NativeLifecycleResult
  /**
   * Returns the verified local artifacts for an alias.
   *
   * # Errors
   *
   * Returns a napi error only when the artifact list cannot be serialized.
   */
  artifacts(alias: string): NativeLifecycleResult
}

/**
 * Connects one Bifrost client, optionally already bound to a write target.
 *
 * A free function rather than a constructor because connecting is asynchronous
 * and a napi constructor cannot be. Every transport argument is optional and
 * falls through the existing resolution chain exactly once when omitted.
 *
 * # Errors
 *
 * Returns a napi error only when the supplied table config is not one
 * serialized `TableConfig`; credential and ingest-dial failures are returned
 * as catalog metadata.
 */
export declare function connectBifrost(table?: NativeTableConfig | undefined | null, serverUrl?: string | undefined | null, credential?: string | undefined | null, grpcUrl?: string | undefined | null): Promise<NativeBifrostConnection>

/**
 * Builds one Card registry handle without performing IO.
 *
 * Omitted arguments resolve through the same shared client configuration
 * chain as `connectBifrost`, so both capabilities authenticate identically.
 * Credential and configuration failures are returned as catalog metadata.
 */
export declare function connectCards(serverUrl?: string | undefined | null, credential?: string | undefined | null): NativeCardsConnection

/**
 * Builds one client without performing IO.
 *
 * Omitted arguments resolve through `client_from_options`: the environment,
 * then `~/.config/wyrd/credentials.toml`. Failures are returned as catalog
 * metadata.
 */
export declare function connectWyrdClient(serverUrl?: string | undefined | null, credential?: string | undefined | null, grpcUrl?: string | undefined | null): NativeWyrdClientResult

/**
 * Fetches an already-registered table's config by name.
 *
 * Every transport argument is optional and resolves through the same chain the
 * client constructor uses when omitted.
 *
 * # Errors
 *
 * Returns a napi error only when the described config cannot be encoded;
 * credential, transport, and server refusals are returned as catalog metadata.
 */
export declare function describeTableConfig(table: string, serverUrl?: string | undefined | null, credential?: string | undefined | null, grpcUrl?: string | undefined | null): Promise<NativeTableConfigResult>

/** Closed result of connecting one Bifrost client: a handle or a catalog error. */
export interface NativeBifrostConnection {
  /** Connected client when construction succeeded. */
  bifrost?: NativeBifrost
  /** Catalog failure when construction failed. */
  error?: NativeWyrdError
}

/** Closed result of building one Card registry handle: a handle or a catalog error. */
export interface NativeCardsConnection {
  /** Registry handle when construction succeeded. */
  cards?: NativeCards
  /** Catalog failure when no credential resolves or the client cannot be built. */
  error?: NativeWyrdError
}

/** Structured native result for one live-query lifecycle control. */
export interface NativeLifecycleResult {
  /** Canonical JSON payload when the control succeeded. */
  valueJson?: string
  /** Stable SDK error code when the control failed. */
  errorCode?: string
  /** HTTP-equivalent status when the control failed. */
  errorStatus?: number
  /** Stable title when the control failed. */
  errorTitle?: string
  /** Scrubbed detail when the control failed. */
  errorDetail?: string
  /** Operator-facing remediation when the control failed. */
  errorRemediation?: string
  /** Serialized JSON-safe structured details when the control failed. */
  errorDetailsJson?: string
}

/** JavaScript query request projected onto the pure Wyrd contract. */
export interface NativeQueryRequest {
  /** SELECT-only SQL text. */
  sql: string
  /** `published_only` or `fused`. */
  visibility: string
  /** `strict` or `allow_degraded`. */
  freshness: string
  /**
   * Optional query deadline in milliseconds, valid in `1..=u32::MAX`.
   *
   * Accepted as a JavaScript number so every out-of-range, fractional, or
   * non-finite value reaches the structured startup failure instead of a
   * napi binding error.
   */
  deadlineMs?: number
}

/** One raw native iterator step consumed by the TypeScript Arrow facade. */
export interface NativeQueryStep {
  /** Complete Arrow IPC stream containing exactly one record batch. */
  ipc?: Buffer
  /** Serialized validated terminal, present only on the final step. */
  terminalJson?: string
  /** Stable SDK error code for a failed native step. */
  errorCode?: string
  /** HTTP-equivalent status for a failed native step. */
  errorStatus?: number
  /** Stable title for a failed native step. */
  errorTitle?: string
  /** Scrubbed SDK error detail for a failed native step. */
  errorDetail?: string
  /** Operator-facing remediation for a failed native step. */
  errorRemediation?: string
  /** Serialized JSON-safe structured details for a failed native step. */
  errorDetailsJson?: string
}

/**
 * One Bifrost table as it crosses the Node boundary.
 *
 * `configJson` is the authoritative value — the whole `TableConfig`, including
 * the server identity a described table already carries — so a config that
 * goes out to JavaScript and comes back is the same config. The other fields
 * are read-only projections JavaScript would otherwise have to derive, and
 * deriving them would mean reimplementing the schema mapping this SDK exists
 * to keep in one place.
 */
export interface NativeTableConfig {
  /** The serialized `TableConfig`; the only field read back natively. */
  configJson: string
  /** `namespace.name`. */
  fqn: string
  /** The declared user columns as one schema-only Arrow IPC stream. */
  schemaIpc: Buffer
  /** Serialized `{table_uid, fingerprint}` once the server has minted it. */
  resolvedJson?: string
}

/** Closed result of describing one table: its config or a catalog error. */
export interface NativeTableConfigResult {
  /** Described table config when the server answered. */
  config?: NativeTableConfig
  /** Catalog failure when description failed. */
  error?: NativeWyrdError
}

/** Closed result of building or delegating one client: a handle or a catalog error. */
export interface NativeWyrdClientResult {
  /** Client when construction or the exchange succeeded. */
  client?: NativeWyrdClient
  /** Catalog failure otherwise. */
  error?: NativeWyrdError
}

/**
 * Catalog metadata for one failed native construction or description.
 *
 * Field names match the other native results so the TypeScript facade builds
 * its public `WyrdError` through the same projection.
 */
export interface NativeWyrdError {
  /** Stable catalog code. */
  errorCode: string
  /** HTTP-equivalent status. */
  errorStatus: number
  /** Stable catalog title. */
  errorTitle: string
  /** Scrubbed catalog detail. */
  errorDetail: string
  /** Operator-facing remediation. */
  errorRemediation: string
  /** Serialized JSON-safe structured details, when present. */
  errorDetailsJson?: string
}

/** Loads and validates one hydrated bundle without contacting Wyrd. */
export declare function openWyrdState(path: string): NativeWyrdState

/**
 * Builds one table config from a JSON Schema document.
 *
 * This is the Zod (`z.toJSONSchema()`) door; the mapping is the same
 * `wyrd-queue` owner every language uses, so one model declares the same
 * columns from any SDK.
 *
 * # Errors
 *
 * Returns a napi error when the table is not `namespace.name`, the document is
 * not one mappable JSON Schema, a declared column is server-owned, or the
 * layout is not one physical-layout declaration.
 */
export declare function tableConfigFromJsonSchema(table: string, schemaJson: string, layoutJson?: string | undefined | null): NativeTableConfig
