/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * The one Bifrost client: query any authorized table, write to the active one.
 *
 * Mirrors the Python binding: both are thin conversions over the one
 * [`Bifrost`], so batching, backpressure, registration, and the
 * query contract have exactly one owner.
 */
export declare class NativeBifrost {
  /**
   * Creates the active table, answering `created` or `already_exists`.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * no-active-table, fingerprint-conflict, and transport failures are
   * returned in [`NativeLifecycleResult`].
   */
  register(): Promise<NativeLifecycleResult>
  /**
   * Binds `table` as the write target, returning the previous binding.
   *
   * The previous table's producer stays pooled, so its buffered rows still
   * flush; a swap loses nothing.
   *
   * # Errors
   *
   * Returns a napi error when the config is not one serialized `TableConfig`
   * or the previous binding cannot be projected.
   */
  useTable(table: NativeTableConfig): NativeTableConfig | null
  /**
   * Binds an already-registered table by name, describing it first.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * not-found, authorization, and transport failures are returned in
   * [`NativeLifecycleResult`].
   */
  useTableByName(table: string): Promise<NativeLifecycleResult>
  /**
   * The active write binding, if any.
   *
   * # Errors
   *
   * Returns a napi error when the binding cannot be projected.
   */
  get table(): NativeTableConfig | null
  /**
   * Enqueues one JSON row into the active table.
   *
   * Stays synchronous because the producer push is a bounded, non-blocking
   * queue operation; only the drains need a worker thread. A saturated queue
   * refuses here rather than dropping silently.
   *
   * # Errors
   *
   * Returns a napi error only when the outcome cannot be encoded; an invalid
   * card reference, no-active-table, and queue-full refusals are returned in
   * [`NativeLifecycleResult`].
   */
  insert(row: string, cardRef?: string | undefined | null, runId?: string | undefined | null): NativeLifecycleResult
  /**
   * Writes one already-built Arrow batch to `table` and awaits durability.
   *
   * The batch crosses as a single-batch Arrow IPC stream, the same framing
   * [`NativeTableConfig::schema_ipc`] uses in the other direction, so the
   * field metadata a canonical table declares survives the boundary. Unlike
   * [`NativeBifrost::insert`] nothing is buffered, so no flush follows.
   *
   * # Errors
   *
   * Returns a napi error when the bytes are not one single-batch Arrow IPC
   * stream; server and envelope refusals are returned in
   * [`NativeLifecycleResult`].
   */
  writeBatch(table: string, batchIpc: Buffer): Promise<NativeLifecycleResult>
  /**
   * Flushes every pooled producer and awaits each durable acknowledgement.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * producer and sink failures are returned in [`NativeLifecycleResult`].
   */
  flush(): Promise<NativeLifecycleResult>
  /**
   * Drains every producer and stops its background task.
   *
   * # Errors
   *
   * As [`NativeBifrost::flush`].
   */
  shutdown(): Promise<NativeLifecycleResult>
  /** Number of distinct table producers currently pooled. */
  get producerCount(): number
  /**
   * Starts one terminal-safe query through the Rust SDK owner.
   *
   * Expected request, Gate, authentication, and transport failures are
   * returned in [`NativeQueryStart`] so JavaScript never has to parse an
   * exception message to recover the public Wyrd error contract.
   *
   * # Errors
   *
   * Returns a napi error only when napi cannot project the structured
   * startup result itself.
   */
  query(request: NativeQueryRequest): Promise<NativeQueryStart>
  /**
   * Lists active queries for the authenticated tenant.
   *
   * Cancelling the JavaScript promise abandons the pending HTTP request and
   * does not create client-owned lifecycle state.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * Wyrd control failures are returned in [`NativeLifecycleResult`].
   */
  running(): Promise<NativeLifecycleResult>
  /**
   * Gets one active query by canonical request ID.
   *
   * Cancelling the JavaScript promise abandons the pending HTTP request and
   * does not alter the active query.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * validation and Wyrd control failures are returned in [`NativeLifecycleResult`].
   */
  status(requestId: string): Promise<NativeLifecycleResult>
  /**
   * Requests server-side cancellation without closing a local stream.
   *
   * Once the server accepts cancellation, abandoning the JavaScript promise
   * does not reverse the server-side lifecycle transition.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * validation and Wyrd control failures are returned in [`NativeLifecycleResult`].
   */
  cancel(requestId: string): Promise<NativeLifecycleResult>
  /**
   * Describes one registered table's stored physical schema.
   *
   * The description is the server's own projection: the user fields a caller
   * declares, the correlation inputs the write path resolves, the managed
   * candidates it may supply, and a canonical table's physical fingerprint.
   * JavaScript builds its insertable schema from this rather than from a
   * local copy of the table contract.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * Wyrd control failures are returned in [`NativeLifecycleResult`].
   */
  describeTable(namespace: string, name: string): Promise<NativeLifecycleResult>
}

/** Native query stream that retains Rust terminal validation and emits raw IPC. */
export declare class NativeBifrostQueryStream {
  /** Returns the canonical server lifecycle request identity. */
  get requestId(): string
  /**
   * Returns one Arrow IPC batch or the final validated terminal.
   *
   * # Errors
   *
   * Returns a napi error carrying the stable Wyrd code for failed,
   * incomplete, malformed, or transport-terminated streams.
   */
  next(): Promise<NativeQueryStep>
  /** Drops the response stream so Rust transport cancellation propagates. */
  close(): Promise<void>
  /**
   * Returns the result's authoritative schema as a schema-only IPC stream.
   *
   * Retained when the stream completes, so a query that produced no batch
   * still carries the server's schema and JavaScript never has to infer one
   * from the batches it happened to receive.
   *
   * # Errors
   *
   * Returns a napi error when the retaining lock is poisoned.
   */
  get schemaIpc(): Buffer | null
  /**
   * Returns serialized terminal metadata after validated completion.
   *
   * # Errors
   *
   * Returns a napi error when the terminal lock is poisoned.
   */
  get terminalJson(): string | null
}

/** Tenant-scoped Card registry handle over the shared `wyrd_client` Cards. */
export declare class NativeCards {
  /**
   * Loads one Card tree from disk and registers it as a composite.
   *
   * # Errors
   *
   * Returns a napi error only when the receipt cannot be serialized; load,
   * validation, and registry failures are returned in the result.
   */
  registerFromPath(path: string): Promise<NativeLifecycleResult>
  /**
   * Fetches one Card envelope by exact reference.
   *
   * # Errors
   *
   * Returns a napi error only when the envelope cannot be serialized; an
   * invalid reference or registry failure is returned in the result.
   */
  get(cardRef: string): Promise<NativeLifecycleResult>
  /**
   * Lists metadata-only Card summaries for one serialized list request.
   *
   * # Errors
   *
   * Returns a napi error only when the page cannot be serialized; a
   * malformed request or registry failure is returned in the result.
   */
  list(requestJson: string): Promise<NativeLifecycleResult>
  /**
   * Hydrates one Card graph into a published local bundle.
   *
   * `metadata_only` skips artifact payload downloads. A failed hydration
   * never publishes a partial bundle.
   *
   * # Errors
   *
   * Returns a napi error only when the summary cannot be serialized; graph,
   * destination, and transfer failures are returned in the result.
   */
  hydrate(cardRef: string, destination: string, metadataOnly: boolean): Promise<NativeLifecycleResult>
  /**
   * Loads one registered Workflow and its locked Agents and Prompts.
   *
   * `selector_json` is `{ "space", "name", "version" }` or `{ "uid" }`; any
   * other shape, including a mix of both, is refused with
   * `WYRD_WORKFLOW_400_INVALID_CARD_REF` before any read. A valid selector delegates
   * to the shared [`wyrd_client::WorkflowCards::load`], which reads every
   * Card at its locked version.
   *
   * Never rejects: a failure is returned in [`NativeWorkflowLoad::error`]
   * with its catalog code, and the public TypeScript `cards.workflow.load`
   * throws it as a `WyrdError`. Loading only reads Cards. If the Node
   * promise is abandoned, completed reads may already have happened, but
   * no partial Workflow is returned and nothing durable is written.
   */
  loadWorkflow(selectorJson: string): Promise<NativeWorkflowLoad>
  /**
   * Soft-deletes one Card by exact reference.
   *
   * # Errors
   *
   * Returns a napi error only when the result cannot be projected; an
   * invalid reference or registry failure is returned in the result.
   */
  delete(cardRef: string): Promise<NativeLifecycleResult>
}

/**
 * Tenant gateway administration handle over the shared `wyrd_client` Gateway.
 *
 * Provider credential mutation is absent by construction: submitting,
 * rotating, revoking, and deleting a credential live on
 * `wyrd_client::gateway_credential`, which this binding never constructs.
 * A JavaScript caller reaching this exported class directly therefore has no
 * method that can write a managed secret, and no runtime source check is
 * needed. Reads, deployments, policies, and invocation stay.
 */
export declare class NativeGateway {
  /**
   * Reads one redacted provider credential by name.
   *
   * # Errors
   *
   * Returns a napi error only when the view cannot be serialized; an invalid
   * name or server failure is returned in the result.
   */
  credential(name: string): Promise<NativeLifecycleResult>
  /**
   * Lists the tenant's redacted provider credentials ordered by name.
   *
   * # Errors
   *
   * Returns a napi error only when the list cannot be serialized; server
   * failures are returned in the result.
   */
  credentials(): Promise<NativeLifecycleResult>
  /**
   * Creates or replaces a provider deployment from its serialized body.
   *
   * # Errors
   *
   * Returns a napi error only when the deployment cannot be serialized; a
   * malformed body or server failure is returned in the result.
   */
  putDeployment(deploymentJson: string): Promise<NativeLifecycleResult>
  /**
   * Reads one provider deployment by name.
   *
   * # Errors
   *
   * Returns a napi error only when the deployment cannot be serialized; an
   * invalid name or server failure is returned in the result.
   */
  deployment(name: string): Promise<NativeLifecycleResult>
  /**
   * Lists the tenant's provider deployments ordered by name.
   *
   * # Errors
   *
   * Returns a napi error only when the list cannot be serialized; server
   * failures are returned in the result.
   */
  deployments(): Promise<NativeLifecycleResult>
  /**
   * Deletes one provider deployment; an absent name succeeds.
   *
   * # Errors
   *
   * Returns a napi error only when the result cannot be projected; an
   * invalid name or server failure is returned in the result.
   */
  deleteDeployment(name: string): Promise<NativeLifecycleResult>
  /**
   * Replaces the tenant fallback policy from its serialized body.
   *
   * # Errors
   *
   * Returns a napi error only when the policy cannot be serialized; a
   * malformed body or server failure is returned in the result.
   */
  putFallbackPolicy(policyJson: string): Promise<NativeLifecycleResult>
  /**
   * Reads the tenant fallback policy, or the default when none is set.
   *
   * # Errors
   *
   * Returns a napi error only when the policy cannot be serialized; server
   * failures are returned in the result.
   */
  fallbackPolicy(): Promise<NativeLifecycleResult>
  /**
   * Restores the default fallback policy.
   *
   * # Errors
   *
   * Returns a napi error only when the result cannot be projected; server
   * failures are returned in the result.
   */
  deleteFallbackPolicy(): Promise<NativeLifecycleResult>
  /**
   * Replaces the tenant governance policy from its serialized body.
   *
   * # Errors
   *
   * Returns a napi error only when the policy cannot be serialized; a
   * malformed body or server failure is returned in the result.
   */
  putGovernancePolicy(policyJson: string): Promise<NativeLifecycleResult>
  /**
   * Reads the tenant governance policy, or the default when none is set.
   *
   * # Errors
   *
   * Returns a napi error only when the policy cannot be serialized; server
   * failures are returned in the result.
   */
  governancePolicy(): Promise<NativeLifecycleResult>
  /**
   * Restores the default governance policy.
   *
   * # Errors
   *
   * Returns a napi error only when the result cannot be projected; server
   * failures are returned in the result.
   */
  deleteGovernancePolicy(): Promise<NativeLifecycleResult>
  /**
   * Replaces the tenant capture policy from its serialized write body.
   *
   * # Errors
   *
   * Returns a napi error only when the versioned policy cannot be
   * serialized; a malformed body or server failure is returned in the
   * result.
   */
  putCapturePolicy(policyJson: string): Promise<NativeLifecycleResult>
  /**
   * Reads the tenant capture policy, or the disabled default.
   *
   * # Errors
   *
   * Returns a napi error only when the policy cannot be serialized; server
   * failures are returned in the result.
   */
  capturePolicy(): Promise<NativeLifecycleResult>
}

/** Tenant-scoped Operator connection handle over the shared `wyrd_client` handle. */
export declare class NativeOperatorConnections {
  /**
   * Creates one connection from a serialized `CreateOperatorConnectionRequest`.
   *
   * # Errors
   *
   * Returns a napi error only when the view cannot be serialized; a
   * malformed request or server refusal is returned in the result.
   */
  create(requestJson: string): Promise<NativeLifecycleResult>
  /**
   * Lists the caller tenant's redacted connections.
   *
   * # Errors
   *
   * Returns a napi error only when the views cannot be serialized.
   */
  list(): Promise<NativeLifecycleResult>
  /**
   * Reads one connection's redacted view.
   *
   * # Errors
   *
   * Returns a napi error only when the view cannot be serialized; a
   * malformed ID or server refusal is returned in the result.
   */
  get(id: string): Promise<NativeLifecycleResult>
  /**
   * Updates or rotates one connection from a serialized
   * `UpdateOperatorConnectionRequest`.
   *
   * # Errors
   *
   * Returns a napi error only when the view cannot be serialized; a
   * malformed argument or server refusal is returned in the result.
   */
  update(id: string, requestJson: string): Promise<NativeLifecycleResult>
  /**
   * Disables one connection; Operators naming it fail closed.
   *
   * # Errors
   *
   * Returns a napi error only when the view cannot be serialized; a
   * malformed ID or server refusal is returned in the result.
   */
  disable(id: string): Promise<NativeLifecycleResult>
}

/** Structured result of starting a native terminal-safe query. */
export declare class NativeQueryStart {
  /** Moves the Rust-owned stream out after a successful startup. */
  takeStream(): NativeBifrostQueryStream | null
  /** Returns the stable SDK error code when startup failed. */
  get errorCode(): string | null
  /** Returns the HTTP-equivalent status when startup failed. */
  get errorStatus(): number | null
  /** Returns the stable title when startup failed. */
  get errorTitle(): string | null
  /** Returns the scrubbed SDK error detail when startup failed. */
  get errorDetail(): string | null
  /** Returns operator-facing remediation when startup failed. */
  get errorRemediation(): string | null
  /** Returns serialized JSON-safe structured details when startup failed. */
  get errorDetailsJson(): string | null
}

/**
 * One invocation, or one Card-scoped view of it, over the shared `Run`.
 *
 * Every emit delegates to `wyrd_client::observe`; this wrapper only carries
 * Node strings across the boundary so the three SDKs share one projection.
 */
export declare class NativeRun {
  /** The `UUIDv7` invocation identity this run and every view of it shares. */
  get runId(): string
  /** The alias this view was opened with. */
  get alias(): string
  /** An immutable sibling view scoped to a registered alias. */
  forCard(alias: string): NativeRunOpen
  /**
   * Emits one Drift observation from its JSON feature object.
   *
   * # Errors
   *
   * Returns a napi error only when the outcome cannot be projected; a
   * malformed feature map, the lifecycle refusals, and queue saturation are
   * returned in [`NativeLifecycleResult`].
   */
  drift(featuresJson: string, sessionId?: string | undefined | null): NativeLifecycleResult
  /**
   * Emits one Eval observation from its JSON context and options.
   *
   * `media_json` is one JSON array of media descriptors; `trace_id` and
   * `span_id` are lower-case hex and fall back to the active span when both
   * are omitted.
   *
   * # Errors
   *
   * Returns a napi error only when the outcome cannot be projected; malformed
   * identifiers, a span without its trace, the lifecycle refusals, and queue
   * saturation are returned in [`NativeLifecycleResult`].
   */
  eval(contextJson: string, sessionId?: string | undefined | null, mediaJson?: string | undefined | null, traceId?: string | undefined | null, spanId?: string | undefined | null): NativeLifecycleResult
  /**
   * Judges this view's subject with a bound Verifier from JSON input.
   *
   * `input_json` is one Eval context object or one array of Drift feature
   * rows; `media_json` is one JSON array of media descriptors. One server
   * call, never replayed; nothing is observed, recorded, or dispatched.
   *
   * # Errors
   *
   * Returns a napi error only when the outcome cannot be projected; an
   * unbound Verifier, input of the wrong shape, malformed media, and the
   * server's verification refusals are returned in
   * [`NativeLifecycleResult`].
   */
  verify(verifier: string, inputJson: string, mediaJson?: string | undefined | null): Promise<NativeLifecycleResult>
  /**
   * Emits one row into a registered `vala.datasets` table.
   *
   * Asynchronous because the first call for a table describes it; later calls
   * reuse the cached schema and producer.
   *
   * # Errors
   *
   * Returns a napi error only when the outcome cannot be projected; a
   * reserved, unknown, or unauthorized table and the lifecycle refusals are
   * returned in [`NativeLifecycleResult`].
   */
  record(table: string, rowJson: string): Promise<NativeLifecycleResult>
}

/** Runnable Workflow loaded from a file or from the registry. */
export declare class NativeWorkflow {
  /** Returns the step IDs in declaration order. */
  stepIds(): Array<string>
  /**
   * Runs this Workflow with the given JSON object of declared inputs.
   *
   * Validation, input, and route errors are returned before any step is
   * dispatched; step failures are recorded in the returned run.
   *
   * # Errors
   *
   * Returns a napi error only when the run cannot be serialized; a
   * malformed input or pre-dispatch refusal is returned in the result.
   */
  run(inputJson?: string | undefined | null): Promise<NativeLifecycleResult>
}

/** Node-facing handle to one authenticated [`WyrdClient`]. */
export declare class NativeWyrdClient {
  /** Returns the effective HTTP server URL this client sends requests to. */
  get serverUrl(): string
  /**
   * Returns the effective gRPC endpoint: the explicit `grpc_url` when one
   * was given, else the server URL's scheme and host on port `50051`.
   */
  get grpcUrl(): string
  /**
   * Returns a current bearer for this client's credential.
   *
   * Reads through the Rust client's shared auth middleware, so an expired
   * token is renewed there; nothing is cached in Node. A refusal or
   * transport failure is returned as catalog metadata.
   */
  accessToken(): Promise<NativeAccessTokenResult>
  /**
   * Returns a client that acts for the holder of `subject_token`.
   *
   * This client's credential is the actor. The first exchange runs here so a
   * refusal is returned at the call site; the returned client re-exchanges
   * in Rust before expiry. An `audience` other than `wyrd` or `bifrost` is a
   * `WYRD_SPEC_400_VALIDATION` result.
   */
  onBehalfOf(subjectToken: string, audience: string): Promise<NativeWyrdClientResult>
  /**
   * Connects one Bifrost client over this client's authentication and
   * transport, optionally already bound to a write target.
   *
   * A delegated client therefore reads and writes as its subject with its
   * actor attributed. The transport arguments exist only so a caller that
   * also supplies them is refused with `WYRD_SPEC_400_VALIDATION` rather
   * than having them silently ignored.
   *
   * # Errors
   *
   * Returns a napi error only when the supplied table config is not one
   * serialized `TableConfig`; the conflict, byte-budget, and ingest-dial
   * failures are returned as catalog metadata.
   */
  connectBifrost(table?: NativeTableConfig | undefined | null, serverUrl?: string | undefined | null, credential?: string | undefined | null, grpcUrl?: string | undefined | null, tenant?: string | undefined | null, clientByteLimitBytes?: number | undefined | null): Promise<NativeBifrostConnection>
}

/**
 * Offline hydrated-bundle view over the shared `wyrd_client` `WyrdState`.
 *
 * The open result is retained so an invalid bundle surfaces its catalog error
 * on the first read instead of as an untyped constructor failure.
 */
export declare class NativeWyrdState {
  /**
   * Returns the exact root Card reference.
   *
   * # Errors
   *
   * Returns a napi error only when the reference cannot be serialized.
   */
  rootRef(): NativeLifecycleResult
  /**
   * Returns every persisted alias in stable sorted order.
   *
   * # Errors
   *
   * Returns a napi error only when the aliases cannot be serialized.
   */
  aliases(): NativeLifecycleResult
  /**
   * Resolves an alias to its stored Card envelope.
   *
   * # Errors
   *
   * Returns a napi error only when the envelope cannot be serialized.
   */
  card(alias: string): NativeLifecycleResult
  /**
   * Resolves an alias to its exact Card reference.
   *
   * # Errors
   *
   * Returns a napi error only when the reference cannot be serialized.
   */
  cardRef(alias: string): NativeLifecycleResult
  /**
   * Returns the verified local artifacts for an alias.
   *
   * # Errors
   *
   * Returns a napi error only when the artifact list cannot be serialized.
   */
  artifacts(alias: string): NativeLifecycleResult
  /**
   * Connects this state's one Bifrost writer and describes the fixed tables.
   *
   * The transport arguments are `connectBifrost`'s and resolve through the
   * same chain when omitted. Startup describes both fixed observation tables
   * before succeeding, so a run can never enqueue against a missing,
   * unauthorized, or incompatible system table.
   *
   * # Errors
   *
   * Returns a napi error when `table` is not one serialized `TableConfig`;
   * a second start, a closed state, and credential, byte-budget, dial, and
   * fixed-table failures are returned in [`NativeLifecycleResult`].
   */
  startBifrost(table?: NativeTableConfig | undefined | null, serverUrl?: string | undefined | null, credential?: string | undefined | null, grpcUrl?: string | undefined | null, tenant?: string | undefined | null, clientByteLimitBytes?: number | undefined | null): Promise<NativeLifecycleResult>
  /**
   * Opens one invocation over this state, targeting `card` or the root Service.
   *
   * Local only: no network IO, no server-side Run resource, and no Verifier
   * execution. A `card` alias resolves in the hydrated graph before the run
   * mints its `run_id`; an unknown alias is returned as the outcome's
   * `WYRD_SDK_404_UNKNOWN_ALIAS` error and nothing is opened.
   */
  run(card?: string | undefined | null): NativeRunOpen
  /**
   * Drains every producer of this state's writer without closing it.
   *
   * # Errors
   *
   * Returns a napi error only when the outcome cannot be projected; the
   * lifecycle refusals and the first producer or sink failure are returned in
   * [`NativeLifecycleResult`].
   */
  flush(): Promise<NativeLifecycleResult>
  /**
   * Drains every producer of this state's writer and closes it to writes.
   *
   * Graceful shutdown is the durability barrier: queue admission is not a
   * Scribe acknowledgement. After an ambiguous failure, retry `shutdown` on
   * the same state rather than replacing the writer.
   *
   * # Errors
   *
   * Returns a napi error only when the outcome cannot be projected; the first
   * producer or sink failure is returned in [`NativeLifecycleResult`].
   */
  shutdown(): Promise<NativeLifecycleResult>
}

/**
 * Registers a local Card tree and returns its receipt (`wyrd apply`).
 *
 * # Errors
 *
 * Returns a napi error only when the receipt cannot be serialized; local,
 * client, and server failures are returned in the result.
 */
export declare function cliApply(path: string, server?: string | undefined | null): Promise<NativeLifecycleResult>

/**
 * Deletes one unreferenced provider credential; an absent name succeeds
 * (`wyrd gateway credential delete`).
 *
 * # Errors
 *
 * Returns a napi error only when the result cannot be serialized; an invalid
 * name, client, or server failure is returned in the result.
 */
export declare function cliDeleteProviderCredential(name: string, server?: string | undefined | null): Promise<NativeLifecycleResult>

/**
 * Hydrates a Card's reachable graph into `output_dir` (`wyrd get`).
 *
 * # Errors
 *
 * Returns a napi error only when the summary cannot be serialized; selector,
 * client, and server failures are returned in the result.
 */
export declare function cliGet(selector: NativeCardSelector, outputDir: string, metadataOnly?: boolean | undefined | null, server?: string | undefined | null): Promise<NativeLifecycleResult>

/**
 * Issues an API key bound to one exact Card (`wyrd auth issue-key`).
 *
 * The result holds the plaintext key exactly once.
 *
 * # Errors
 *
 * Returns a napi error only when the response cannot be serialized;
 * coordinate, client, and server failures are returned in the result.
 */
export declare function cliIssueKey(options: NativeIssueKey, server?: string | undefined | null): Promise<NativeLifecycleResult>

/**
 * Loads one Card and materializes its artifacts (`wyrd load`).
 *
 * # Errors
 *
 * Returns a napi error only when the output cannot be serialized; selector,
 * client, and server failures are returned in the result.
 */
export declare function cliLoad(selector: NativeCardSelector, path?: string | undefined | null, server?: string | undefined | null): Promise<NativeLifecycleResult>

/**
 * Validates a local Card tree without contacting a server (`wyrd plan`).
 *
 * # Errors
 *
 * Returns a napi error only when the plan cannot be serialized; a load
 * failure is returned in the result.
 */
export declare function cliPlan(path: string): NativeLifecycleResult

/**
 * Creates or rotates one provider credential from its serialized body
 * (`wyrd gateway credential put`).
 *
 * A decode failure quotes no part of the body, which may carry a provider
 * key; the returned view is redacted.
 *
 * # Errors
 *
 * Returns a napi error only when the view cannot be serialized; a malformed
 * body, client, or server failure is returned in the result.
 */
export declare function cliPutProviderCredential(writeJson: string, server?: string | undefined | null): Promise<NativeLifecycleResult>

/**
 * Terminally revokes one provider credential
 * (`wyrd gateway credential revoke`).
 *
 * # Errors
 *
 * Returns a napi error only when the view cannot be serialized; an invalid
 * name, client, or server failure is returned in the result.
 */
export declare function cliRevokeProviderCredential(name: string, server?: string | undefined | null): Promise<NativeLifecycleResult>

/**
 * Connects one Bifrost client, optionally already bound to a write target.
 *
 * A free function rather than a constructor because connecting is asynchronous
 * and a napi constructor cannot be. Every transport argument is optional and
 * falls through the existing resolution chain exactly once when omitted.
 *
 * # Errors
 *
 * Returns a napi error only when the supplied table config is not one
 * serialized `TableConfig`; credential, byte-budget, and ingest-dial failures
 * are returned as catalog metadata.
 */
export declare function connectBifrost(table?: NativeTableConfig | undefined | null, serverUrl?: string | undefined | null, credential?: string | undefined | null, grpcUrl?: string | undefined | null, tenant?: string | undefined | null, clientByteLimitBytes?: number | undefined | null): Promise<NativeBifrostConnection>

/**
 * Builds one Card registry handle without performing IO.
 *
 * Omitted arguments resolve through the same shared client configuration
 * chain as `connectBifrost`, so both capabilities authenticate identically.
 * Credential and configuration failures are returned as catalog metadata.
 */
export declare function connectCards(serverUrl?: string | undefined | null, credential?: string | undefined | null, tenant?: string | undefined | null): NativeCardsConnection

/**
 * Builds one gateway administration handle without performing IO.
 *
 * Omitted arguments resolve through the same shared client configuration
 * chain as `connectCards`, so every capability authenticates identically.
 *
 * # Errors
 *
 * Returns a napi error when no credential resolves or the HTTP client cannot
 * be built.
 */
export declare function connectGateway(serverUrl?: string | undefined | null, credential?: string | undefined | null, tenant?: string | undefined | null): NativeGateway

/**
 * Builds one Operator connection handle without performing IO.
 *
 * Omitted arguments resolve through the same shared client configuration
 * chain as `connectCards`.
 */
export declare function connectOperatorConnections(serverUrl?: string | undefined | null, credential?: string | undefined | null, tenant?: string | undefined | null): NativeOperatorConnectionsConnection

/**
 * Builds one client without performing IO.
 *
 * Omitted arguments resolve through `client_from_options`: the environment,
 * then the saved `wyrd auth login` for this server (the one for `tenant`, a
 * tenant route key, when given, otherwise the newest), then
 * `~/.config/wyrd/credentials.toml`. Failures are returned as catalog
 * metadata, including `WYRD_CLIENT_401_SAVED_LOGIN_UNUSABLE` when this server
 * has saved logins but none for `tenant`.
 */
export declare function connectWyrdClient(serverUrl?: string | undefined | null, credential?: string | undefined | null, grpcUrl?: string | undefined | null, tenant?: string | undefined | null): NativeWyrdClientResult

/**
 * Fetches an already-registered table's config by name.
 *
 * Every transport argument is optional and resolves through the same chain the
 * client constructor uses when omitted.
 *
 * # Errors
 *
 * Returns a napi error only when the described config cannot be encoded;
 * credential, transport, and server refusals are returned as catalog metadata.
 */
export declare function describeTableConfig(table: string, serverUrl?: string | undefined | null, credential?: string | undefined | null, grpcUrl?: string | undefined | null, tenant?: string | undefined | null): Promise<NativeTableConfigResult>

/**
 * Load an authored Workflow file and the Cards it references.
 *
 * Delegates to the shared [`Workflow::from_path`]: local files load without
 * a server, and registry refs are read through the ambient client
 * configuration (`WYRD_SERVER_URL`, `WYRD_API_KEY`). Never rejects: a load
 * failure is returned in [`NativeWorkflowLoad::error`] with its catalog
 * code, and the public TypeScript `Workflow.fromPath` throws it as a
 * `WyrdError`.
 *
 * Loading only reads files and Cards. If the Node promise is abandoned,
 * completed reads may already have happened, but no partial Workflow is
 * returned and nothing durable is written.
 */
export declare function loadWorkflowFromPath(path: string): Promise<NativeWorkflowLoad>

/** Closed result of reading one client's current bearer: a token or a catalog error. */
export interface NativeAccessTokenResult {
  /** Current bearer when the auth path produced one. */
  token?: string
  /** Catalog failure otherwise. */
  error?: NativeWyrdError
}

/** Closed result of connecting one Bifrost client: a handle or a catalog error. */
export interface NativeBifrostConnection {
  /** Connected client when construction succeeded. */
  bifrost?: NativeBifrost
  /** Catalog failure when construction failed. */
  error?: NativeWyrdError
}

/** Closed result of building one Card registry handle: a handle or a catalog error. */
export interface NativeCardsConnection {
  /** Registry handle when construction succeeded. */
  cards?: NativeCards
  /** Catalog failure when no credential resolves or the client cannot be built. */
  error?: NativeWyrdError
}

/**
 * Card selector for `get` and `load`: a `uid` with `kind`, or `kind`,
 * `space`, and `name`; `version` narrows either.
 */
export interface NativeCardSelector {
  /** Card kind, such as `Model` or `Prompt`. */
  kind?: string
  /** Card space. */
  space?: string
  /** Card name. */
  name?: string
  /** Exact Card version. */
  version?: string
  /** Exact Card UID. */
  uid?: string
}

/** Options for `issueKey`: the bound Card and the key's label and lifetime. */
export interface NativeIssueKey {
  /** Card kind, such as `Service` or `Agent`. */
  kind: string
  /** Card name. */
  name: string
  /** Exact Card version. */
  version: string
  /** Card space. */
  space: string
  /** Optional label stored with the key row. */
  label?: string
  /** Optional lifetime override in seconds. */
  expiresInSeconds?: number
}

/** Structured native result for one live-query lifecycle control. */
export interface NativeLifecycleResult {
  /** Canonical JSON payload when the control succeeded. */
  valueJson?: string
  /** Stable SDK error code when the control failed. */
  errorCode?: string
  /** HTTP-equivalent status when the control failed. */
  errorStatus?: number
  /** Stable title when the control failed. */
  errorTitle?: string
  /** Scrubbed detail when the control failed. */
  errorDetail?: string
  /** Operator-facing remediation when the control failed. */
  errorRemediation?: string
  /** Serialized JSON-safe structured details when the control failed. */
  errorDetailsJson?: string
}

/** Closed result of building one Operator connection handle: a handle or a catalog error. */
export interface NativeOperatorConnectionsConnection {
  /** Operator connection handle when construction succeeded. */
  connections?: NativeOperatorConnections
  /** Catalog failure when no credential resolves or the client cannot be built. */
  error?: NativeWyrdError
}

/**
 * One JavaScript bind value, tagged by its JavaScript runtime type.
 *
 * The TypeScript facade sets `kind` to `"null"`, `"boolean"`, `"number"`, or
 * `"string"` and fills the matching field; any other kind is refused by
 * [`NativeQueryParam::into_param`] so the catalog error comes from Rust.
 */
export interface NativeQueryParam {
  /** JavaScript runtime type of the value. */
  kind: string
  /** Value when `kind` is `"boolean"`. */
  bool?: boolean
  /** Value when `kind` is `"number"`. */
  number?: number
  /** Value when `kind` is `"string"`. */
  string?: string
}

/** JavaScript query request projected onto the pure Wyrd contract. */
export interface NativeQueryRequest {
  /** SELECT-only SQL text. */
  sql: string
  /**
   * Optional query deadline in milliseconds, valid in `1..=u32::MAX`.
   *
   * Accepted as a JavaScript number so every out-of-range, fractional, or
   * non-finite value reaches the structured startup failure instead of a
   * napi binding error.
   */
  deadlineMs?: number
  /** Ordered bind values for the `$1..$n` placeholders in `sql`. */
  params?: Array<NativeQueryParam>
}

/** One raw native iterator step consumed by the TypeScript Arrow facade. */
export interface NativeQueryStep {
  /** Complete Arrow IPC stream containing exactly one record batch. */
  ipc?: Buffer
  /** Serialized validated terminal, present only on the final step. */
  terminalJson?: string
  /** Stable SDK error code for a failed native step. */
  errorCode?: string
  /** HTTP-equivalent status for a failed native step. */
  errorStatus?: number
  /** Stable title for a failed native step. */
  errorTitle?: string
  /** Scrubbed SDK error detail for a failed native step. */
  errorDetail?: string
  /** Operator-facing remediation for a failed native step. */
  errorRemediation?: string
  /** Serialized JSON-safe structured details for a failed native step. */
  errorDetailsJson?: string
}

/**
 * Closed result of opening one scoped run: a run handle or a catalog error.
 *
 * Opening cannot be projected through [`NativeLifecycleResult`] because the run
 * is a native class rather than a serializable value, so it follows the same
 * handle-or-error shape as [`NativeCardsConnection`].
 */
export interface NativeRunOpen {
  /** The scoped run when the bundle and alias resolved. */
  run?: NativeRun
  /** The stable failure that rejected the bundle or the alias. */
  error?: NativeWyrdError
}

/**
 * One Bifrost table as it crosses the Node boundary.
 *
 * `configJson` is the authoritative value — the whole `TableConfig`, including
 * the server identity a described table already carries — so a config that
 * goes out to JavaScript and comes back is the same config. The other fields
 * are read-only projections JavaScript would otherwise have to derive, and
 * deriving them would mean reimplementing the schema mapping this SDK exists
 * to keep in one place.
 */
export interface NativeTableConfig {
  /** The serialized `TableConfig`; the only field read back natively. */
  configJson: string
  /** `namespace.name`. */
  fqn: string
  /** The declared user columns as one schema-only Arrow IPC stream. */
  schemaIpc: Buffer
  /** Serialized `{table_uid, fingerprint}` once the server has minted it. */
  resolvedJson?: string
}

/** Closed result of describing one table: its config or a catalog error. */
export interface NativeTableConfigResult {
  /** Described table config when the server answered. */
  config?: NativeTableConfig
  /** Catalog failure when description failed. */
  error?: NativeWyrdError
}

/** Closed result of loading one Workflow: a handle or a catalog error. */
export interface NativeWorkflowLoad {
  /** Workflow when loading succeeded. */
  workflow?: NativeWorkflow
  /** Catalog failure otherwise. */
  error?: NativeWyrdError
}

/** Closed result of building or delegating one client: a handle or a catalog error. */
export interface NativeWyrdClientResult {
  /** Client when construction or the exchange succeeded. */
  client?: NativeWyrdClient
  /** Catalog failure otherwise. */
  error?: NativeWyrdError
}

/**
 * Catalog metadata for one failed native construction or description.
 *
 * Field names match the other native results so the TypeScript facade builds
 * its public `WyrdError` through the same projection.
 */
export interface NativeWyrdError {
  /** Stable catalog code. */
  errorCode: string
  /** HTTP-equivalent status. */
  errorStatus: number
  /** Stable catalog title. */
  errorTitle: string
  /** Scrubbed catalog detail. */
  errorDetail: string
  /** Operator-facing remediation. */
  errorRemediation: string
  /** Serialized JSON-safe structured details, when present. */
  errorDetailsJson?: string
}

/** Loads and validates one hydrated bundle without contacting Wyrd. */
export declare function openWyrdState(path: string): NativeWyrdState

/**
 * Runs the `wyrd` executable over `args` (argv including the program name)
 * and resolves its process exit code.
 */
export declare function runWyrdCli(args: Array<string>): Promise<number>

/**
 * Builds one table config from a JSON Schema document.
 *
 * This is the Zod (`z.toJSONSchema()`) door; the mapping is the same
 * `wyrd-queue` owner every language uses, so one model declares the same
 * columns from any SDK.
 *
 * # Errors
 *
 * Returns a napi error only when the declared config cannot be encoded. A
 * table that is not `namespace.name`, a document that is not one mappable
 * JSON Schema, a server-owned column, a layout that is not one
 * physical-layout declaration, or a compaction target that is not a
 * non-negative integer is returned as catalog metadata.
 */
export declare function tableConfigFromJsonSchema(table: string, schemaJson: string, layoutJson?: string | undefined | null, compactionTargetFileSizeBytes?: number | undefined | null): NativeTableConfigResult
