/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * The one Bifrost client: query any authorized table, write to the active one.
 *
 * Mirrors the Python binding: both are thin conversions over the one
 * [`vala_sdk::Bifrost`], so batching, backpressure, registration, and the
 * query contract have exactly one owner.
 */
export declare class NativeBifrost {
  /**
   * Creates the active table, answering `created` or `already_exists`.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * no-active-table, fingerprint-conflict, and transport failures are
   * returned in [`NativeLifecycleResult`].
   */
  register(): Promise<NativeLifecycleResult>
  /**
   * Binds `table` as the write target, returning the previous binding.
   *
   * The previous table's producer stays pooled, so its buffered rows still
   * flush; a swap loses nothing.
   *
   * # Errors
   *
   * Returns a napi error when the config is not one serialized `TableConfig`
   * or the previous binding cannot be projected.
   */
  useTable(table: NativeTableConfig): NativeTableConfig | null
  /**
   * Binds an already-registered table by name, describing it first.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * not-found, authorization, and transport failures are returned in
   * [`NativeLifecycleResult`].
   */
  useTableByName(table: string): Promise<NativeLifecycleResult>
  /**
   * The active write binding, if any.
   *
   * # Errors
   *
   * Returns a napi error when the binding cannot be projected.
   */
  get table(): NativeTableConfig | null
  /**
   * Enqueues one JSON row into the active table.
   *
   * Stays synchronous because the producer push is a bounded, non-blocking
   * queue operation; only the drains need a worker thread. A saturated queue
   * refuses here rather than dropping silently.
   *
   * # Errors
   *
   * Returns a napi error for an invalid card reference; no-active-table and
   * queue-full refusals are returned in [`NativeLifecycleResult`].
   */
  insert(row: string, cardRef?: string | undefined | null, runId?: string | undefined | null): NativeLifecycleResult
  /**
   * Flushes every pooled producer and awaits each durable acknowledgement.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * producer and sink failures are returned in [`NativeLifecycleResult`].
   */
  flush(): Promise<NativeLifecycleResult>
  /**
   * Drains every producer and stops its background task.
   *
   * # Errors
   *
   * As [`NativeBifrost::flush`].
   */
  shutdown(): Promise<NativeLifecycleResult>
  /** Number of distinct table producers currently pooled. */
  get producerCount(): number
  /**
   * Starts one terminal-safe query through the Rust SDK owner.
   *
   * Expected request, Gate, authentication, and transport failures are
   * returned in [`NativeQueryStart`] so JavaScript never has to parse an
   * exception message to recover the public Wyrd error contract.
   *
   * # Errors
   *
   * Returns a napi error only when napi cannot project the structured
   * startup result itself.
   */
  query(request: NativeQueryRequest): Promise<NativeQueryStart>
  /**
   * Lists active queries for the authenticated tenant.
   *
   * Cancelling the JavaScript promise abandons the pending HTTP request and
   * does not create client-owned lifecycle state.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * Wyrd control failures are returned in [`NativeLifecycleResult`].
   */
  running(): Promise<NativeLifecycleResult>
  /**
   * Gets one active query by canonical request ID.
   *
   * Cancelling the JavaScript promise abandons the pending HTTP request and
   * does not alter the active query.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * validation and Wyrd control failures are returned in [`NativeLifecycleResult`].
   */
  status(requestId: string): Promise<NativeLifecycleResult>
  /**
   * Requests server-side cancellation without closing a local stream.
   *
   * Once the server accepts cancellation, abandoning the JavaScript promise
   * does not reverse the server-side lifecycle transition.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * validation and Wyrd control failures are returned in [`NativeLifecycleResult`].
   */
  cancel(requestId: string): Promise<NativeLifecycleResult>
  /**
   * Describes one registered table's stored physical schema.
   *
   * The description is the server's own projection: the user fields a caller
   * declares, the correlation inputs the write path resolves, the managed
   * candidates it may supply, and a canonical table's physical fingerprint.
   * JavaScript builds its insertable schema from this rather than from a
   * local copy of the table contract.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * Wyrd control failures are returned in [`NativeLifecycleResult`].
   */
  describeTable(namespace: string, name: string): Promise<NativeLifecycleResult>
}

/** Native query stream that retains Rust terminal validation and emits raw IPC. */
export declare class NativeBifrostQueryStream {
  /** Returns the canonical server lifecycle request identity. */
  get requestId(): string
  /**
   * Returns one Arrow IPC batch or the final validated terminal.
   *
   * # Errors
   *
   * Returns a napi error carrying the stable Wyrd code for failed,
   * incomplete, malformed, or transport-terminated streams.
   */
  next(): Promise<NativeQueryStep>
  /** Drops the response stream so Rust transport cancellation propagates. */
  close(): Promise<void>
  /**
   * Returns the result's authoritative schema as a schema-only IPC stream.
   *
   * Retained when the stream completes, so a query that produced no batch
   * still carries the server's schema and JavaScript never has to infer one
   * from the batches it happened to receive.
   *
   * # Errors
   *
   * Returns a napi error when the retaining lock is poisoned.
   */
  get schemaIpc(): Buffer | null
  /** Returns serialized terminal metadata after validated completion. */
  get terminalJson(): string | null
}

/** Structured result of starting a native terminal-safe query. */
export declare class NativeQueryStart {
  /** Moves the Rust-owned stream out after a successful startup. */
  takeStream(): NativeBifrostQueryStream | null
  /** Returns the stable SDK error code when startup failed. */
  get errorCode(): string | null
  /** Returns the HTTP-equivalent status when startup failed. */
  get errorStatus(): number | null
  /** Returns the stable title when startup failed. */
  get errorTitle(): string | null
  /** Returns the scrubbed SDK error detail when startup failed. */
  get errorDetail(): string | null
  /** Returns operator-facing remediation when startup failed. */
  get errorRemediation(): string | null
  /** Returns serialized JSON-safe structured details when startup failed. */
  get errorDetailsJson(): string | null
}

/**
 * Connects one Bifrost client, optionally already bound to a write target.
 *
 * A free function rather than a constructor because connecting is asynchronous
 * and a napi constructor cannot be. Every transport argument is optional and
 * falls through the existing resolution chain exactly once when omitted.
 *
 * # Errors
 *
 * Returns a napi error when no credential resolves, when the supplied table
 * config is not one serialized `TableConfig`, or when the gRPC ingest channel
 * cannot be dialled.
 */
export declare function connectBifrost(table?: NativeTableConfig | undefined | null, serverUrl?: string | undefined | null, credential?: string | undefined | null, grpcUrl?: string | undefined | null): Promise<NativeBifrost>

/**
 * Fetches an already-registered table's config by name.
 *
 * Every transport argument is optional and resolves through the same chain the
 * client constructor uses when omitted.
 *
 * # Errors
 *
 * Returns a napi error when no credential resolves, or when the server refuses
 * or cannot describe the table.
 */
export declare function describeTableConfig(table: string, serverUrl?: string | undefined | null, credential?: string | undefined | null, grpcUrl?: string | undefined | null): Promise<NativeTableConfig>

/** Structured native result for one live-query lifecycle control. */
export interface NativeLifecycleResult {
  /** Canonical JSON payload when the control succeeded. */
  valueJson?: string
  /** Stable SDK error code when the control failed. */
  errorCode?: string
  /** HTTP-equivalent status when the control failed. */
  errorStatus?: number
  /** Stable title when the control failed. */
  errorTitle?: string
  /** Scrubbed detail when the control failed. */
  errorDetail?: string
  /** Operator-facing remediation when the control failed. */
  errorRemediation?: string
  /** Serialized JSON-safe structured details when the control failed. */
  errorDetailsJson?: string
}

/** JavaScript query request projected onto the pure Wyrd contract. */
export interface NativeQueryRequest {
  /** SELECT-only SQL text. */
  sql: string
  /** `published_only` or `fused`. */
  visibility: string
  /** `strict` or `allow_degraded`. */
  freshness: string
  /** Optional positive query deadline. */
  deadlineMs?: number
}

/** One raw native iterator step consumed by the TypeScript Arrow facade. */
export interface NativeQueryStep {
  /** Complete Arrow IPC stream containing exactly one record batch. */
  ipc?: Buffer
  /** Serialized validated terminal, present only on the final step. */
  terminalJson?: string
  /** Stable SDK error code for a failed native step. */
  errorCode?: string
  /** HTTP-equivalent status for a failed native step. */
  errorStatus?: number
  /** Stable title for a failed native step. */
  errorTitle?: string
  /** Scrubbed SDK error detail for a failed native step. */
  errorDetail?: string
  /** Operator-facing remediation for a failed native step. */
  errorRemediation?: string
  /** Serialized JSON-safe structured details for a failed native step. */
  errorDetailsJson?: string
}

/**
 * One Bifrost table as it crosses the Node boundary.
 *
 * `configJson` is the authoritative value — the whole `TableConfig`, including
 * the server identity a described table already carries — so a config that
 * goes out to JavaScript and comes back is the same config. The other fields
 * are read-only projections JavaScript would otherwise have to derive, and
 * deriving them would mean reimplementing the schema mapping this SDK exists
 * to keep in one place.
 */
export interface NativeTableConfig {
  /** The serialized `TableConfig`; the only field read back natively. */
  configJson: string
  /** `namespace.name`. */
  fqn: string
  /** The declared user columns as one schema-only Arrow IPC stream. */
  schemaIpc: Buffer
  /** Serialized `{table_uid, fingerprint}` once the server has minted it. */
  resolvedJson?: string
}

/**
 * Builds one table config from a JSON Schema document.
 *
 * This is the Zod (`z.toJSONSchema()`) door; the mapping is the same
 * `wyrd-queue` owner every language uses, so one model declares the same
 * columns from any SDK.
 *
 * # Errors
 *
 * Returns a napi error when the table is not `namespace.name`, the document is
 * not one mappable JSON Schema, a declared column is server-owned, or the
 * layout is not one physical-layout declaration.
 */
export declare function tableConfigFromJsonSchema(table: string, schemaJson: string, layoutJson?: string | undefined | null): NativeTableConfig
