/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Authenticated native write handle over Vala's pooled producer path.
 *
 * Mirrors the Python `Bifrost` binding: both are thin conversions over the one
 * [`vala_sdk::Bifrost`] handle, so the durable batching, backpressure, and
 * ingest contract have exactly one owner. The handle is shared through an
 * [`Arc`] so a blocking drain can move it onto a blocking worker without
 * stalling the Node event loop.
 */
export declare class NativeBifrost {
  /**
   * Explicit write path: enqueue one JSON row and propagate backpressure.
   *
   * Stays synchronous because the producer push is a bounded, non-blocking
   * queue operation; only the drain needs a worker thread.
   *
   * # Errors
   *
   * Returns a napi error for a malformed JSON schema, an unsupported schema
   * node, an invalid card reference, or a full or draining producer queue.
   */
  insert(table: string, schema: string, row: string, cardRef: string, runId?: string | undefined | null): void
  /**
   * Fire-and-forget observe path: enqueue one row, counting saturation.
   *
   * Queue saturation is deliberately swallowed and surfaced through
   * [`Self::dropped`] rather than raised, so telemetry never fails a caller.
   *
   * # Errors
   *
   * Returns a napi error only for a malformed JSON schema or card reference,
   * which are caller mistakes rather than backpressure.
   */
  record(table: string, schema: string, row: string, cardRef: string, runId?: string | undefined | null): void
  /**
   * Flush every pooled producer and await each durable acknowledgement.
   *
   * The native drain blocks, so it runs on a blocking worker; awaiting it
   * keeps the Node event loop free. The Python binding releases the GIL for
   * the same reason.
   *
   * # Errors
   *
   * Returns a napi error when a batch cannot be sealed or the server refuses
   * it, preserving the stable error text at the boundary.
   *
   * # Panics
   *
   * Panics when the blocking drain task cannot be joined.
   */
  flush(): Promise<void>
  /**
   * Drain queued rows and stop every producer background task.
   *
   * # Errors
   *
   * Returns a napi error when the terminal drain cannot complete or a
   * server acknowledgement reports a write failure.
   *
   * # Panics
   *
   * Panics when the blocking drain task cannot be joined.
   */
  shutdown(): Promise<void>
  /** Rows dropped by the fire-and-forget observe path under backpressure. */
  get dropped(): number
  /** Number of distinct producers currently pooled. */
  get producerCount(): number
}

/** Authenticated native query client sharing Wyrd's HTTP and auth pools. */
export declare class NativeBifrostQueryClient {
  /** Constructs a bearer-token query client without performing IO. */
  constructor(serverUrl: string, token: string, grpcUrl?: string | undefined | null)
  /**
   * Starts one terminal-safe query through the Rust SDK owner.
   *
   * Expected request, Gate, authentication, and transport failures are
   * returned in [`NativeQueryStart`] so JavaScript never has to parse an
   * exception message to recover the public Wyrd error contract.
   *
   * # Errors
   *
   * Returns a napi error only when napi cannot project the structured
   * startup result itself.
   */
  query(request: NativeQueryRequest): Promise<NativeQueryStart>
  /**
   * Lists active queries for the authenticated tenant.
   *
   * Cancelling the JavaScript promise abandons the pending HTTP request and
   * does not create client-owned lifecycle state.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * Wyrd control failures are returned in [`NativeLifecycleResult`].
   */
  running(): Promise<NativeLifecycleResult>
  /**
   * Gets one active query by canonical request ID.
   *
   * Cancelling the JavaScript promise abandons the pending HTTP request and
   * does not alter the active query.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * validation and Wyrd control failures are returned in [`NativeLifecycleResult`].
   */
  status(requestId: string): Promise<NativeLifecycleResult>
  /**
   * Requests server-side cancellation without closing a local stream.
   *
   * Once the server accepts cancellation, abandoning the JavaScript promise
   * does not reverse the server-side lifecycle transition.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * validation and Wyrd control failures are returned in [`NativeLifecycleResult`].
   */
  cancel(requestId: string): Promise<NativeLifecycleResult>
  /**
   * Describes one registered table's stored physical schema.
   *
   * The description is the server's own projection: the user fields a caller
   * declares, the correlation inputs the write path resolves, the managed
   * candidates it may supply, and a canonical table's physical fingerprint.
   * JavaScript builds its insertable schema from this rather than from a
   * local copy of the table contract.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * Wyrd control failures are returned in [`NativeLifecycleResult`].
   */
  describeTable(namespace: string, name: string): Promise<NativeLifecycleResult>
  /**
   * Reads one complete authorized cut of a single trace.
   *
   * Trace detail has no continuation token: `since` and `until` bound the
   * scanned window only, and each span carries its own events and links.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * window, authorization, and transport failures are returned in
   * [`NativeLifecycleResult`].
   */
  getTrace(traceId: string, since?: string | undefined | null, until?: string | undefined | null): Promise<NativeLifecycleResult>
  /**
   * Reads one page of `GenAI` generation records.
   *
   * # Errors
   *
   * Returns a napi error only when the native result cannot be projected;
   * window, authorization, and transport failures are returned in
   * [`NativeLifecycleResult`].
   */
  queryGenai(request: NativeGenAiRequest): Promise<NativeLifecycleResult>
  /**
   * Projects one described table's writable Arrow schema as schema-only IPC.
   *
   * The buffer carries no batch, so JavaScript decodes it with its installed
   * Arrow implementation instead of reimplementing the description's
   * field/type conversion. `include_event_time` selects whether the caller
   * intends to supply the managed event-time column.
   *
   * # Errors
   *
   * Returns a napi error when `description_json` is not one describe
   * response, when the description declares a column the write path already
   * appends, or when the schema cannot be encoded.
   */
  writableSchemaIpc(descriptionJson: string, includeEventTime: boolean): Buffer
}

/** Native query stream that retains Rust terminal validation and emits raw IPC. */
export declare class NativeBifrostQueryStream {
  /** Returns the canonical server lifecycle request identity. */
  get requestId(): string
  /**
   * Returns one Arrow IPC batch or the final validated terminal.
   *
   * # Errors
   *
   * Returns a napi error carrying the stable Wyrd code for failed,
   * incomplete, malformed, or transport-terminated streams.
   */
  next(): Promise<NativeQueryStep>
  /** Drops the response stream so Rust transport cancellation propagates. */
  close(): Promise<void>
  /** Returns serialized terminal metadata after validated completion. */
  get terminalJson(): string | null
}

/** Structured result of starting a native terminal-safe query. */
export declare class NativeQueryStart {
  /** Moves the Rust-owned stream out after a successful startup. */
  takeStream(): NativeBifrostQueryStream | null
  /** Returns the stable SDK error code when startup failed. */
  get errorCode(): string | null
  /** Returns the HTTP-equivalent status when startup failed. */
  get errorStatus(): number | null
  /** Returns the stable title when startup failed. */
  get errorTitle(): string | null
  /** Returns the scrubbed SDK error detail when startup failed. */
  get errorDetail(): string | null
  /** Returns operator-facing remediation when startup failed. */
  get errorRemediation(): string | null
  /** Returns serialized JSON-safe structured details when startup failed. */
  get errorDetailsJson(): string | null
}

/**
 * Connects one authenticated write handle to the configured gRPC ingest plane.
 *
 * This is a free function rather than a constructor because connecting is
 * asynchronous and a napi constructor cannot be. The Python binding blocks
 * inside `__new__` instead; both reach the same handle.
 *
 * `serverUrl` selects the HTTP authentication plane and `grpcUrl` overrides
 * the ingest endpoint for split-plane and local test deployments.
 *
 * # Errors
 *
 * Returns a napi error for empty configuration, an unresolvable credential, or
 * a gRPC transport that cannot connect.
 */
export declare function connectBifrost(serverUrl: string, apiKey: string, grpcUrl?: string | undefined | null): Promise<NativeBifrost>

/**
 * `GenAI` filter request as JavaScript sends it.
 *
 * Window bounds arrive as RFC 3339 text because napi has no native chrono
 * projection; every field is optional so an unfiltered page is the default.
 */
export interface NativeGenAiRequest {
  /** Inclusive lower bound on event time, RFC 3339. */
  since?: string
  /** Exclusive upper bound on event time, RFC 3339. */
  until?: string
  /** Requested page size. */
  limit?: number
  /** Continuation token from a prior page. */
  pageToken?: string
  /** Conversation-id filter. */
  conversationId?: string
  /** Model-name filter. */
  model?: string
  /** Provider filter. */
  provider?: string
}

/** Structured native result for one live-query lifecycle control. */
export interface NativeLifecycleResult {
  /** Canonical JSON payload when the control succeeded. */
  valueJson?: string
  /** Stable SDK error code when the control failed. */
  errorCode?: string
  /** HTTP-equivalent status when the control failed. */
  errorStatus?: number
  /** Stable title when the control failed. */
  errorTitle?: string
  /** Scrubbed detail when the control failed. */
  errorDetail?: string
  /** Operator-facing remediation when the control failed. */
  errorRemediation?: string
  /** Serialized JSON-safe structured details when the control failed. */
  errorDetailsJson?: string
}

/** JavaScript query request projected onto the pure Wyrd contract. */
export interface NativeQueryRequest {
  /** SELECT-only SQL text. */
  sql: string
  /** `published_only` or `fused`. */
  visibility: string
  /** `strict` or `allow_degraded`. */
  freshness: string
  /** Optional positive query deadline. */
  deadlineMs?: number
}

/** One raw native iterator step consumed by the TypeScript Arrow facade. */
export interface NativeQueryStep {
  /** Complete Arrow IPC stream containing exactly one record batch. */
  ipc?: Buffer
  /** Serialized validated terminal, present only on the final step. */
  terminalJson?: string
  /** Stable SDK error code for a failed native step. */
  errorCode?: string
  /** HTTP-equivalent status for a failed native step. */
  errorStatus?: number
  /** Stable title for a failed native step. */
  errorTitle?: string
  /** Scrubbed SDK error detail for a failed native step. */
  errorDetail?: string
  /** Operator-facing remediation for a failed native step. */
  errorRemediation?: string
  /** Serialized JSON-safe structured details for a failed native step. */
  errorDetailsJson?: string
}
