/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Authenticated native query client sharing Wyrd's HTTP and auth pools. */
export declare class NativeBifrostQueryClient {
  /** Constructs a bearer-token query client without performing IO. */
  constructor(serverUrl: string, token: string)
  /**
   * Starts one terminal-safe query through the Rust SDK owner.
   *
   * Expected request, Gate, authentication, and transport failures are
   * returned in [`NativeQueryStart`] so JavaScript never has to parse an
   * exception message to recover the public Wyrd error contract.
   *
   * # Errors
   *
   * Returns a napi error only when napi cannot project the structured
   * startup result itself.
   */
  query(request: NativeQueryRequest): Promise<NativeQueryStart>
}

/** Native query stream that retains Rust terminal validation and emits raw IPC. */
export declare class NativeBifrostQueryStream {
  /**
   * Returns one Arrow IPC batch or the final validated terminal.
   *
   * # Errors
   *
   * Returns a napi error carrying the stable Wyrd code for failed,
   * incomplete, malformed, or transport-terminated streams.
   */
  next(): Promise<NativeQueryStep>
  /** Drops the response stream so Rust transport cancellation propagates. */
  close(): Promise<void>
  /** Returns serialized terminal metadata after validated completion. */
  get terminalJson(): string | null
}

/** Structured result of starting a native terminal-safe query. */
export declare class NativeQueryStart {
  /** Moves the Rust-owned stream out after a successful startup. */
  takeStream(): NativeBifrostQueryStream | null
  /** Returns the stable SDK error code when startup failed. */
  get errorCode(): string | null
  /** Returns the HTTP-equivalent status when startup failed. */
  get errorStatus(): number | null
  /** Returns the stable title when startup failed. */
  get errorTitle(): string | null
  /** Returns the scrubbed SDK error detail when startup failed. */
  get errorDetail(): string | null
  /** Returns operator-facing remediation when startup failed. */
  get errorRemediation(): string | null
}

/** JavaScript query request projected onto the pure Wyrd contract. */
export interface NativeQueryRequest {
  /** SELECT-only SQL text. */
  sql: string
  /** `published_only` or `fused`. */
  visibility: string
  /** `strict` or `allow_degraded`. */
  freshness: string
  /** Optional positive query deadline. */
  deadlineMs?: number
}

/** One raw native iterator step consumed by the TypeScript Arrow facade. */
export interface NativeQueryStep {
  /** Complete Arrow IPC stream containing exactly one record batch. */
  ipc?: Buffer
  /** Serialized validated terminal, present only on the final step. */
  terminalJson?: string
  /** Stable SDK error code for a failed native step. */
  errorCode?: string
  /** HTTP-equivalent status for a failed native step. */
  errorStatus?: number
  /** Stable title for a failed native step. */
  errorTitle?: string
  /** Scrubbed SDK error detail for a failed native step. */
  errorDetail?: string
  /** Operator-facing remediation for a failed native step. */
  errorRemediation?: string
}
