"""Generate the typed `cards.get` envelope for TypeScript and Python.

The `wyrd-spec` Card JSON Schema is the single source. This script reads
`crates/wyrd-spec/schemas/card.json`, keeps the envelope of the Card kinds the
SDKs type (`SUPPORTED_KINDS`) plus every definition those kinds reach, and
writes one TypeScript module and one Python `TypedDict` module. Both are
generated outputs: `mise run codegen:check` regenerates them and fails on
drift.

Schemas are lowered to a small intermediate form first so both languages emit
the same names. Inline object schemas (tagged-union variants, nested
properties) are hoisted into named types, and an object with shared
properties plus `oneOf` variants becomes one merged object per variant.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "crates/wyrd-spec/schemas/card.json"
TS_OUT = ROOT / "sdks/wyrd-sdk-ts/wyrd/src/card-types.ts"
PY_OUT = ROOT / "sdks/wyrd-sdk-python/python/wyrd/_card_types.py"

# Card kinds whose envelopes are typed; every other kind stays untyped until
# it is implemented and tested.
SUPPORTED_KINDS = [
    "Data",
    "Model",
    "Prompt",
    "Agent",
    "Verifier",
    "Service",
    "Trigger",
    "Operator",
]

HEADER = (
    "Generated by `mise run codegen:regen` from `crates/wyrd-spec/schemas/card.json`. Do not edit."
)

# Intermediate type expressions:
#   ("ref", name) | ("prim", kind) | ("lit", value) | ("array", t) | ("map", t)
#   | ("union", [t, ...])
# Named nodes:
#   ("object", [(key, t, required, description)], description)
#   | ("alias", t, description)


def pascal(text: str) -> str:
    """Return `text` as a PascalCase identifier fragment."""
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[^0-9A-Za-z]+", text) if part)


class Lowering:
    """Lower JSON Schema definitions into named intermediate nodes."""

    def __init__(self, definitions: dict) -> None:
        self.definitions = definitions
        self.nodes: dict[str, tuple] = {}
        self.pending: list[str] = []

    def require(self, name: str) -> str:
        """Queue a referenced definition for lowering and return its name."""
        if name not in self.nodes and name not in self.pending:
            self.pending.append(name)
        return name

    def drain(self) -> None:
        """Lower every queued definition, including definitions they reach."""
        while self.pending:
            name = self.pending.pop()
            if name not in self.nodes:
                self.define(name, self.definitions[name])

    def fresh(self, name: str) -> str:
        """Return a hoisted-type name that collides with no definition."""
        candidate, index = name, 2
        while candidate in self.nodes or candidate in self.definitions:
            candidate, index = f"{name}{index}", index + 1
        return candidate

    def define(self, name: str, schema: dict) -> None:
        """Lower one schema into the named node `name`."""
        description = schema.get("description")
        if self.is_object(schema) and not self.variants(schema):
            self.nodes[name] = ("object", [], description)
            self.nodes[name] = ("object", self.properties(name, schema), description)
        else:
            self.nodes[name] = ("alias", None, description)
            self.nodes[name] = ("alias", self.expr(name, schema), description)

    @staticmethod
    def variants(schema: dict) -> list:
        """Return a schema's `oneOf`/`anyOf` alternatives."""
        return schema.get("oneOf") or schema.get("anyOf") or []

    @staticmethod
    def is_object(schema: dict) -> bool:
        """Report whether a schema declares an object with named properties."""
        return "properties" in schema and schema.get("type", "object") == "object"

    def properties(self, owner: str, schema: dict, shared: dict | None = None) -> list:
        """Lower an object's properties, merging a union's `shared` properties."""
        shared = shared or {}
        merged = {**shared.get("properties", {}), **schema.get("properties", {})}
        required = set(schema.get("required", [])) | set(shared.get("required", []))
        return [
            (
                key,
                self.expr(owner + pascal(key), value),
                key in required,
                value.get("description") if isinstance(value, dict) else None,
            )
            for key, value in sorted(merged.items())
        ]

    def hoist(self, name: str, schema: dict, shared: dict | None = None) -> tuple:
        """Name one inline object schema and return a reference to it."""
        if "properties" not in schema:
            raise SystemExit(f"{name}: union variant sharing properties is not an inline object")
        name = self.fresh(name)
        self.nodes[name] = ("object", [], schema.get("description"))
        self.nodes[name] = (
            "object",
            self.properties(name, schema, shared),
            schema.get("description"),
        )
        return ("ref", name)

    @staticmethod
    def tag(schema: dict) -> str | None:
        """Return the single-value enum tag that names a union variant."""
        for value in schema.get("properties", {}).values():
            if isinstance(value, dict) and len(value.get("enum", [])) == 1:
                return value["enum"][0]
        return None

    def expr(self, owner: str, schema: dict | bool) -> tuple:
        """Lower one schema position into a type expression."""
        if schema is True or schema == {} or not isinstance(schema, dict):
            return ("prim", "any")
        if "$ref" in schema:
            return ("ref", self.require(schema["$ref"].split("/")[-1]))
        if "allOf" in schema:
            return self.expr(owner, schema["allOf"][0])
        variants = self.variants(schema)
        if variants:
            shared = schema if "properties" in schema else None
            members = []
            for index, variant in enumerate(variants, start=1):
                if shared is not None or self.is_object(variant):
                    keys = list(variant.get("properties", {}))
                    label = self.tag(variant) or (keys[0] if len(keys) == 1 else f"Variant{index}")
                    members.append(self.hoist(owner + pascal(label), variant, shared))
                else:
                    members.append(self.expr(f"{owner}Variant{index}", variant))
            return ("union", members)
        if "enum" in schema:
            return ("union", [("lit", value) for value in schema["enum"]])
        kinds = schema.get("type")
        if isinstance(kinds, list):
            return ("union", [self.expr(owner, {**schema, "type": kind}) for kind in kinds])
        if kinds == "array":
            return ("array", self.expr(owner + "Item", schema.get("items", True)))
        if kinds == "object" or "properties" in schema:
            if schema.get("properties"):
                return self.hoist(owner, schema)
            extra = schema.get("additionalProperties", True)
            return ("map", self.expr(owner + "Value", extra if extra is not False else True))
        if kinds in ("string", "integer", "number", "boolean", "null"):
            return ("prim", kinds)
        return ("prim", "any")


def flatten(expr: tuple) -> list[tuple]:
    """Flatten nested unions into one de-duplicated member list."""
    if expr[0] != "union":
        return [expr]
    members: list[tuple] = []
    for member in expr[1]:
        for flat in flatten(member):
            if flat not in members:
                members.append(flat)
    return members


class TypeScript:
    """Render intermediate nodes as TypeScript declarations."""

    PRIMS = {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
        "any": "unknown",
    }

    def expr(self, expr: tuple) -> str:
        """Render one type expression."""
        tag = expr[0]
        if tag == "ref":
            return expr[1]
        if tag == "prim":
            return self.PRIMS[expr[1]]
        if tag == "lit":
            return json.dumps(expr[1])
        if tag == "array":
            inner = self.expr(expr[1])
            wrap = " | " in inner or inner.startswith("readonly ")
            return f"readonly ({inner})[]" if wrap else f"readonly {inner}[]"
        if tag == "map":
            return f"Readonly<Record<string, {self.expr(expr[1])}>>"
        return " | ".join(dict.fromkeys(self.expr(member) for member in flatten(expr)))

    @staticmethod
    def doc(description: str | None, indent: str) -> list[str]:
        """Render a JSDoc block."""
        if not description:
            return []
        lines = description.replace("*/", "*\\/").splitlines()
        return [f"{indent}/**", *[f"{indent} * {line}".rstrip() for line in lines], f"{indent} */"]

    def render(self, nodes: dict[str, tuple]) -> str:
        """Render the complete TypeScript module."""
        out = [f"// {HEADER}", ""]
        for name in sorted(nodes):
            node = nodes[name]
            out.extend(self.doc(node[-1], ""))
            if node[0] == "alias":
                out.append(f"export type {name} = {self.expr(node[1])};")
            else:
                out.append(f"export interface {name} {{")
                for key, expr, required, description in node[1]:
                    out.extend(self.doc(description, "  "))
                    optional = "" if required else "?"
                    out.append(f"  readonly {key}{optional}: {self.expr(expr)};")
                out.append("}")
            out.append("")
        return "\n".join(out) + "\n"


class Python:
    """Render intermediate nodes as a runtime-importable `TypedDict` module."""

    PRIMS = {
        "string": "str",
        "integer": "int",
        "number": "float",
        "boolean": "bool",
        "null": "None",
        "any": "JsonValue",
    }

    def expr(self, expr: tuple) -> str:
        """Render one type expression."""
        tag = expr[0]
        if tag == "ref":
            return expr[1]
        if tag == "prim":
            return self.PRIMS[expr[1]]
        if tag == "lit":
            return f"Literal[{json.dumps(expr[1])}]"
        if tag == "array":
            return f"list[{self.expr(expr[1])}]"
        if tag == "map":
            return f"dict[str, {self.expr(expr[1])}]"
        members = flatten(expr)
        literals = [json.dumps(member[1]) for member in members if member[0] == "lit"]
        rendered = [self.expr(member) for member in members if member[0] != "lit"]
        if literals:
            rendered.insert(0, f"Literal[{', '.join(literals)}]")
        return " | ".join(dict.fromkeys(rendered))

    @staticmethod
    def docstring(description: str | None) -> list[str]:
        """Render a class docstring."""
        text = (description or "Generated Card schema type.").replace('"""', "'''")
        text = text.replace("\\", "\\\\").rstrip()
        if text.endswith('"'):
            text += " "
        lines = text.splitlines()
        if len(lines) == 1:
            return [f'    """{lines[0]}"""']
        return ['    """' + lines[0], *[f"    {line}".rstrip() for line in lines[1:]], '    """']

    @staticmethod
    def comment(description: str | None) -> list[str]:
        """Render a description as comment lines above a type alias."""
        if not description:
            return []
        return [f"# {line}".rstrip() for line in description.splitlines()]

    def klass(self, name: str, fields: list, description: str | None) -> list[str]:
        """Render one object as a `TypedDict`, split by requiredness."""
        required = [field for field in fields if field[2]]
        optional = [field for field in fields if not field[2]]
        body = lambda group: [f"    {key}: {self.expr(expr)}" for key, expr, _, _ in group]  # noqa: E731
        if required and optional:
            return [
                f"class _{name}Required(TypedDict):",
                f'    """Required keys of `{name}`."""',
                "",
                *body(required),
                "",
                "",
                f"class {name}(_{name}Required, total=False):",
                *self.docstring(description),
                "",
                *body(optional),
            ]
        total = "" if required else ", total=False"
        return [
            f"class {name}(TypedDict{total}):",
            *self.docstring(description),
            *([""] + body(required or optional) if fields else []),
        ]

    def render(self, nodes: dict[str, tuple]) -> str:
        """Render the complete Python module."""
        out = [
            f'"""{HEADER}"""',
            "",
            "from __future__ import annotations",
            "",
            "from typing import Literal, TypeAlias, TypedDict",
            "",
            "JsonValue: TypeAlias = 'str | int | float | bool | None | list[JsonValue] | dict[str, JsonValue]'",
            "",
        ]
        for name in sorted(nodes):
            node = nodes[name]
            out.append("")
            if node[0] == "alias":
                out.extend(self.comment(node[-1]))
                out.append(f"{name}: TypeAlias = '{self.expr(node[1])}'")
            else:
                out.append("")
                out.extend(self.klass(name, node[1], node[2]))
                out.append("")
        return "\n".join(out) + "\n"


def envelope(
    lowering: Lowering, schema: dict, name: str, kind: tuple, spec: tuple, description: str
) -> None:
    """Add one Card envelope node whose `kind` and `spec` are narrowed."""
    properties = schema["properties"]
    fields = []
    for key in sorted(properties):
        expr = {"kind": kind, "spec": spec}.get(key) or lowering.expr(
            name + pascal(key), properties[key]
        )
        fields.append((key, expr, key in schema["required"], properties[key].get("description")))
    lowering.nodes[name] = ("object", fields, description)


def lower() -> dict[str, tuple]:
    """Lower the supported Card envelopes and everything they reach.

    Each supported kind gets `Registered<Kind>Card` with its typed spec. Every
    other kind shares `RegisteredUntypedCard`, whose spec stays a JSON map, so
    `RegisteredCard` covers every envelope the registry can return while
    exposing typed specs only for the supported kinds.
    """
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    definitions = schema["definitions"]
    lowering = Lowering(definitions)
    names = []
    for kind in SUPPORTED_KINDS:
        name = f"Registered{kind}Card"
        spec = ("ref", lowering.require(f"{kind}Spec"))
        envelope(lowering, schema, name, ("lit", kind), spec, f"Registered `{kind}` Card envelope.")
        names.append(("ref", name))
    deferred = [kind for kind in definitions["CardKind"]["enum"] if kind not in SUPPORTED_KINDS]
    untyped = ("union", [("lit", kind) for kind in deferred])
    envelope(
        lowering,
        schema,
        "RegisteredUntypedCard",
        untyped,
        ("map", ("prim", "any")),
        "Registered Card envelope of a kind whose spec is not typed yet.",
    )
    names.append(("ref", "RegisteredUntypedCard"))
    lowering.nodes["TypedCardKind"] = (
        "alias",
        ("union", [("lit", kind) for kind in SUPPORTED_KINDS]),
        "Card kinds whose `spec` and `status` `cards.get` types.",
    )
    lowering.nodes["RegisteredCard"] = (
        "alias",
        ("union", names),
        "One registered Card envelope as `cards.get` returns it, discriminated by `kind`.",
    )
    lowering.drain()
    return lowering.nodes


def main() -> None:
    """Write both generated modules."""
    nodes = lower()
    TS_OUT.write_text(TypeScript().render(nodes), encoding="utf-8")
    PY_OUT.write_text(Python().render(nodes), encoding="utf-8")
    print(f"Wrote {len(nodes)} Card types to {TS_OUT} and {PY_OUT}", file=sys.stderr)


if __name__ == "__main__":
    main()
