[package]
name = "wyrd-cli"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
publish = false
autotests = false
description = "Wyrd command-line interface."

[lib]
name = "wyrd_cli"
path = "src/lib.rs"

[[bin]]
name = "wyrd"
path = "src/main.rs"

[[test]]
name = "cli"
path = "tests/cli.rs"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
indicatif = { workspace = true }
reqwest = { workspace = true }
secrecy = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
shellexpand = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
toml = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
vala-eval = { workspace = true }
vala-sql = { workspace = true }
wyrd-auth-issue = { workspace = true }
wyrd-client = { workspace = true }
wyrd-config = { workspace = true }
wyrd-error-derive = { workspace = true }

wyrd-loader = { workspace = true }
wyrd-registry = { workspace = true }
wyrd-semver = { workspace = true }
wyrd-spec = { workspace = true }
wyrd-sql = { workspace = true, features = ["embedded-postgres"] }

[dev-dependencies]
assert_cmd = "2"
axum = { workspace = true }
base64 = { workspace = true }
predicates = "3"
sha2 = { workspace = true }
tempfile = { workspace = true }
tokio-util = { workspace = true }
uuid = { workspace = true }
wiremock = { workspace = true }
wyrd-server = { workspace = true }
wyrd-sdk = { workspace = true }
wyrd-storage = { workspace = true }
wyrd-dev-fixtures = { workspace = true, features = ["pg"] }
wyrd-testing = { workspace = true }
