[package]
name = "wyrd-runtime"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
[dependencies]
chrono = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true, features = ["std", "v5", "v7"] }
wyrd-spec = { path = "../../wyrd-spec", version = "0.0.1" }

[dev-dependencies]
serde_json = { workspace = true }
wyrd-semver = { path = "../wyrd-semver", version = "0.0.1" }
