[package]
name = "wyrd-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
tokio.workspace = true
axum.workspace = true
tower.workspace = true
thiserror.workspace = true
wyrd-spec = { path = "../../wyrd-spec", version = "0.0.1" }
