name: lints-test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lints-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: sudo apt-get update && sudo apt-get install -y ripgrep
      - run: rustup target add wasm32-unknown-unknown
      - run: mise run pre-pr
